module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fHead0: { public: true, type: 'TEXT' },
     fHead1: { public: true, type: 'TEXT' },
     fHead2: { public: true, type: 'TEXT' },
     fHead3: { public: true, type: 'TEXT' },
     fHead4: { public: true, type: 'TEXT' },
     fFoot0: { public: true, type: 'TEXT' },
     fFoot1: { public: true, type: 'TEXT' },
     fFoot2: { public: true, type: 'TEXT' },
     fFoot3: { public: true, type: 'TEXT' },
     fFoot4: { public: true, type: 'TEXT' },
     fPrinterType: { public: true, type: 'INTEGER' },
     fMinCashLen: { public: true, type: 'INTEGER' },
     fCommPort: { public: true, type: 'TEXT' },
     fFiscalPrinter: { public: true, type: 'INTEGER' },
     fDisplayText: { public: true, type: 'TEXT' } } }