module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fNumber: { public: true, type: 'INTEGER' },
     fRegDate: { public: true, type: 'DATE' },
     fComment: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fSign: { public: true, type: 'TEXT' },
     TRVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fOvst: { public: true, type: 'INTEGER' },
           fAccNumber: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fDebVal: { public: true, type: 'FLOAT' },
           fCredVal: { public: true, type: 'FLOAT' },
           fVATCode: { public: true, type: 'TEXT' },
           fQty: { public: true, type: 'FLOAT' },
           fCurDebVal: { public: true, type: 'FLOAT' },
           fCurCredVal: { public: true, type: 'FLOAT' },
           fToRateB1: { public: true, type: 'FLOAT' },
           fComment: { public: true, type: 'TEXT' },
           fCurncy: { public: true, type: 'TEXT' },
           fBRSerNr: { public: true, type: 'INTEGER' },
           fBRRowNr: { public: true, type: 'INTEGER' },
           fNomVal: { public: true, type: 'FLOAT' },
           fCompCode: { public: true, type: 'TEXT' },
           fTyp: { public: true, type: 'INTEGER' },
           fSerNr: { public: true, type: 'INTEGER' },
           fDueDate: { public: true, type: 'DATE' },
           fCorspSer: { public: true, type: 'INTEGER' },
           fUpdDate: { public: true, type: 'DATE' },
           fSign: { public: true, type: 'TEXT' },
           fOldTransDate: { public: true, type: 'DATE' },
           fCorrNr: { public: true, type: 'INTEGER' },
           fCorrDate: { public: true, type: 'DATE' },
           fCorrYc: { public: true, type: 'INTEGER' },
           fReconsf: { public: true, type: 'INTEGER' },
           fFrRate: { public: true, type: 'FLOAT' },
           fToRateB2: { public: true, type: 'FLOAT' },
           fDebVal2: { public: true, type: 'FLOAT' },
           fCredVal2: { public: true, type: 'FLOAT' },
           fBaseRate1: { public: true, type: 'FLOAT' },
           fBaseRate2: { public: true, type: 'FLOAT' },
           fACShort: { public: true, type: 'TEXT' },
           fReconCode: { public: true, type: 'TEXT' },
           fTAccNumber: { public: true, type: 'TEXT' },
           fTFromFileName: { public: true, type: 'TEXT' },
           fTFromCode: { public: true, type: 'TEXT' },
           fSAFTType: { public: true, type: 'INTEGER' },
           fReconDate: { public: true, type: 'DATE' },
           fExtraComment: { public: true, type: 'TEXT' },
           fRvrsVATCode: { public: true, type: 'TEXT' } } },
     fDSum: { public: true, type: 'FLOAT' },
     fCSum: { public: true, type: 'FLOAT' },
     fDiffVal: { public: true, type: 'FLOAT' },
     fRefStr: { public: true, type: 'TEXT' },
     fXMainf: { public: true, type: 'INTEGER' },
     fIntYc: { public: true, type: 'INTEGER' },
     fXBalf: { public: true, type: 'INTEGER' },
     fExpf: { public: true, type: 'INTEGER' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fDSum2: { public: true, type: 'FLOAT' },
     fCSum2: { public: true, type: 'FLOAT' },
     fDiff2Val: { public: true, type: 'FLOAT' },
     fLastChangeDate: { public: true, type: 'DATE' },
     fFileName: { public: true, type: 'TEXT' },
     fTransNr: { public: true, type: 'INTEGER' },
     fSeqNr: { public: true, type: 'INTEGER' },
     fRegTime: { public: true, type: 'TIME' } },
  indexes: { NumberIndex45: { fields: [ 'fIntYc', 'fNumber' ], indicesType: 'UNIQUE' } } }