module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fCustCode: { public: true, type: 'TEXT' },
     fCustName: { public: true, type: 'TEXT' },
     fService: { public: true, type: 'TEXT' },
     fServiceName: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fClosed: { public: true, type: 'INTEGER' },
     fType: { public: true, type: 'INTEGER' },
     fExtraPerClick: { public: true, type: 'INTEGER' },
     fPerLength: { public: true, type: 'INTEGER' },
     fIVNr: { public: true, type: 'INTEGER' },
     TXCUServiceVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fTyp: { public: true, type: 'INTEGER' },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fPrice: { public: true, type: 'FLOAT' },
           fPrc: { public: true, type: 'FLOAT' },
           fText: { public: true, type: 'TEXT' } } },
     fCountdownClicks: { public: true, type: 'INTEGER' },
     fCountdownLTxt: { public: true, type: 'TEXT' },
     fNoInvoicing: { public: true, type: 'INTEGER' },
     fLastInvDate: { public: true, type: 'DATE' },
     fSalesMan: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex572: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }