module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fSessionID: { public: true, type: 'TEXT' },
     fMachineID: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fEffectCoef: { public: true, type: 'FLOAT' },
     TempProdPlanVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStartDate: { public: true, type: 'DATE' },
           fEndDate: { public: true, type: 'DATE' },
           fStartTime: { public: true, type: 'TIME' },
           fEndTime: { public: true, type: 'TIME' },
           fProdOpNr: { public: true, type: 'INTEGER' },
           fProdNr: { public: true, type: 'INTEGER' },
           fDur: { public: true, type: 'INTEGER' },
           fFixedFlag: { public: true, type: 'INTEGER' },
           fType: { public: true, type: 'INTEGER' },
           fAddClass: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fProdOpCode: { public: true, type: 'TEXT' },
           fProdRoute: { public: true, type: 'TEXT' },
           fSetupTime: { public: true, type: 'INTEGER' },
           fQty: { public: true, type: 'FLOAT' } } } },
  indexes: { SerNrIndex788: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }