module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fEventType: { public: true, type: 'TEXT' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fStartTime: { public: true, type: 'TIME' },
     fEndTime: { public: true, type: 'TIME' },
     fMinPersons: { public: true, type: 'INTEGER' },
     fMaxPersons: { public: true, type: 'INTEGER' },
     fMinAge: { public: true, type: 'INTEGER' },
     fMaxAge: { public: true, type: 'INTEGER' },
     fPriceType: { public: true, type: 'INTEGER' },
     fVECode: { public: true, type: 'TEXT' },
     fVEName: { public: true, type: 'TEXT' },
     fInvFlag: { public: true, type: 'INTEGER' },
     fStatusFlag: { public: true, type: 'INTEGER' },
     fInvMark: { public: true, type: 'INTEGER' },
     fStatusMark: { public: true, type: 'INTEGER' },
     fMotherEvent: { public: true, type: 'INTEGER' },
     fResCode: { public: true, type: 'TEXT' },
     fResLoc: { public: true, type: 'TEXT' },
     RsrtEventVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fJobNr: { public: true, type: 'INTEGER' },
           fGuestCode: { public: true, type: 'TEXT' },
           fGuestName: { public: true, type: 'TEXT' },
           fCustCode: { public: true, type: 'TEXT' },
           fCustName: { public: true, type: 'TEXT' },
           fExtraAssets: { public: true, type: 'TEXT' },
           fStatus: { public: true, type: 'INTEGER' },
           fIVNr: { public: true, type: 'INTEGER' },
           fDownPaidSent: { public: true, type: 'FLOAT' },
           fDownPaidInvd: { public: true, type: 'FLOAT' },
           fInvoicing: { public: true, type: 'INTEGER' },
           fPrice: { public: true, type: 'FLOAT' },
           fFromFileName: { public: true, type: 'TEXT' },
           fFromTransNr: { public: true, type: 'INTEGER' },
           fRsrtEventTypePack: { public: true, type: 'TEXT' },
           fSequenceNr: { public: true, type: 'INTEGER' },
           fStp: { public: true, type: 'INTEGER' } } },
     fTotQty: { public: true, type: 'INTEGER' },
     fIgnoreInEventsAvail: { public: true, type: 'INTEGER' },
     fScheduleStartTime: { public: true, type: 'TIME' },
     fScheduleEndTime: { public: true, type: 'TIME' },
     fVINr: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex667: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }