module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fOrdToDespDate: { public: true, type: 'INTEGER' },
     fUpdateGPWhenDel: { public: true, type: 'INTEGER' },
     fIVBasedOnSH: { public: true, type: 'INTEGER' },
     fQTClassToOR: { public: true, type: 'INTEGER' },
     fDelAddrOpt: { public: true, type: 'INTEGER' },
     fDontAllowOverreserving: { public: true, type: 'INTEGER' },
     fCredIVUpdateOR: { public: true, type: 'INTEGER' },
     fNoRetFromOR: { public: true, type: 'INTEGER' },
     fSetTransDateToServDelDate: { public: true, type: 'INTEGER' },
     fBackOrderComment: { public: true, type: 'TEXT' },
     fReqORClass: { public: true, type: 'INTEGER' },
     fConToPrepWhenInv: { public: true, type: 'INTEGER' },
     fRequireCustOrdNo: { public: true, type: 'INTEGER' },
     fRequireDeliveryAddress: { public: true, type: 'INTEGER' },
     fCreateIVonSHOK: { public: true, type: 'INTEGER' },
     fCreateIVonRetOK: { public: true, type: 'INTEGER' },
     fSHIncludesAllORRows: { public: true, type: 'INTEGER' },
     fSHShipSetToZero: { public: true, type: 'INTEGER' } } }