module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fFileName: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fKeyOne: { public: true, type: 'TEXT' },
     fKeyTwo: { public: true, type: 'TEXT' },
     fColName: { public: true, type: 'TEXT' },
     fVp: { public: true, type: 'FLOAT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fDv: { public: true, type: 'FLOAT' },
     fCv: { public: true, type: 'FLOAT' },
     fDv2: { public: true, type: 'FLOAT' },
     fCv2: { public: true, type: 'FLOAT' },
     fDcv: { public: true, type: 'FLOAT' },
     fCcv: { public: true, type: 'FLOAT' },
     fComment: { public: true, type: 'TEXT' },
     fXOriginalRecord: { public: true, type: 'INTEGER' },
     fKeyThree: { public: true, type: 'TEXT' },
     fXSource: { public: true, type: 'INTEGER' },
     fSerialNr: { public: true, type: 'TEXT' },
     fV1: { public: true, type: 'FLOAT' },
     fV2: { public: true, type: 'FLOAT' },
     fV3: { public: true, type: 'FLOAT' },
     fV4: { public: true, type: 'FLOAT' },
     fXperloc: { public: true, type: 'FLOAT' } },
  indexes: { SerNrIndex615: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }