module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fType: { public: true, type: 'TEXT' },
     fDuration: { public: true, type: 'TIME' },
     fNumber: { public: true, type: 'TEXT' },
     fTrunkNr: { public: true, type: 'TEXT' },
     fExtNo: { public: true, type: 'TEXT' },
     fCost: { public: true, type: 'FLOAT' },
     fTransDate: { public: true, type: 'DATE' },
     fTransTime: { public: true, type: 'TIME' },
     fRings: { public: true, type: 'INTEGER' },
     fStatus: { public: true, type: 'INTEGER' },
     fResCode: { public: true, type: 'TEXT' },
     fDirection: { public: true, type: 'INTEGER' },
     fRegType: { public: true, type: 'INTEGER' },
     fRegCode: { public: true, type: 'TEXT' },
     fPulses: { public: true, type: 'INTEGER' },
     fPerson: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex269: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }