module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fSRVarAcc: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fLocation: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fLocOKNr: { public: true, type: 'FLOAT' },
     fACShort: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fInvalidDate: { public: true, type: 'DATE' },
     fReason: { public: true, type: 'TEXT' },
     fTotQty: { public: true, type: 'FLOAT' },
     fTotDiff: { public: true, type: 'FLOAT' },
     SRVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fSpec: { public: true, type: 'TEXT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fQty: { public: true, type: 'FLOAT' },
           fLocation: { public: true, type: 'TEXT' },
           fPosCode: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fSRVarAcc: { public: true, type: 'TEXT' },
           fCoefficient: { public: true, type: 'FLOAT' },
           fUnitXval: { public: true, type: 'FLOAT' },
           fUnitYval: { public: true, type: 'FLOAT' },
           fUnitZval: { public: true, type: 'FLOAT' },
           fACShort: { public: true, type: 'TEXT' },
           fFIFO: { public: true, type: 'FLOAT' },
           fFIFORowVal: { public: true, type: 'FLOAT' },
           fNewFIFO: { public: true, type: 'FLOAT' },
           fNewFIFORowVal: { public: true, type: 'FLOAT' },
           fDiffFIFO: { public: true, type: 'FLOAT' },
           fDiffFIFORowVal: { public: true, type: 'FLOAT' },
           fVEInvoiceNr: { public: true, type: 'TEXT' } } },
     fSign: { public: true, type: 'TEXT' },
     fSalesGroup: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex630: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }