module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fAddr1: { public: true, type: 'TEXT' },
     fAddr2: { public: true, type: 'TEXT' },
     fAddr3: { public: true, type: 'TEXT' },
     fAddr4: { public: true, type: 'TEXT' },
     fContact: { public: true, type: 'TEXT' },
     fPhone: { public: true, type: 'TEXT' },
     fFax: { public: true, type: 'TEXT' },
     fEmail: { public: true, type: 'TEXT' },
     fPriceList: { public: true, type: 'TEXT' },
     fInvoiceBase: { public: true, type: 'INTEGER' },
     fIncludeOriginalItem: { public: true, type: 'INTEGER' },
     fIncludePeriod: { public: true, type: 'INTEGER' },
     fAddEmptyLine: { public: true, type: 'INTEGER' },
     fUseAsQty: { public: true, type: 'INTEGER' },
     fGroupInvoice: { public: true, type: 'INTEGER' },
     fIncludeSite: { public: true, type: 'INTEGER' },
     fInclCustOrdNr: { public: true, type: 'INTEGER' },
     fInclRentResNo: { public: true, type: 'INTEGER' },
     fOnePerReservation: { public: true, type: 'INTEGER' } },
  indexes: { CodeIndex358: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }