module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fNodeToItemBrowse: { public: true, type: 'INTEGER' },
     fNodeToShopBasket: { public: true, type: 'INTEGER' },
     fItemBrowseTemplate: { public: true, type: 'TEXT' },
     fShopBasketTemplate: { public: true, type: 'TEXT' },
     fRecommendItemsTemplate: { public: true, type: 'TEXT' },
     fItemOrderTemplate: { public: true, type: 'TEXT' },
     fNodeToItemOrder: { public: true, type: 'TEXT' },
     fNodeToShopApp: { public: true, type: 'INTEGER' },
     fNodeToItemImageApp: { public: true, type: 'INTEGER' },
     fShopPerCountry: { public: true, type: 'INTEGER' },
     fShopBasketTemplPage: { public: true, type: 'TEXT' },
     fShopBasketTemplElement: { public: true, type: 'TEXT' },
     fShopCatalogTemplPage: { public: true, type: 'TEXT' },
     fShopCatalogTemplElement: { public: true, type: 'TEXT' },
     fAfterAddToBasketAction: { public: true, type: 'INTEGER' },
     fAfterAddToBasketPage: { public: true, type: 'TEXT' },
     fPayTypeCreditCard: { public: true, type: 'INTEGER' },
     fPayTypeInvoice: { public: true, type: 'INTEGER' },
     fPayTypeDirectDebit: { public: true, type: 'INTEGER' },
     fPayTypePayPal: { public: true, type: 'INTEGER' },
     fPayCheckoutElement: { public: true, type: 'TEXT' },
     fAllowRequestingQuotes: { public: true, type: 'INTEGER' },
     fSendPasswordBySMS: { public: true, type: 'INTEGER' },
     fAfterAddToBasketElement: { public: true, type: 'TEXT' },
     fShowStockLevel: { public: true, type: 'INTEGER' },
     fForceLanguage: { public: true, type: 'INTEGER' } } }