module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fServerType: { public: true, type: 'INTEGER' },
     fAllowServers: { public: true, type: 'INTEGER' },
     fHideIOS: { public: true, type: 'INTEGER' },
     fCurrentVersion: { public: true, type: 'TEXT' },
     fTestVersion: { public: true, type: 'TEXT' },
     fDevVersion: { public: true, type: 'TEXT' },
     fPMAccess: { public: true, type: 'TEXT' },
     fDownServerAddr: { public: true, type: 'TEXT' },
     fSmallCurrentVersion: { public: true, type: 'TEXT' },
     fSmallTestVersion: { public: true, type: 'TEXT' },
     fSmallDevVersion: { public: true, type: 'TEXT' },
     fDevVerAccess: { public: true, type: 'TEXT' },
     fHALSourceAccess: { public: true, type: 'TEXT' } } }