module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fOrderNr: { public: true, type: 'INTEGER' },
     fVINr: { public: true, type: 'INTEGER' },
     fPrepaymentNr: { public: true, type: 'INTEGER' },
     fVIInvDate: { public: true, type: 'DATE' },
     fVIRegDate: { public: true, type: 'DATE' },
     fVIDueDate: { public: true, type: 'DATE' },
     fVIRebDate: { public: true, type: 'DATE' },
     fVITransDate: { public: true, type: 'DATE' },
     fInvoiceNr: { public: true, type: 'TEXT' },
     fRefStr: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fVECode: { public: true, type: 'TEXT' },
     fVEName: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fOKPersons: { public: true, type: 'TEXT' },
     fPayVal: { public: true, type: 'FLOAT' },
     fRebVal: { public: true, type: 'FLOAT' },
     fVATVal: { public: true, type: 'FLOAT' },
     fCalcVATVal: { public: true, type: 'FLOAT' },
     fHoldSum: { public: true, type: 'FLOAT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fInvType: { public: true, type: 'INTEGER' },
     fExportFlag: { public: true, type: 'INTEGER' },
     fPayDeal: { public: true, type: 'TEXT' },
     fVEVatCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fPrelBook: { public: true, type: 'INTEGER' },
     fCredInv: { public: true, type: 'INTEGER' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fCredMark: { public: true, type: 'TEXT' },
     fVATNr: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fSortCode: { public: true, type: 'TEXT' },
     fSalesGroup: { public: true, type: 'TEXT' },
     fSalesMan: { public: true, type: 'TEXT' },
     fContractStr: { public: true, type: 'TEXT' },
     fVEEventNr: { public: true, type: 'TEXT' },
     fVEEventDate: { public: true, type: 'DATE' },
     fPMComment: { public: true, type: 'TEXT' },
     fOPNr: { public: true, type: 'INTEGER' },
     FEVIVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fOvst: { public: true, type: 'INTEGER' },
           fAccNumber: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fSum: { public: true, type: 'FLOAT' },
           fPrepayAmount: { public: true, type: 'FLOAT' },
           fVATVal: { public: true, type: 'FLOAT' },
           fQty: { public: true, type: 'FLOAT' },
           fItem: { public: true, type: 'TEXT' },
           fPRCode: { public: true, type: 'TEXT' },
           fVATCode: { public: true, type: 'TEXT' },
           fVEPNr: { public: true, type: 'INTEGER' },
           fPrepayNr: { public: true, type: 'INTEGER' },
           fACShort: { public: true, type: 'TEXT' },
           fOrdRow: { public: true, type: 'INTEGER' },
           fVIRow: { public: true, type: 'INTEGER' },
           fSign: { public: true, type: 'TEXT' },
           fOldTransDate: { public: true, type: 'DATE' } } },
     fRebVal2: { public: true, type: 'FLOAT' },
     fVIRebDate2: { public: true, type: 'DATE' } },
  indexes: { SerNrIndex375: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }