module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     LegalInvNrBlockMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fPurchDate: { public: true, type: 'DATE' },
           fSerie: { public: true, type: 'TEXT' },
           fTSerStart: { public: true, type: 'TEXT' },
           fTSerEnd: { public: true, type: 'TEXT' },
           fTSerCom: { public: true, type: 'TEXT' },
           fCClass: { public: true, type: 'TEXT' },
           fEndDate: { public: true, type: 'DATE' },
           fPerPage: { public: true, type: 'INTEGER' },
           fApprovalNr: { public: true, type: 'TEXT' },
           fApprovalYear: { public: true, type: 'TEXT' },
           fCertificateNr: { public: true, type: 'TEXT' },
           fCertificate: { public: true, type: 'TEXT' },
           fPrivateKey: { public: true, type: 'TEXT' },
           fPassphrase: { public: true, type: 'TEXT' },
           fLocalMachineCode: { public: true, type: 'TEXT' },
           fBranch: { public: true, type: 'TEXT' },
           fRegType: { public: true, type: 'INTEGER' },
           fSelectionType: { public: true, type: 'INTEGER' },
           fChronology: { public: true, type: 'INTEGER' },
           fOutArgEInvoices: { public: true, type: 'INTEGER' },
           fTaxAuthID: { public: true, type: 'TEXT' },
           fDosageKey: { public: true, type: 'TEXT' } } } } }