module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fClosed: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fPBXType: { public: true, type: 'INTEGER' },
     fPBXTapiTSP: { public: true, type: 'TEXT' },
     fPBXHost: { public: true, type: 'TEXT' },
     fPBXPort: { public: true, type: 'TEXT' },
     fPBXUser: { public: true, type: 'TEXT' },
     fPBXPassword: { public: true, type: 'TEXT' },
     fIntPrefix: { public: true, type: 'TEXT' },
     fCountryCode: { public: true, type: 'TEXT' },
     fDefAreaCode: { public: true, type: 'TEXT' },
     fSkipDigit: { public: true, type: 'TEXT' },
     PBXConnectionVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fPBXRuleType: { public: true, type: 'INTEGER' },
           fPBXRuleIdentifier: { public: true, type: 'TEXT' },
           fPBXRuleComment: { public: true, type: 'TEXT' } } },
     fRemoteConfigDir: { public: true, type: 'TEXT' },
     fRemoteUser: { public: true, type: 'TEXT' },
     fUpdateOnRecordChangef: { public: true, type: 'INTEGER' },
     fIAXf: { public: true, type: 'INTEGER' },
     fIAXPassword: { public: true, type: 'TEXT' },
     fPBXHostIP: { public: true, type: 'TEXT' },
     fXDefaultCallerId: { public: true, type: 'TEXT' },
     fExtLinePrefix: { public: true, type: 'TEXT' },
     fAsteriskController: { public: true, type: 'TEXT' },
     fAsteriskControllerKey: { public: true, type: 'TEXT' },
     fAsteriskControllerPort: { public: true, type: 'INTEGER' } },
  indexes: { CodeIndex185: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }