module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fWONr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fEMCode: { public: true, type: 'TEXT' },
     fEMName: { public: true, type: 'TEXT' },
     fCustCode: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fInvFlag: { public: true, type: 'INTEGER' },
     fCustContact: { public: true, type: 'TEXT' },
     fSum0: { public: true, type: 'FLOAT' },
     fSum1: { public: true, type: 'FLOAT' },
     fSum2: { public: true, type: 'FLOAT' },
     fSum3: { public: true, type: 'FLOAT' },
     fSum4: { public: true, type: 'FLOAT' },
     fObjects: { public: true, type: 'TEXT' },
     fPhone: { public: true, type: 'TEXT' },
     fFax: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fInvoiceToCode: { public: true, type: 'TEXT' },
     fComment1: { public: true, type: 'TEXT' },
     fComment2: { public: true, type: 'TEXT' },
     fComment3: { public: true, type: 'TEXT' },
     fComment4: { public: true, type: 'TEXT' },
     fLocation: { public: true, type: 'TEXT' },
     fCustCat: { public: true, type: 'TEXT' },
     fPriceList: { public: true, type: 'TEXT' },
     fRebCode: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fExportFlag: { public: true, type: 'INTEGER' },
     fCustVATCode: { public: true, type: 'TEXT' },
     fInclVAT: { public: true, type: 'INTEGER' },
     fOVc: { public: true, type: 'INTEGER' },
     fArtCode: { public: true, type: 'TEXT' },
     fSerialNr: { public: true, type: 'TEXT' },
     fSpec: { public: true, type: 'TEXT' },
     fMaxCost: { public: true, type: 'FLOAT' },
     fPrelOK: { public: true, type: 'INTEGER' },
     fSVONr: { public: true, type: 'INTEGER' },
     fLocOKNr: { public: true, type: 'FLOAT' },
     fSalesGroup: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fACShort: { public: true, type: 'TEXT' },
     fCostAcc: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fInvalidDate: { public: true, type: 'DATE' },
     fUpdStockFlag: { public: true, type: 'INTEGER' },
     WSVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fPrice: { public: true, type: 'FLOAT' },
           fSum: { public: true, type: 'FLOAT' },
           fVRebate: { public: true, type: 'FLOAT' },
           fSalesAcc: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fBasePrice: { public: true, type: 'FLOAT' },
           fSpec: { public: true, type: 'TEXT' },
           fVATCode: { public: true, type: 'TEXT' },
           fRecepy: { public: true, type: 'TEXT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fOvst: { public: true, type: 'INTEGER' },
           fInvd: { public: true, type: 'FLOAT' },
           fVARList: { public: true, type: 'TEXT' },
           fItemType: { public: true, type: 'INTEGER' },
           fQtyInvbl: { public: true, type: 'FLOAT' },
           fMotherNr: { public: true, type: 'TEXT' },
           fFIFO: { public: true, type: 'FLOAT' },
           fFIFORowVal: { public: true, type: 'FLOAT' },
           fCoefficient: { public: true, type: 'FLOAT' },
           fPosCode: { public: true, type: 'TEXT' },
           fCostAcc: { public: true, type: 'TEXT' },
           fACShort: { public: true, type: 'TEXT' },
           fReturned: { public: true, type: 'FLOAT' },
           fTaxTemplateCode: { public: true, type: 'TEXT' },
           fTaxMatrix: { public: true, type: 'TEXT' } } },
     fCustTaxTemplateCode: { public: true, type: 'TEXT' },
     fTaxMatrix: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex184: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }