module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fDays: { public: true, type: 'TEXT' },
     fFromDate: { public: true, type: 'DATE' },
     fToDate: { public: true, type: 'DATE' },
     fStartTime: { public: true, type: 'TIME' },
     fEndTime: { public: true, type: 'TIME' },
     fCost: { public: true, type: 'FLOAT' },
     fArtCode: { public: true, type: 'TEXT' },
     fDistance: { public: true, type: 'FLOAT' },
     fResCode: { public: true, type: 'TEXT' },
     fComment1: { public: true, type: 'TEXT' },
     fMaxQty: { public: true, type: 'INTEGER' },
     fMinQty: { public: true, type: 'INTEGER' },
     fExGroup: { public: true, type: 'TEXT' },
     fMaxAge: { public: true, type: 'INTEGER' },
     fMinAge: { public: true, type: 'INTEGER' },
     fPrio: { public: true, type: 'INTEGER' },
     fBeforeTime1: { public: true, type: 'INTEGER' },
     fBeforeTime2: { public: true, type: 'INTEGER' },
     fSource: { public: true, type: 'TEXT' },
     fDestination: { public: true, type: 'TEXT' },
     fPlace: { public: true, type: 'TEXT' },
     fVECode: { public: true, type: 'TEXT' },
     fVEName: { public: true, type: 'TEXT' },
     fSexFlag: { public: true, type: 'INTEGER' } },
  indexes: { CodeIndex330: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }