module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCourseCode: { public: true, type: 'TEXT' },
     fCourseName: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fStartDate: { public: true, type: 'DATE' },
     fStartTime: { public: true, type: 'TIME' },
     fEndDate: { public: true, type: 'DATE' },
     fEndTime: { public: true, type: 'TIME' },
     fStartDate2: { public: true, type: 'DATE' },
     fStartTime2: { public: true, type: 'TIME' },
     fEndDate2: { public: true, type: 'DATE' },
     fEndTime2: { public: true, type: 'TIME' },
     fStartDate3: { public: true, type: 'DATE' },
     fStartTime3: { public: true, type: 'TIME' },
     fEndDate3: { public: true, type: 'DATE' },
     fEndTime3: { public: true, type: 'TIME' },
     UnivTestVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fQuestion: { public: true, type: 'TEXT' },
           fAlt1: { public: true, type: 'TEXT' },
           fAlt2: { public: true, type: 'TEXT' },
           fAlt3: { public: true, type: 'TEXT' },
           fAlt4: { public: true, type: 'TEXT' },
           fAlt5: { public: true, type: 'TEXT' },
           fAlt6: { public: true, type: 'TEXT' },
           fAlt1Correct: { public: true, type: 'INTEGER' },
           fAlt2Correct: { public: true, type: 'INTEGER' },
           fAlt3Correct: { public: true, type: 'INTEGER' },
           fAlt4Correct: { public: true, type: 'INTEGER' },
           fAlt5Correct: { public: true, type: 'INTEGER' },
           fAlt6Correct: { public: true, type: 'INTEGER' } } },
     fUser: { public: true, type: 'TEXT' },
     fSalesGroup: { public: true, type: 'TEXT' },
     fNoOfQuestions: { public: true, type: 'INTEGER' },
     fCorrAnsToPass: { public: true, type: 'INTEGER' } },
  indexes: 
   { CourseCodeIndex548: 
      { fields: [ 'fCourseCode', 'fLangCode' ],
        indicesType: 'UNIQUE' } } }