module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fArtCode: { public: true, type: 'TEXT' },
     fSerialNr: { public: true, type: 'TEXT' },
     fStatusCode: { public: true, type: 'TEXT' },
     fAnalyseDate: { public: true, type: 'DATE' },
     fNewBestBefore: { public: true, type: 'DATE' },
     fNextAnalyseDate: { public: true, type: 'DATE' },
     fTestedBy: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fSerNr: { public: true, type: 'INTEGER' },
     fAgreementNr: { public: true, type: 'INTEGER' },
     fRentResSerNo: { public: true, type: 'INTEGER' },
     fVc: { public: true, type: 'INTEGER' },
     fVcSerNr: { public: true, type: 'INTEGER' },
     fQCTemplate: { public: true, type: 'TEXT' },
     QualConVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fQCTest: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fQCUnit: { public: true, type: 'TEXT' },
           fFrom: { public: true, type: 'FLOAT' },
           fTo: { public: true, type: 'FLOAT' },
           fResult: { public: true, type: 'FLOAT' } } },
     fCompletedBy: { public: true, type: 'TEXT' },
     fAnalyseTime: { public: true, type: 'TIME' },
     fStandProblem: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex121: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }