module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fCompName: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fAddr1: { public: true, type: 'TEXT' },
     fAddr2: { public: true, type: 'TEXT' },
     fAddr3: { public: true, type: 'TEXT' },
     fAddr4: { public: true, type: 'TEXT' },
     fTel: { public: true, type: 'TEXT' },
     fFaxNo: { public: true, type: 'TEXT' },
     fRegNr: { public: true, type: 'TEXT' },
     fVATNo: { public: true, type: 'TEXT' },
     fSyncSumPOS: { public: true, type: 'INTEGER' } },
  indexes: { CodeIndex516: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }