module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fSignature: { public: true, type: 'TEXT' },
     fTotQty: { public: true, type: 'FLOAT' },
     fTotPriceBefore: { public: true, type: 'FLOAT' },
     fTotPriceAfter: { public: true, type: 'FLOAT' },
     fTotVATBefore: { public: true, type: 'FLOAT' },
     fTotVATAfter: { public: true, type: 'FLOAT' },
     fComment0: { public: true, type: 'TEXT' },
     fComment1: { public: true, type: 'TEXT' },
     fComment2: { public: true, type: 'TEXT' },
     fComment3: { public: true, type: 'TEXT' },
     BPCVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fSpec: { public: true, type: 'TEXT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fQty: { public: true, type: 'FLOAT' },
           fBasePriceBefore: { public: true, type: 'FLOAT' },
           fBasePriceAfter: { public: true, type: 'FLOAT' },
           fVATCode: { public: true, type: 'TEXT' },
           fUnitCode: { public: true, type: 'TEXT' },
           fPurPrice: { public: true, type: 'FLOAT' },
           fPurSum: { public: true, type: 'FLOAT' },
           fPurExtraCost: { public: true, type: 'FLOAT' },
           fMarginPerc: { public: true, type: 'FLOAT' },
           fBasePriceAfterSum: { public: true, type: 'FLOAT' },
           fBasePriceAfterInclVAT: { public: true, type: 'FLOAT' },
           fBasePriceAfterSumInclVAT: { public: true, type: 'FLOAT' },
           fVATSum: { public: true, type: 'FLOAT' },
           fPriceFactor: { public: true, type: 'FLOAT' },
           fTaxTemplateCode: { public: true, type: 'TEXT' },
           fTaxMatrix: { public: true, type: 'TEXT' } } },
     fLocation: { public: true, type: 'TEXT' },
     fInclVAT: { public: true, type: 'INTEGER' },
     fTaxMatrix: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex177: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }