module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     VATCodeBlockMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fVATCode: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fExVatpr: { public: true, type: 'FLOAT' },
           fIncVatpr: { public: true, type: 'FLOAT' },
           fSalesVATAcc: { public: true, type: 'TEXT' },
           fPurchVATAcc: { public: true, type: 'TEXT' },
           fTax1pr: { public: true, type: 'FLOAT' },
           fTax1Acc: { public: true, type: 'TEXT' },
           fPayPurchVATAcc: { public: true, type: 'TEXT' },
           fPaySalesVATAcc: { public: true, type: 'TEXT' },
           fExcludeFromOfficial: { public: true, type: 'INTEGER' },
           fCorSalesVATAcc: { public: true, type: 'TEXT' },
           fCorPurchVATAcc: { public: true, type: 'TEXT' },
           fTax1OppAcc: { public: true, type: 'TEXT' },
           fTax1Min: { public: true, type: 'FLOAT' },
           fTaxRules: { public: true, type: 'TEXT' },
           fCredSalesVATAcc: { public: true, type: 'TEXT' },
           fCredPurchVATAcc: { public: true, type: 'TEXT' },
           fInclinTotal: { public: true, type: 'INTEGER' },
           fTaxMatrixVariance: { public: true, type: 'TEXT' },
           fValidUntil: { public: true, type: 'DATE' },
           fHotelWIPAcc: { public: true, type: 'TEXT' },
           fMinBaseAmount: { public: true, type: 'FLOAT' },
           fMaxBaseAmount: { public: true, type: 'FLOAT' },
           fCalcRule: { public: true, type: 'INTEGER' },
           fREDpr: { public: true, type: 'FLOAT' },
           fSTExVatpr: { public: true, type: 'FLOAT' },
           fMinRvrsVAT: { public: true, type: 'FLOAT' },
           fVATRateTier: { public: true, type: 'TEXT' } } } } }