module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fDateCreated: { public: true, type: 'DATE' },
     fRespPerson: { public: true, type: 'TEXT' },
     fSalesGroup: { public: true, type: 'TEXT' },
     fBudgetSum: { public: true, type: 'FLOAT' },
     fCostSum: { public: true, type: 'FLOAT' },
     fRevenueSum: { public: true, type: 'FLOAT' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fMediaType: { public: true, type: 'TEXT' },
     fMediaComment: { public: true, type: 'TEXT' },
     fStatus: { public: true, type: 'TEXT' },
     fStatusComment: { public: true, type: 'TEXT' },
     fCampaign: { public: true, type: 'TEXT' },
     CampaignVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fCodeType: { public: true, type: 'INTEGER' },
           fCode: { public: true, type: 'TEXT' },
           fName: { public: true, type: 'TEXT' },
           fPerson: { public: true, type: 'TEXT' } } } },
  indexes: { CodeIndex844: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }