module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fYearCode: { public: true, type: 'INTEGER' },
     fType: { public: true, type: 'INTEGER' },
     fJan: { public: true, type: 'INTEGER' },
     fFeb: { public: true, type: 'INTEGER' },
     fMar: { public: true, type: 'INTEGER' },
     fApr: { public: true, type: 'INTEGER' },
     fMay: { public: true, type: 'INTEGER' },
     fJun: { public: true, type: 'INTEGER' },
     fJul: { public: true, type: 'INTEGER' },
     fAug: { public: true, type: 'INTEGER' },
     fSep: { public: true, type: 'INTEGER' },
     fOct: { public: true, type: 'INTEGER' },
     fNov: { public: true, type: 'INTEGER' },
     fDec: { public: true, type: 'INTEGER' } },
  indexes: { YearCodeIndex524: { fields: [ 'fYearCode', 'fType' ], indicesType: 'UNIQUE' } } }