module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fEmployee: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fSign: { public: true, type: 'TEXT' },
     fLeaveActType: { public: true, type: 'TEXT' },
     fDays: { public: true, type: 'FLOAT' },
     fFwdBalDays: { public: true, type: 'FLOAT' },
     fRemDays: { public: true, type: 'FLOAT' },
     fAcceptanceStatus: { public: true, type: 'INTEGER' },
     fAcceptanceBy: { public: true, type: 'TEXT' },
     fAcceptanceFYI: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex719: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }