module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fBankName: { public: true, type: 'TEXT' },
     fChargeType: { public: true, type: 'TEXT' },
     fBranch: { public: true, type: 'TEXT' },
     fModality: { public: true, type: 'TEXT' },
     fCustAccount: { public: true, type: 'TEXT' },
     fAccountNr: { public: true, type: 'TEXT' },
     fLastBankReceiptNr: { public: true, type: 'INTEGER' },
     fMailHeader: { public: true, type: 'TEXT' },
     fMailText: { public: true, type: 'TEXT' },
     fStatus: { public: true, type: 'INTEGER' },
     fHost: { public: true, type: 'TEXT' },
     fPath: { public: true, type: 'TEXT' },
     fFormat: { public: true, type: 'INTEGER' },
     fComment1: { public: true, type: 'TEXT' },
     fComment2: { public: true, type: 'TEXT' },
     fComment3: { public: true, type: 'TEXT' },
     fComment4: { public: true, type: 'TEXT' },
     fComment5: { public: true, type: 'TEXT' },
     fComment6: { public: true, type: 'TEXT' },
     fComment7: { public: true, type: 'TEXT' },
     fComment8: { public: true, type: 'TEXT' } } }