module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fMainStock: { public: true, type: 'TEXT' },
     fDontAllowOvership: { public: true, type: 'INTEGER' },
     fRequireLocation: { public: true, type: 'INTEGER' },
     fDefServiceLoc: { public: true, type: 'TEXT' },
     fUpdateSVGM: { public: true, type: 'INTEGER' },
     fUpdateAvailable: { public: true, type: 'INTEGER' },
     fCalcFIFO: { public: true, type: 'INTEGER' },
     fChronology: { public: true, type: 'INTEGER' },
     fLastOKNr: { public: true, type: 'FLOAT' },
     fDelivPlainItems: { public: true, type: 'INTEGER' },
     fAllowInvBeforeShip: { public: true, type: 'INTEGER' },
     fDelivSetBatch: { public: true, type: 'INTEGER' },
     fDelOrdQty: { public: true, type: 'INTEGER' },
     fRecevPlainItems: { public: true, type: 'INTEGER' },
     fUnitConvCalc: { public: true, type: 'INTEGER' },
     fStartClass: { public: true, type: 'TEXT' },
     fNoSerOnPU: { public: true, type: 'INTEGER' },
     fDemandPosition: { public: true, type: 'INTEGER' },
     fSetDelDateToCurrent: { public: true, type: 'INTEGER' },
     fDontCalcWAPerLoc: { public: true, type: 'INTEGER' },
     fDontAllowOverreceive: { public: true, type: 'INTEGER' },
     fAllowInvBeforePU: { public: true, type: 'INTEGER' },
     fSortBatchOnBestBefore: { public: true, type: 'INTEGER' },
     fXForcePlanDelDate: { public: true, type: 'INTEGER' },
     fSamePriceforItemonSR: { public: true, type: 'INTEGER' },
     fPONoOnPURowsOnly: { public: true, type: 'INTEGER' },
     fStockCorectAfter: { public: true, type: 'DATE' },
     fRecalcStockNeeded: { public: true, type: 'INTEGER' },
     fChronologyOkOnly: { public: true, type: 'INTEGER' },
     fChkSerNumOnNonStockIVCash: { public: true, type: 'INTEGER' },
     fExtraCostsCalculation: { public: true, type: 'INTEGER' },
     fForceReason: { public: true, type: 'INTEGER' } } }