module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fVECode: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fAddr1: { public: true, type: 'TEXT' },
     fAddr2: { public: true, type: 'TEXT' },
     fAddr3: { public: true, type: 'TEXT' },
     fVEContact: { public: true, type: 'TEXT' },
     fExportFlag: { public: true, type: 'INTEGER' },
     fOrderedFlag: { public: true, type: 'INTEGER' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fCountryCode: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fShipDeal: { public: true, type: 'TEXT' },
     fShipMode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fFromLocation: { public: true, type: 'TEXT' },
     fInsCurncy: { public: true, type: 'TEXT' },
     fShpCurncy: { public: true, type: 'TEXT' },
     fDiv1Curncy: { public: true, type: 'TEXT' },
     fDiv2Curncy: { public: true, type: 'TEXT' },
     fInsVal: { public: true, type: 'FLOAT' },
     fInsPrc: { public: true, type: 'FLOAT' },
     fShpVal: { public: true, type: 'FLOAT' },
     fDiv1Val: { public: true, type: 'FLOAT' },
     fDiv2Val: { public: true, type: 'FLOAT' },
     fLocalTransVal: { public: true, type: 'FLOAT' },
     fLocalTrans2Val: { public: true, type: 'FLOAT' },
     fCusDecKey: { public: true, type: 'TEXT' },
     fTransitNumber: { public: true, type: 'TEXT' },
     fPriceRange: { public: true, type: 'TEXT' },
     fWeight: { public: true, type: 'FLOAT' },
     fVolume: { public: true, type: 'FLOAT' },
     fSumCostPrice: { public: true, type: 'FLOAT' },
     fTotFOBVal: { public: true, type: 'FLOAT' },
     fTotFOBLocalVal: { public: true, type: 'FLOAT' },
     fNrOffPackages: { public: true, type: 'FLOAT' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fNoChargesFlag: { public: true, type: 'INTEGER' },
     fLetOfConv: { public: true, type: 'TEXT' },
     fNrOffShpP: { public: true, type: 'INTEGER' },
     fNrOffInvP: { public: true, type: 'INTEGER' },
     fNrOffOtherP: { public: true, type: 'INTEGER' },
     fOtherPapers: { public: true, type: 'TEXT' },
     fFixedNumber: { public: true, type: 'TEXT' },
     fCargoNumber: { public: true, type: 'TEXT' },
     fArrivalCode: { public: true, type: 'TEXT' },
     fToLocation: { public: true, type: 'TEXT' },
     fSumCustoms: { public: true, type: 'FLOAT' },
     fPurInvVal: { public: true, type: 'FLOAT' },
     fVYKey: { public: true, type: 'TEXT' },
     CustomsVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fOvst: { public: true, type: 'INTEGER' },
           fPONr: { public: true, type: 'INTEGER' },
           fPORowNr: { public: true, type: 'INTEGER' },
           fArtCode: { public: true, type: 'TEXT' },
           fArtDesc: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fVEArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fVEQuant: { public: true, type: 'FLOAT' },
           fPrice: { public: true, type: 'FLOAT' },
           fSum: { public: true, type: 'FLOAT' },
           fWeight: { public: true, type: 'FLOAT' },
           fVolume: { public: true, type: 'FLOAT' },
           fFOBVal: { public: true, type: 'FLOAT' },
           fCustomsVal: { public: true, type: 'FLOAT' },
           fDutiesVal: { public: true, type: 'FLOAT' },
           fRowCost: { public: true, type: 'FLOAT' },
           fCommodityCode: { public: true, type: 'TEXT' },
           fCommodityDesc: { public: true, type: 'TEXT' },
           fCountryCode: { public: true, type: 'TEXT' },
           fDutiesCodes: { public: true, type: 'TEXT' },
           fChargesCodes: { public: true, type: 'TEXT' },
           fVATCode: { public: true, type: 'TEXT' },
           fChargesVal: { public: true, type: 'FLOAT' },
           fAlcPrc: { public: true, type: 'FLOAT' },
           fATaxPrc: { public: true, type: 'FLOAT' },
           fATaxVal: { public: true, type: 'FLOAT' } } },
     fInvAddr3: { public: true, type: 'TEXT' },
     fInvAddr4: { public: true, type: 'TEXT' },
     fRefStr: { public: true, type: 'TEXT' },
     fTransNumber: { public: true, type: 'TEXT' },
     fDeliveryType: { public: true, type: 'INTEGER' },
     fNetWeight: { public: true, type: 'FLOAT' },
     fCustomsOrgNr: { public: true, type: 'TEXT' },
     fShipState: { public: true, type: 'TEXT' },
     fWarehouse: { public: true, type: 'TEXT' },
     fPayMethod: { public: true, type: 'TEXT' },
     fOrigCode: { public: true, type: 'TEXT' },
     fFrightDiv: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex100: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }