module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fBookDate: { public: true, type: 'DATE' },
     fCUCode: { public: true, type: 'TEXT' },
     fCUName: { public: true, type: 'TEXT' },
     fContact: { public: true, type: 'TEXT' },
     fResCode: { public: true, type: 'TEXT' },
     fBookStart: { public: true, type: 'TIME' },
     fBookEnd: { public: true, type: 'TIME' },
     fPersons: { public: true, type: 'INTEGER' },
     fPhone: { public: true, type: 'TEXT' },
     fTable: { public: true, type: 'TEXT' },
     fMath: { public: true, type: 'TEXT' },
     fType: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fResLoc: { public: true, type: 'TEXT' },
     fMachineName: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex399: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }