module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fAppleID: { public: true, type: 'TEXT' },
     fPassword: { public: true, type: 'TEXT' },
     fAccountNo: { public: true, type: 'TEXT' },
     fSessionID: { public: true, type: 'TEXT' },
     fInstanceID: { public: true, type: 'TEXT' },
     fSessionCreatedDate: { public: true, type: 'DATE' },
     fSessionCreatedTime: { public: true, type: 'TIME' },
     fLiveFlag: { public: true, type: 'INTEGER' },
     fShipToAccount: { public: true, type: 'TEXT' },
     fRegionCType: { public: true, type: 'TEXT' },
     fPartsAutoUpdate: { public: true, type: 'INTEGER' },
     fAppleItemCode: { public: true, type: 'INTEGER' },
     fAutoEnrollmentInterval: { public: true, type: 'TIME' },
     fGroupInvoicing: { public: true, type: 'INTEGER' },
     fPOCDeliveryPreference: { public: true, type: 'INTEGER' } } }