module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fEMCode: { public: true, type: 'TEXT' },
     fEMName: { public: true, type: 'TEXT' },
     fCustCode: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fCustContact: { public: true, type: 'TEXT' },
     fSVONr: { public: true, type: 'INTEGER' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fSumCostVal: { public: true, type: 'FLOAT' },
     fSumSalesVal: { public: true, type: 'FLOAT' },
     fSumQuant: { public: true, type: 'FLOAT' },
     fComment1: { public: true, type: 'TEXT' },
     fComment2: { public: true, type: 'TEXT' },
     fComment3: { public: true, type: 'TEXT' },
     fComment4: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     SVGMVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fInQuant: { public: true, type: 'FLOAT' },
           fOutQuant: { public: true, type: 'FLOAT' },
           fVARList: { public: true, type: 'TEXT' },
           fSpec: { public: true, type: 'TEXT' },
           fCostPrice: { public: true, type: 'FLOAT' },
           fSalesPrice: { public: true, type: 'FLOAT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fPlanShiprw: { public: true, type: 'TEXT' },
           fSoldDate: { public: true, type: 'DATE' },
           fWarrantyUntil: { public: true, type: 'DATE' },
           fLocation: { public: true, type: 'TEXT' },
           fMotherNr: { public: true, type: 'TEXT' },
           fVECode: { public: true, type: 'TEXT' },
           fContact: { public: true, type: 'TEXT' } } },
     fLangCode: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex191: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }