module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fCurrency: { public: true, type: 'TEXT' },
     fAmount: { public: true, type: 'FLOAT' },
     fFromPayURL: { public: true, type: 'TEXT' },
     fSessionID: { public: true, type: 'TEXT' },
     fPaid: { public: true, type: 'INTEGER' },
     fCreatedDate: { public: true, type: 'DATE' },
     fPaidDate: { public: true, type: 'DATE' },
     fPartner: { public: true, type: 'TEXT' },
     fMerchantid: { public: true, type: 'TEXT' },
     fMerchantcode: { public: true, type: 'TEXT' },
     fMerchantaccref: { public: true, type: 'TEXT' },
     fMerchantkey: { public: true, type: 'TEXT' },
     fMerchantrefundpw: { public: true, type: 'TEXT' },
     fMerchanttestaddr: { public: true, type: 'INTEGER' },
     fMerchantserialnr: { public: true, type: 'TEXT' },
     fMerchantlivef: { public: true, type: 'INTEGER' },
     fName: { public: true, type: 'TEXT' },
     fAddr1: { public: true, type: 'TEXT' },
     fAddr2: { public: true, type: 'TEXT' },
     fAddr3: { public: true, type: 'TEXT' },
     fPostcode: { public: true, type: 'TEXT' },
     fCountry: { public: true, type: 'TEXT' },
     fLastname: { public: true, type: 'TEXT' },
     fKey2: { public: true, type: 'TEXT' },
     fProfile_id: { public: true, type: 'TEXT' },
     fAccess_key: { public: true, type: 'TEXT' } },
  indexes: { CodeIndex586: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }