module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fServerUUID: { public: true, type: 'TEXT' },
     fFileName: { public: true, type: 'TEXT' },
     fFileType: { public: true, type: 'INTEGER' },
     fState: { public: true, type: 'INTEGER' },
     fServerName: { public: true, type: 'TEXT' },
     fCUCode: { public: true, type: 'TEXT' },
     fFilePath: { public: true, type: 'TEXT' },
     fUpdatedFlag: { public: true, type: 'INTEGER' },
     fController: { public: true, type: 'TEXT' },
     fCreatedDate: { public: true, type: 'DATE' },
     fCreatedTime: { public: true, type: 'TIME' },
     fDateChanged: { public: true, type: 'DATE' },
     fTimeChanged: { public: true, type: 'TIME' },
     fAmazonRegion: { public: true, type: 'TEXT' },
     fUUID: { public: true, type: 'TEXT' } },
  indexes: { MainKeyIndex836: { fields: [ 'fUUID' ], indicesType: 'UNIQUE' } } }