module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fBranchID: { public: true, type: 'TEXT' },
     fBranchName: { public: true, type: 'TEXT' },
     TableLayoutVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fTable0: { public: true, type: 'TEXT' },
           fTable1: { public: true, type: 'TEXT' },
           fTable2: { public: true, type: 'TEXT' },
           fTable3: { public: true, type: 'TEXT' },
           fTable4: { public: true, type: 'TEXT' },
           fTable5: { public: true, type: 'TEXT' },
           fTable6: { public: true, type: 'TEXT' },
           fTable7: { public: true, type: 'TEXT' },
           fTable8: { public: true, type: 'TEXT' },
           fTable9: { public: true, type: 'TEXT' } } },
     fVertical: { public: true, type: 'INTEGER' },
     fHorizontal: { public: true, type: 'INTEGER' },
     fMachineName: { public: true, type: 'TEXT' } },
  indexes: { CodeIndex658: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }