module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fComment1: { public: true, type: 'TEXT' },
     fFrTime1: { public: true, type: 'TIME' },
     fToTime1: { public: true, type: 'TIME' },
     fComment2: { public: true, type: 'TEXT' },
     fFrTime2: { public: true, type: 'TIME' },
     fToTime2: { public: true, type: 'TIME' },
     fComment3: { public: true, type: 'TEXT' },
     fFrTime3: { public: true, type: 'TIME' },
     fToTime3: { public: true, type: 'TIME' },
     fComment4: { public: true, type: 'TEXT' },
     fFrTime4: { public: true, type: 'TIME' },
     fToTime4: { public: true, type: 'TIME' },
     fComment5: { public: true, type: 'TEXT' },
     fFrTime5: { public: true, type: 'TIME' },
     fToTime5: { public: true, type: 'TIME' },
     fComplimentaryUsage: { public: true, type: 'TEXT' },
     fStaffUsage: { public: true, type: 'TEXT' },
     fMeetingType: { public: true, type: 'TEXT' } } }