module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fArtCode: { public: true, type: 'TEXT' },
     fVariety: { public: true, type: 'TEXT' },
     fLocation: { public: true, type: 'TEXT' },
     fFileName: { public: true, type: 'TEXT' },
     fTransNr: { public: true, type: 'INTEGER' },
     fRow: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fStockAffectf: { public: true, type: 'INTEGER' },
     fQty: { public: true, type: 'FLOAT' },
     fQty2: { public: true, type: 'FLOAT' },
     fRemQty: { public: true, type: 'FLOAT' },
     fSource: { public: true, type: 'INTEGER' },
     fTotCostPrice: { public: true, type: 'FLOAT' },
     fSerialNr: { public: true, type: 'TEXT' },
     fRemCostPrice: { public: true, type: 'FLOAT' },
     fFIFODate: { public: true, type: 'DATE' },
     fWATotCost: { public: true, type: 'FLOAT' },
     fCPTotCost: { public: true, type: 'FLOAT' },
     fBPTotCost: { public: true, type: 'FLOAT' },
     fWATotCostPerLoc: { public: true, type: 'FLOAT' },
     fCPTotCostPerLoc: { public: true, type: 'FLOAT' },
     fBPTotCostPerLoc: { public: true, type: 'FLOAT' },
     fPosition: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fSerNrPerLoc: { public: true, type: 'FLOAT' },
     fVECode: { public: true, type: 'TEXT' },
     fConsigStock: { public: true, type: 'INTEGER' },
     fWillBePurged: { public: true, type: 'INTEGER' },
     fTREOStock: { public: true, type: 'INTEGER' },
     fPrimaryCostModel: { public: true, type: 'INTEGER' },
     fQueuedCostModel: { public: true, type: 'INTEGER' },
     fFIFOPerLocation: { public: true, type: 'INTEGER' },
     fItemType: { public: true, type: 'INTEGER' },
     fFIFOPerSerialNr: { public: true, type: 'INTEGER' },
     fNoNLCostOnShip: { public: true, type: 'INTEGER' },
     fWAPerLocation: { public: true, type: 'INTEGER' },
     fWABase2: { public: true, type: 'INTEGER' },
     fUpdWeightAvFromRetPU: { public: true, type: 'INTEGER' },
     fUpdWeightAvFromRet: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex51: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }