module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fFileName: { public: true, type: 'TEXT' },
     fCustID: { public: true, type: 'TEXT' },
     fCustSerNr: { public: true, type: 'TEXT' },
     fStatus: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fFileNameDesc: { public: true, type: 'TEXT' },
     fCreationDate: { public: true, type: 'DATE' },
     fCreationTime: { public: true, type: 'TIME' },
     fSent: { public: true, type: 'INTEGER' },
     fCompID: { public: true, type: 'TEXT' },
     fCustVersionNr: { public: true, type: 'INTEGER' },
     fDBID: { public: true, type: 'TEXT' },
     fTheirRecipient: { public: true, type: 'TEXT' },
     fType: { public: true, type: 'INTEGER' },
     fVATNr: { public: true, type: 'TEXT' },
     fRegNr1: { public: true, type: 'TEXT' },
     fCompNr: { public: true, type: 'INTEGER' },
     fCAE: { public: true, type: 'TEXT' },
     fCAEExpiry: { public: true, type: 'DATE' },
     fCAEAFlag: { public: true, type: 'INTEGER' },
     fCustRecRowNr: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex454: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }