module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fNumber: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fVATCode: { public: true, type: 'TEXT' },
     fDutiesCodes: { public: true, type: 'TEXT' },
     fChargesCodes: { public: true, type: 'TEXT' },
     fLicencesCodes: { public: true, type: 'TEXT' },
     fProhibitsCodes: { public: true, type: 'TEXT' },
     fIndicationCodes: { public: true, type: 'TEXT' },
     fDemandNo: { public: true, type: 'INTEGER' },
     fDemandQty: { public: true, type: 'INTEGER' },
     fGattPrc: { public: true, type: 'FLOAT' },
     fGattAmount: { public: true, type: 'FLOAT' },
     fGattBaseQty: { public: true, type: 'INTEGER' },
     fLiterBased: { public: true, type: 'INTEGER' },
     fNetweightBased: { public: true, type: 'INTEGER' },
     fImportFlag: { public: true, type: 'INTEGER' },
     fATaxPrc: { public: true, type: 'FLOAT' },
     fATaxVal: { public: true, type: 'FLOAT' } },
  indexes: { NumberIndex102: { fields: [ 'fNumber' ], indicesType: 'UNIQUE' } } }