module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fCustCode: { public: true, type: 'TEXT' },
     fCustName: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fAddr1: { public: true, type: 'TEXT' },
     fAddr2: { public: true, type: 'TEXT' },
     fAddr3: { public: true, type: 'TEXT' },
     fAddr4: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fRefStr: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fDocType: { public: true, type: 'TEXT' },
     fPassportNr: { public: true, type: 'TEXT' },
     fNationality: { public: true, type: 'TEXT' },
     fBirthDate: { public: true, type: 'DATE' },
     fTotal: { public: true, type: 'FLOAT' },
     fBaseTotal: { public: true, type: 'FLOAT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fDrawer: { public: true, type: 'TEXT' },
     fTransTime: { public: true, type: 'TIME' },
     fMachineName: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fType: { public: true, type: 'INTEGER' },
     fTypeMark: { public: true, type: 'INTEGER' },
     fPayMode: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex691: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }