module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fProdOrdNr: { public: true, type: 'INTEGER' },
     fSequence: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fPlanDurTime: { public: true, type: 'TIME' },
     fPlanDurDays: { public: true, type: 'INTEGER' },
     ProdOperationVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fItem: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fMaterial: { public: true, type: 'TEXT' },
           fInQty: { public: true, type: 'FLOAT' },
           fOutQty: { public: true, type: 'FLOAT' },
           fActualInQty: { public: true, type: 'FLOAT' },
           fActualOutQty: { public: true, type: 'FLOAT' },
           fItemCost: { public: true, type: 'FLOAT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fBestBefore: { public: true, type: 'DATE' },
           fRelVal: { public: true, type: 'FLOAT' },
           fFIFORowVal: { public: true, type: 'FLOAT' },
           fCoefficient: { public: true, type: 'FLOAT' },
           fObjects: { public: true, type: 'TEXT' },
           fPosCode: { public: true, type: 'TEXT' },
           fDiscarded: { public: true, type: 'INTEGER' },
           fStandProblem: { public: true, type: 'TEXT' } } },
     fDoneFlag: { public: true, type: 'INTEGER' },
     fProdDate: { public: true, type: 'DATE' },
     fLocation: { public: true, type: 'TEXT' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fStartTime: { public: true, type: 'TIME' },
     fEndTime: { public: true, type: 'TIME' },
     fPRStatusFlag: { public: true, type: 'INTEGER' },
     fFinnishedFlag: { public: true, type: 'INTEGER' },
     fStdOperation: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fQty: { public: true, type: 'FLOAT' },
     fActualQty: { public: true, type: 'FLOAT' },
     fLocOKNr: { public: true, type: 'FLOAT' },
     fStandProblem: { public: true, type: 'TEXT' },
     fMachineGroup: { public: true, type: 'TEXT' },
     fDisplayGroup: { public: true, type: 'TEXT' },
     fMachine: { public: true, type: 'TEXT' },
     fPerson: { public: true, type: 'TEXT' },
     fProdNr: { public: true, type: 'INTEGER' },
     fRowsHoldActualQty: { public: true, type: 'INTEGER' },
     fMath2: { public: true, type: 'TEXT' },
     fBatchTime: { public: true, type: 'INTEGER' },
     fSubSequence: { public: true, type: 'INTEGER' },
     fSetupTime: { public: true, type: 'TIME' },
     fQueueTime: { public: true, type: 'TIME' },
     fMoveTime: { public: true, type: 'TIME' },
     fRunTime: { public: true, type: 'TIME' } },
  indexes: { SerNrIndex530: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }