module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fMainPersons: { public: true, type: 'TEXT' },
     fCCPersons: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fTransTime: { public: true, type: 'TIME' },
     fLTxtCode: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fAlarmType: { public: true, type: 'INTEGER' },
     fActSerNr: { public: true, type: 'INTEGER' },
     fCompNo: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fSender: { public: true, type: 'TEXT' },
     fStdTxt: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex527: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }