module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fSipTrunk: { public: true, type: 'TEXT' },
     fClosed: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fExtension: { public: true, type: 'TEXT' },
     fDefaultContact: { public: true, type: 'TEXT' },
     fOpenTime: { public: true, type: 'TIME' },
     fCloseTime: { public: true, type: 'TIME' },
     fQueueID: { public: true, type: 'INTEGER' },
     fOpenTime2: { public: true, type: 'TIME' },
     fCloseTime2: { public: true, type: 'TIME' },
     fFallBackNumber: { public: true, type: 'TEXT' },
     fNoGeneralSIPFallback: { public: true, type: 'INTEGER' },
     fCRMCompany: { public: true, type: 'TEXT' },
     fExcludeBankHolidaysf: { public: true, type: 'INTEGER' },
     fActReached: { public: true, type: 'TEXT' },
     fActReachedDone: { public: true, type: 'INTEGER' },
     fActOpen: { public: true, type: 'TEXT' },
     fActOpenDone: { public: true, type: 'INTEGER' },
     fAlwaysClosedf: { public: true, type: 'INTEGER' } },
  indexes: { CodeIndex826: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }