module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fSign: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fSimFlag: { public: true, type: 'INTEGER' },
     fDSum: { public: true, type: 'FLOAT' },
     fCSum: { public: true, type: 'FLOAT' },
     fDiffVal: { public: true, type: 'FLOAT' },
     fXMainf: { public: true, type: 'INTEGER' },
     fBalf: { public: true, type: 'INTEGER' },
     FBVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fAccNumber: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fX1: { public: true, type: 'TEXT' },
           fDebVal: { public: true, type: 'FLOAT' },
           fCredVal: { public: true, type: 'FLOAT' },
           fDeb2Val: { public: true, type: 'FLOAT' },
           fCred2Val: { public: true, type: 'FLOAT' },
           fCurDebVal: { public: true, type: 'FLOAT' },
           fCurCredVal: { public: true, type: 'FLOAT' },
           fCurncyCode: { public: true, type: 'TEXT' } } },
     fD2Sum: { public: true, type: 'FLOAT' },
     fC2Sum: { public: true, type: 'FLOAT' },
     fDiff2Val: { public: true, type: 'FLOAT' } },
  indexes: { SerNrIndex42: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }