module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fHostName: { public: true, type: 'TEXT' },
     fHansaPort: { public: true, type: 'INTEGER' },
     fSSLPort: { public: true, type: 'INTEGER' },
     fLastCheckDate: { public: true, type: 'DATE' },
     fLastCheckTime: { public: true, type: 'TIME' },
     fServerDiskTotal: { public: true, type: 'INTEGER' },
     fServerDiskFree: { public: true, type: 'INTEGER' },
     fNewHansaVersion: { public: true, type: 'TEXT' },
     fClosed: { public: true, type: 'INTEGER' },
     fXActForAutoServers: { public: true, type: 'INTEGER' },
     fLastSeenDate: { public: true, type: 'DATE' },
     fLastSeenTime: { public: true, type: 'TIME' },
     fReachableFlag: { public: true, type: 'INTEGER' },
     fVersionBuild: { public: true, type: 'INTEGER' },
     fFastCheckFlag: { public: true, type: 'INTEGER' },
     fCurrentState: { public: true, type: 'INTEGER' },
     fIs64BitFlag: { public: true, type: 'INTEGER' },
     fCustCode: { public: true, type: 'TEXT' },
     fXIsAutonode: { public: true, type: 'INTEGER' },
     fWebPort: { public: true, type: 'INTEGER' },
     fAmazonInstanceType: { public: true, type: 'TEXT' },
     fAmazonInstanceId: { public: true, type: 'TEXT' },
     fAmazonImageId: { public: true, type: 'TEXT' },
     fAmazonKernelId: { public: true, type: 'TEXT' },
     fAmazonPrivateIP: { public: true, type: 'TEXT' },
     fAmazonPublicDNS: { public: true, type: 'TEXT' },
     fHostingConfig: { public: true, type: 'INTEGER' },
     fHostingConfigComment: { public: true, type: 'TEXT' },
     fAdminUser: { public: true, type: 'TEXT' },
     fAmazonElasticIP: { public: true, type: 'TEXT' },
     fPlatform: { public: true, type: 'INTEGER' },
     fClassification: { public: true, type: 'TEXT' },
     fXActForTestAutoServers: { public: true, type: 'INTEGER' },
     fXActForMigrServers: { public: true, type: 'INTEGER' },
     fHostPoolType: { public: true, type: 'INTEGER' },
     fMaxCapacity: { public: true, type: 'INTEGER' },
     fNodeType: { public: true, type: 'INTEGER' },
     fServerDiskMaxUsed: { public: true, type: 'INTEGER' } },
  indexes: { MainKeyIndex556: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }