module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fDoneFlag: { public: true, type: 'INTEGER' },
     fStartDate: { public: true, type: 'DATE' },
     fStartTime: { public: true, type: 'TIME' },
     fEndDate: { public: true, type: 'DATE' },
     fEndTime: { public: true, type: 'TIME' },
     fDueDate: { public: true, type: 'DATE' },
     fDurTime: { public: true, type: 'TIME' },
     fDurDays: { public: true, type: 'INTEGER' },
     fQueuePos: { public: true, type: 'INTEGER' },
     fQty: { public: true, type: 'FLOAT' },
     fFinished: { public: true, type: 'FLOAT' },
     fObjects: { public: true, type: 'TEXT' },
     fLocation: { public: true, type: 'TEXT' },
     fLengthClass: { public: true, type: 'INTEGER' },
     fMachine: { public: true, type: 'TEXT' },
     fPerson: { public: true, type: 'TEXT' },
     fRecName: { public: true, type: 'TEXT' },
     fComment1: { public: true, type: 'TEXT' },
     fComment2: { public: true, type: 'TEXT' },
     fComment3: { public: true, type: 'TEXT' },
     fRecipe: { public: true, type: 'TEXT' },
     ProdOrderVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fItem: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fInQty: { public: true, type: 'FLOAT' },
           fOutQty: { public: true, type: 'FLOAT' },
           fObjects: { public: true, type: 'TEXT' },
           fOutBatchStatus: { public: true, type: 'TEXT' },
           fUnitXval: { public: true, type: 'FLOAT' },
           fUnitYval: { public: true, type: 'FLOAT' },
           fUnitZval: { public: true, type: 'FLOAT' },
           fCoefficient: { public: true, type: 'FLOAT' },
           fRelVal: { public: true, type: 'FLOAT' },
           fItemCost: { public: true, type: 'FLOAT' },
           fExtraCost: { public: true, type: 'FLOAT' },
           fFIFORowVal: { public: true, type: 'FLOAT' },
           fMaterial: { public: true, type: 'TEXT' } } },
     fFinnishedFlag: { public: true, type: 'INTEGER' },
     fSalesOrder: { public: true, type: 'INTEGER' },
     fInstr0: { public: true, type: 'TEXT' },
     fInstr1: { public: true, type: 'TEXT' },
     fInstr2: { public: true, type: 'TEXT' },
     fSetUpTime: { public: true, type: 'TIME' },
     fDiscarded: { public: true, type: 'FLOAT' },
     fStatusFlag: { public: true, type: 'INTEGER' },
     fXScale: { public: true, type: 'FLOAT' },
     fPlannedStartDate: { public: true, type: 'DATE' },
     fExtraProdQty: { public: true, type: 'FLOAT' },
     fLangCode: { public: true, type: 'TEXT' },
     fReserved: { public: true, type: 'INTEGER' },
     fRouting: { public: true, type: 'TEXT' },
     fProdClass: { public: true, type: 'TEXT' },
     fPriority: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex67: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }