module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fMainPersons: { public: true, type: 'TEXT' },
     fCCPersons: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fStartTime: { public: true, type: 'TIME' },
     fEndTime: { public: true, type: 'TIME' },
     fCostTime: { public: true, type: 'TIME' },
     fCUCode: { public: true, type: 'TEXT' },
     fCUName: { public: true, type: 'TEXT' },
     fContact: { public: true, type: 'TEXT' },
     fPhone: { public: true, type: 'TEXT' },
     fActType: { public: true, type: 'TEXT' },
     fActResult: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fPrioLevel: { public: true, type: 'INTEGER' },
     fPrivateFlag: { public: true, type: 'INTEGER' },
     fTodoFlag: { public: true, type: 'INTEGER' },
     fCalTimeFlag: { public: true, type: 'INTEGER' },
     fPRCode: { public: true, type: 'TEXT' },
     fItemCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     ActVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fTextCode: { public: true, type: 'TEXT' },
           fText: { public: true, type: 'TEXT' } } },
     fLengthClass: { public: true, type: 'INTEGER' },
     fResources: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fTimeClass: { public: true, type: 'TEXT' },
     fSymbNr: { public: true, type: 'INTEGER' },
     fSupervisor: { public: true, type: 'TEXT' },
     fCreationDate: { public: true, type: 'DATE' },
     fLastChangedDate: { public: true, type: 'DATE' },
     fLangCode: { public: true, type: 'TEXT' },
     fUserStr1: { public: true, type: 'TEXT' },
     fUserStr2: { public: true, type: 'TEXT' },
     fUserStr3: { public: true, type: 'TEXT' },
     fUserStr4: { public: true, type: 'TEXT' },
     fUserStr5: { public: true, type: 'TEXT' },
     fUserVal1: { public: true, type: 'FLOAT' },
     fUserVal2: { public: true, type: 'FLOAT' },
     fUserVal3: { public: true, type: 'FLOAT' },
     fUserDate1: { public: true, type: 'DATE' },
     fUserDate2: { public: true, type: 'DATE' },
     fUserDate3: { public: true, type: 'DATE' },
     fArtCode: { public: true, type: 'TEXT' },
     fSerialNr: { public: true, type: 'TEXT' },
     fSVOSerNr: { public: true, type: 'INTEGER' },
     fProdSerNr: { public: true, type: 'INTEGER' },
     fAlarmType: { public: true, type: 'INTEGER' },
     fAlarmWhen: { public: true, type: 'INTEGER' },
     fAlarmUnits: { public: true, type: 'INTEGER' },
     fExternalType: { public: true, type: 'INTEGER' },
     fExternalID: { public: true, type: 'TEXT' },
     fInventoryNr: { public: true, type: 'TEXT' },
     fProdOpSerNr: { public: true, type: 'INTEGER' },
     fMother: { public: true, type: 'INTEGER' },
     fTRSerNr: { public: true, type: 'INTEGER' },
     fRsrtEventSerNr: { public: true, type: 'INTEGER' },
     fAutoGenCallFlag: { public: true, type: 'INTEGER' },
     fFromFileName: { public: true, type: 'TEXT' },
     fFromSerNr: { public: true, type: 'TEXT' },
     fActTypeComment: { public: true, type: 'TEXT' },
     fNextApprovers: { public: true, type: 'TEXT' },
     fNextApproversType: { public: true, type: 'INTEGER' },
     fNextFYIPersons: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fValue: { public: true, type: 'FLOAT' },
     fApprovalFwdPersons: { public: true, type: 'TEXT' },
     fFromCompanyNr: { public: true, type: 'INTEGER' },
     fPBXQueues: { public: true, type: 'TEXT' },
     fRecurringType: { public: true, type: 'INTEGER' },
     fRecurringWeekDay: { public: true, type: 'INTEGER' },
     fRecurringMonthDay: { public: true, type: 'INTEGER' },
     fPlannedDate: { public: true, type: 'DATE' },
     fPlannedTime: { public: true, type: 'TIME' },
     fRecurringActSerNr: { public: true, type: 'INTEGER' },
     fRecurringMonth: { public: true, type: 'INTEGER' },
     fActState: { public: true, type: 'TEXT' },
     fCountryCode: { public: true, type: 'TEXT' },
     fAvoidRedDays: { public: true, type: 'INTEGER' },
     fActStateComment: { public: true, type: 'TEXT' },
     fPRName: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex110: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }