module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fTable: { public: true, type: 'TEXT' },
     fWaiter: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fSeats: { public: true, type: 'INTEGER' },
     fTableLayoutName: { public: true, type: 'TEXT' },
     fXPos: { public: true, type: 'INTEGER' },
     fYPos: { public: true, type: 'INTEGER' },
     fWidth: { public: true, type: 'INTEGER' },
     fHeight: { public: true, type: 'INTEGER' },
     fShape: { public: true, type: 'INTEGER' },
     fBranchID: { public: true, type: 'TEXT' },
     fTableViewCode: { public: true, type: 'TEXT' } },
  indexes: { TableIndex328: { fields: [ 'fTable' ], indicesType: 'UNIQUE' } } }