module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fCode: { public: true, type: 'TEXT' },
     fDescription: { public: true, type: 'TEXT' },
     fMonStart: { public: true, type: 'TIME' },
     fMonEnd: { public: true, type: 'FLOAT' },
     fTueStart: { public: true, type: 'TIME' },
     fTueEnd: { public: true, type: 'FLOAT' },
     fWedStart: { public: true, type: 'TIME' },
     fWedEnd: { public: true, type: 'FLOAT' },
     fThuStart: { public: true, type: 'TIME' },
     fThuEnd: { public: true, type: 'FLOAT' },
     fFriStart: { public: true, type: 'TIME' },
     fFriEnd: { public: true, type: 'FLOAT' },
     fSatStart: { public: true, type: 'TIME' },
     fSatEnd: { public: true, type: 'FLOAT' },
     fSunStart: { public: true, type: 'TIME' },
     fSunEnd: { public: true, type: 'FLOAT' },
     fResMgrColNr: { public: true, type: 'INTEGER' },
     fInventoryNr: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex69: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }