module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fCustCode: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fAddr1: { public: true, type: 'TEXT' },
     fAddr2: { public: true, type: 'TEXT' },
     fOurContact: { public: true, type: 'TEXT' },
     fClientContact: { public: true, type: 'TEXT' },
     fMakeContact: { public: true, type: 'TEXT' },
     fValidTo: { public: true, type: 'DATE' },
     fPeriodCost: { public: true, type: 'FLOAT' },
     fCustPrice: { public: true, type: 'FLOAT' },
     fOurCost: { public: true, type: 'FLOAT' },
     fCONr: { public: true, type: 'INTEGER' },
     fCOChildNr: { public: true, type: 'INTEGER' },
     fText0: { public: true, type: 'TEXT' },
     fText1: { public: true, type: 'TEXT' },
     fText2: { public: true, type: 'TEXT' },
     fText3: { public: true, type: 'TEXT' },
     fText4: { public: true, type: 'TEXT' },
     fText5: { public: true, type: 'TEXT' },
     fText6: { public: true, type: 'TEXT' },
     fText7: { public: true, type: 'TEXT' },
     fText8: { public: true, type: 'TEXT' },
     fText9: { public: true, type: 'TEXT' },
     fFunderCode: { public: true, type: 'TEXT' },
     fFunderName: { public: true, type: 'TEXT' },
     fCQDate: { public: true, type: 'DATE' },
     fSalesMan: { public: true, type: 'TEXT' },
     fReplyTo: { public: true, type: 'INTEGER' },
     fVECode: { public: true, type: 'TEXT' },
     fVEName: { public: true, type: 'TEXT' },
     fVEContact: { public: true, type: 'TEXT' },
     fVersion: { public: true, type: 'INTEGER' },
     fReferingTo: { public: true, type: 'TEXT' },
     fPerType: { public: true, type: 'INTEGER' },
     fPerLength: { public: true, type: 'INTEGER' },
     fInvTimes: { public: true, type: 'INTEGER' },
     fNewINPrice: { public: true, type: 'FLOAT' },
     fOldINPrice: { public: true, type: 'FLOAT' },
     fRedemtion: { public: true, type: 'FLOAT' },
     fQBond: { public: true, type: 'DATE' },
     fPurOpt: { public: true, type: 'TEXT' },
     fSWAPOpt: { public: true, type: 'TEXT' },
     fContractClass: { public: true, type: 'TEXT' },
     CQVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fSpec: { public: true, type: 'TEXT' },
           fPrice: { public: true, type: 'FLOAT' },
           fType: { public: true, type: 'TEXT' },
           fPurPrice: { public: true, type: 'FLOAT' },
           fPurOption: { public: true, type: 'FLOAT' },
           fExtRate: { public: true, type: 'FLOAT' },
           fBiVECode: { public: true, type: 'TEXT' },
           fPeriodSum: { public: true, type: 'FLOAT' } } },
     fInvAddr3: { public: true, type: 'TEXT' },
     fInvAddr4: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex130: { fields: [ 'fSerNr', 'fVersion' ], indicesType: 'UNIQUE' } } }