module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'TEXT' },
     fProgType: { public: true, type: 'INTEGER' },
     fCreateDate: { public: true, type: 'DATE' },
     fRegDate: { public: true, type: 'DATE' },
     fDealer: { public: true, type: 'TEXT' },
     fCustCode: { public: true, type: 'TEXT' },
     fCOCUServiceNr: { public: true, type: 'INTEGER' },
     fPrePaid: { public: true, type: 'INTEGER' },
     fInclMaint: { public: true, type: 'INTEGER' },
     fMainItem: { public: true, type: 'TEXT' },
     fMaintRequired: { public: true, type: 'INTEGER' },
     InternalSerialNrVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fInit: { public: true, type: 'TEXT' },
           fMaint: { public: true, type: 'TEXT' },
           fMonths: { public: true, type: 'INTEGER' },
           fFreeMaintDays: { public: true, type: 'INTEGER' },
           fComment: { public: true, type: 'TEXT' } } },
     fProductCode: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex567: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }