module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fOrderPrinting: { public: true, type: 'INTEGER' },
     fShipPrinting: { public: true, type: 'INTEGER' },
     fInvoicePrinting: { public: true, type: 'INTEGER' },
     fTransactionPrinting: { public: true, type: 'INTEGER' },
     fInvoiceGen: { public: true, type: 'INTEGER' },
     fOr2Printing: { public: true, type: 'INTEGER' },
     fFreightPrinting: { public: true, type: 'INTEGER' },
     fEDIInvoice: { public: true, type: 'INTEGER' },
     fCOInvoicePrinting: { public: true, type: 'INTEGER' },
     fCashInvoicePrinting: { public: true, type: 'INTEGER' },
     fPUPalletLabelPrinting: { public: true, type: 'INTEGER' },
     fProdPalletLabelPrinting: { public: true, type: 'INTEGER' },
     fBarTabPrinting: { public: true, type: 'INTEGER' } } }