module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fCustCode: { public: true, type: 'TEXT' },
     fCustName: { public: true, type: 'TEXT' },
     fInvAddr1: { public: true, type: 'TEXT' },
     fInvAddr2: { public: true, type: 'TEXT' },
     fInvAddr3: { public: true, type: 'TEXT' },
     fInvAddr4: { public: true, type: 'TEXT' },
     fInvAddr5: { public: true, type: 'TEXT' },
     fOurContact: { public: true, type: 'TEXT' },
     fExportFlag: { public: true, type: 'INTEGER' },
     fPayDeal: { public: true, type: 'TEXT' },
     fCustCat: { public: true, type: 'TEXT' },
     fInvType: { public: true, type: 'INTEGER' },
     fPriceList: { public: true, type: 'TEXT' },
     fInclVAT: { public: true, type: 'INTEGER' },
     fInvComment: { public: true, type: 'TEXT' },
     fSalesMan: { public: true, type: 'TEXT' },
     fDealer: { public: true, type: 'TEXT' },
     fDealerName: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fLangCode: { public: true, type: 'TEXT' },
     fVATNr: { public: true, type: 'TEXT' },
     fCustVATCode: { public: true, type: 'TEXT' },
     fShipDeal: { public: true, type: 'TEXT' },
     fShipMode: { public: true, type: 'TEXT' },
     fDelAddr0: { public: true, type: 'TEXT' },
     fDelAddr1: { public: true, type: 'TEXT' },
     fDelAddr2: { public: true, type: 'TEXT' },
     fDelAddr3: { public: true, type: 'TEXT' },
     fDelAddr4: { public: true, type: 'TEXT' },
     fDelAddr5: { public: true, type: 'TEXT' },
     fXDelAddrCode: { public: true, type: 'TEXT' },
     fSite: { public: true, type: 'TEXT' },
     fRebCode: { public: true, type: 'TEXT' },
     fInvoiceToCode: { public: true, type: 'TEXT' },
     fSorting: { public: true, type: 'TEXT' },
     fEMail: { public: true, type: 'TEXT' },
     fPhone: { public: true, type: 'TEXT' },
     fFax: { public: true, type: 'TEXT' },
     fLocation: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fClientContact: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fFrPrice: { public: true, type: 'FLOAT' },
     fTAXSum: { public: true, type: 'FLOAT' },
     fSum0: { public: true, type: 'FLOAT' },
     fSum1: { public: true, type: 'FLOAT' },
     fSum2: { public: true, type: 'FLOAT' },
     fSum3: { public: true, type: 'FLOAT' },
     fSum4: { public: true, type: 'FLOAT' },
     fBaseSum4: { public: true, type: 'FLOAT' },
     EasyRentVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fSerialNr: { public: true, type: 'TEXT' },
           fArtCode: { public: true, type: 'TEXT' },
           fOutQty: { public: true, type: 'FLOAT' },
           fInQty: { public: true, type: 'FLOAT' },
           fSpec: { public: true, type: 'TEXT' },
           fGroup: { public: true, type: 'TEXT' },
           fInvItem: { public: true, type: 'TEXT' },
           fPrice: { public: true, type: 'FLOAT' },
           fVRebate: { public: true, type: 'FLOAT' },
           fSum: { public: true, type: 'FLOAT' },
           fStartDate: { public: true, type: 'DATE' },
           fEndDate: { public: true, type: 'DATE' },
           fInvDate: { public: true, type: 'DATE' },
           fOutLocation: { public: true, type: 'TEXT' },
           fInLocation: { public: true, type: 'TEXT' },
           fVATCode: { public: true, type: 'TEXT' },
           fDispNr: { public: true, type: 'INTEGER' },
           fOffhireNr: { public: true, type: 'INTEGER' },
           fNSSCType: { public: true, type: 'TEXT' },
           fF1Start: { public: true, type: 'DATE' },
           fF1End: { public: true, type: 'DATE' },
           fF2Start: { public: true, type: 'DATE' },
           fF2End: { public: true, type: 'DATE' },
           fF3Start: { public: true, type: 'DATE' },
           fF3End: { public: true, type: 'DATE' },
           fR1Start: { public: true, type: 'DATE' },
           fR1End: { public: true, type: 'DATE' },
           fR2Start: { public: true, type: 'DATE' },
           fR2End: { public: true, type: 'DATE' },
           fR3Start: { public: true, type: 'DATE' },
           fSite: { public: true, type: 'TEXT' } } },
     fNSSRec: { public: true, type: 'TEXT' },
     fLastDispNr: { public: true, type: 'INTEGER' },
     fLastOffhireNr: { public: true, type: 'INTEGER' },
     fNSSCType: { public: true, type: 'TEXT' },
     fNoTAXonVAT: { public: true, type: 'INTEGER' },
     fTotalwoTAX: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex507: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }