module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fUserCode: { public: true, type: 'TEXT' },
     fUserName: { public: true, type: 'TEXT' },
     fLocations: { public: true, type: 'TEXT' },
     fSec1Enabled: { public: true, type: 'INTEGER' },
     fSec1RoomDetails: { public: true, type: 'INTEGER' },
     fSec2Enabled: { public: true, type: 'INTEGER' },
     fSec2PeriodType: { public: true, type: 'INTEGER' },
     fSec2ObjType: { public: true, type: 'TEXT' },
     fSec2Obj: { public: true, type: 'TEXT' },
     fSec2Account: { public: true, type: 'TEXT' },
     fSec3Enabled: { public: true, type: 'INTEGER' },
     fSec3ShowAgents: { public: true, type: 'INTEGER' },
     fSec3ShowGuests: { public: true, type: 'INTEGER' },
     fSec4Enabled: { public: true, type: 'INTEGER' },
     fSec4Detailed: { public: true, type: 'INTEGER' },
     fSec4Locations: { public: true, type: 'TEXT' },
     fSec5Enabled: { public: true, type: 'INTEGER' },
     fSec5Detailed: { public: true, type: 'INTEGER' },
     fSec5Machines: { public: true, type: 'TEXT' },
     fSec6Enabled: { public: true, type: 'INTEGER' },
     fSec6Detailed: { public: true, type: 'INTEGER' },
     fSec7Enabled: { public: true, type: 'INTEGER' },
     fSec7DoSalesGroup: { public: true, type: 'INTEGER' },
     fSec7SalesGroups: { public: true, type: 'TEXT' },
     fSec7DoLocations: { public: true, type: 'INTEGER' },
     fSec7Locations: { public: true, type: 'TEXT' },
     fSec7DoResStatus: { public: true, type: 'INTEGER' } },
  indexes: { UserCodeIndex713: { fields: [ 'fUserCode' ], indicesType: 'UNIQUE' } } }