module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fPOClass: { public: true, type: 'TEXT' },
     fTender: { public: true, type: 'TEXT' },
     fVECode: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fExprIntPl: { public: true, type: 'DATE' },
     fExprIntAct: { public: true, type: 'DATE' },
     fPreQualSentPl: { public: true, type: 'DATE' },
     fPreQualSentAct: { public: true, type: 'DATE' },
     fPreQualNoObjPl: { public: true, type: 'DATE' },
     fPreQualNoObjAct: { public: true, type: 'DATE' },
     fBidDocSentPl: { public: true, type: 'DATE' },
     fBidDocSentAct: { public: true, type: 'DATE' },
     fBidDocNoObjPl: { public: true, type: 'DATE' },
     fBidDocNoObjAct: { public: true, type: 'DATE' },
     fBidPackAvPl: { public: true, type: 'DATE' },
     fBidPackAvAct: { public: true, type: 'DATE' },
     fBidOpenPl: { public: true, type: 'DATE' },
     fBidOpenAct: { public: true, type: 'DATE' },
     fContrNoObjPl: { public: true, type: 'DATE' },
     fContrNoObjAct: { public: true, type: 'DATE' },
     fContrSignPl: { public: true, type: 'DATE' },
     fContrSignAct: { public: true, type: 'DATE' },
     fContrEndAct: { public: true, type: 'DATE' },
     fContrEndPl: { public: true, type: 'DATE' },
     fClosed: { public: true, type: 'INTEGER' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fSum: { public: true, type: 'FLOAT' },
     fPerson: { public: true, type: 'TEXT' },
     fObject: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex264: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }