module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fRegister: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fSubject: { public: true, type: 'TEXT' },
     fStdTxt: { public: true, type: 'TEXT' },
     fAcceptanceActType: { public: true, type: 'TEXT' },
     fRejectedActType: { public: true, type: 'TEXT' },
     fNotNeededActType: { public: true, type: 'TEXT' },
     fAcceptedActType: { public: true, type: 'TEXT' },
     AcceptanceRulesVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fLimit: { public: true, type: 'FLOAT' },
           fAcceptanceType: { public: true, type: 'INTEGER' },
           fAcceptanceBy: { public: true, type: 'TEXT' },
           fActionType: { public: true, type: 'INTEGER' },
           fActionResult: { public: true, type: 'INTEGER' },
           fSpec: { public: true, type: 'TEXT' },
           fNextLevel: { public: true, type: 'INTEGER' },
           fApproverSelection: { public: true, type: 'INTEGER' },
           fFYIPersons: { public: true, type: 'TEXT' },
           fFYIActionResult: { public: true, type: 'INTEGER' } } },
     fType: { public: true, type: 'INTEGER' },
     fCustCode: { public: true, type: 'TEXT' },
     fCancelledActType: { public: true, type: 'TEXT' },
     fOKApproved: { public: true, type: 'INTEGER' },
     fEditRejected: { public: true, type: 'INTEGER' },
     fCancelApprovalRequest: { public: true, type: 'INTEGER' },
     fAutomaticApprovalforApprover: { public: true, type: 'INTEGER' },
     fFYIActType: { public: true, type: 'TEXT' },
     fFYISubject: { public: true, type: 'TEXT' },
     fForwardedActType: { public: true, type: 'TEXT' },
     fAbsentActType: { public: true, type: 'TEXT' },
     fAbsentSubject: { public: true, type: 'TEXT' },
     fDeclinedActType: { public: true, type: 'TEXT' } },
  indexes: { RegisterIndex685: { fields: [ 'fRegister', 'fCustCode' ], indicesType: 'UNIQUE' } } }