module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     ResAvVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math2',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fResType: { public: true, type: 'TEXT' },
           fQtyWanted: { public: true, type: 'FLOAT' },
           fQtyAvailable: { public: true, type: 'FLOAT' },
           fPubPriceList: { public: true, type: 'TEXT' },
           fUsage: { public: true, type: 'TEXT' },
           fAgentPrice: { public: true, type: 'FLOAT' },
           fAgentSum: { public: true, type: 'FLOAT' },
           fPersons: { public: true, type: 'INTEGER' },
           fGuestCode: { public: true, type: 'TEXT' },
           fXQtyConv: { public: true, type: 'TEXT' },
           fArtCode: { public: true, type: 'TEXT' },
           fPubPrice: { public: true, type: 'FLOAT' },
           fPubSum: { public: true, type: 'FLOAT' },
           fCalcType: { public: true, type: 'INTEGER' },
           fComment: { public: true, type: 'TEXT' },
           fTransDate: { public: true, type: 'DATE' },
           fEndDate: { public: true, type: 'DATE' },
           fStartTime: { public: true, type: 'TIME' },
           fEndTime: { public: true, type: 'TIME' },
           fAgentVat: { public: true, type: 'FLOAT' },
           fPubVat: { public: true, type: 'FLOAT' },
           fNrOfDays: { public: true, type: 'INTEGER' },
           fClassification: { public: true, type: 'TEXT' },
           fChildren: { public: true, type: 'INTEGER' },
           fRefStr: { public: true, type: 'TEXT' },
           fBookOrigin: { public: true, type: 'TEXT' },
           fNoOfGuests: { public: true, type: 'INTEGER' },
           fResLoc: { public: true, type: 'TEXT' },
           fVisitPurpose: { public: true, type: 'TEXT' },
           fResCode: { public: true, type: 'TEXT' } } },
     fComment: { public: true, type: 'TEXT' },
     fSourceCode: { public: true, type: 'TEXT' },
     fSourceName: { public: true, type: 'TEXT' },
     fAgentPriceList: { public: true, type: 'TEXT' },
     fAgentSum4: { public: true, type: 'FLOAT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fClosed: { public: true, type: 'INTEGER' },
     fTotPersons: { public: true, type: 'INTEGER' },
     fPubSum4: { public: true, type: 'FLOAT' },
     fMatherJobNr: { public: true, type: 'INTEGER' },
     fLangCode: { public: true, type: 'TEXT' },
     fCUCode: { public: true, type: 'TEXT' },
     fCUName: { public: true, type: 'TEXT' },
     fNrOfDays: { public: true, type: 'INTEGER' },
     fXLangCode: { public: true, type: 'TEXT' },
     fIncludePackage: { public: true, type: 'INTEGER' },
     fPrelFlag: { public: true, type: 'INTEGER' },
     fStartTime: { public: true, type: 'TIME' },
     fEndTime: { public: true, type: 'TIME' },
     fMath: { public: true, type: 'TEXT' },
     fLTxtCode: { public: true, type: 'TEXT' },
     fGroupWillNotPay: { public: true, type: 'INTEGER' },
     fCustContact: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fRefStr: { public: true, type: 'TEXT' },
     fBookOrigin: { public: true, type: 'TEXT' },
     fResLoc: { public: true, type: 'TEXT' },
     fVisitPurpose: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fTourOperator: { public: true, type: 'TEXT' },
     fTourOperatorName: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex227: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }