module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fInstalmentType: { public: true, type: 'INTEGER' },
     fInstalmentMonths: { public: true, type: 'INTEGER' },
     fPayDeal: { public: true, type: 'TEXT' },
     fDepositSum: { public: true, type: 'FLOAT' },
     fDepositPrc: { public: true, type: 'FLOAT' },
     fLateRateOption: { public: true, type: 'INTEGER' },
     fLateFeeDays: { public: true, type: 'INTEGER' },
     fRateType: { public: true, type: 'INTEGER' },
     fInstalment: { public: true, type: 'TEXT' },
     CredManTypeVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fChargeType: { public: true, type: 'INTEGER' },
           fQuant: { public: true, type: 'FLOAT' },
           fPrice: { public: true, type: 'FLOAT' },
           fSum: { public: true, type: 'FLOAT' },
           fVRebate: { public: true, type: 'FLOAT' },
           fPriceFactor: { public: true, type: 'FLOAT' } } },
     fIntRate: { public: true, type: 'FLOAT' },
     fChargeMethod: { public: true, type: 'INTEGER' },
     fFreeDays: { public: true, type: 'INTEGER' },
     fSettleLimit: { public: true, type: 'INTEGER' } },
  indexes: { CodeIndex624: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }