module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fInvoiceBy: { public: true, type: 'INTEGER' },
     fDefArtCode: { public: true, type: 'TEXT' },
     fChargeMethod: { public: true, type: 'INTEGER' },
     fLastJobNr: { public: true, type: 'INTEGER' },
     fLastDaughterJobNr: { public: true, type: 'INTEGER' },
     fTimeToClean: { public: true, type: 'TIME' },
     fTimeToCleanChOut: { public: true, type: 'TIME' },
     fObjects: { public: true, type: 'TEXT' },
     fOverbookPrc: { public: true, type: 'FLOAT' },
     fHoursBeforef: { public: true, type: 'INTEGER' },
     fNoHoursBefore: { public: true, type: 'INTEGER' },
     fColourBefore: { public: true, type: 'INTEGER' },
     fHoursAfterf: { public: true, type: 'INTEGER' },
     fNoHoursAfter: { public: true, type: 'INTEGER' },
     fColourAfter: { public: true, type: 'INTEGER' },
     fMaxPersons: { public: true, type: 'INTEGER' },
     fResLoc: { public: true, type: 'TEXT' },
     fMaxChildren: { public: true, type: 'INTEGER' },
     fMaxPax: { public: true, type: 'INTEGER' },
     fSort: { public: true, type: 'INTEGER' } },
  indexes: { CodeIndex219: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }