module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fTransTime: { public: true, type: 'TIME' },
     fKeepInDB: { public: true, type: 'INTEGER' },
     fMath: { public: true, type: 'TEXT' },
     fLanguages: { public: true, type: 'TEXT' },
     fClassification: { public: true, type: 'TEXT' },
     fType1: { public: true, type: 'INTEGER' },
     fType2: { public: true, type: 'INTEGER' },
     fType3: { public: true, type: 'INTEGER' },
     fType4: { public: true, type: 'INTEGER' },
     fVersion: { public: true, type: 'FLOAT' },
     fRegion: { public: true, type: 'TEXT' },
     fType5: { public: true, type: 'INTEGER' },
     fType6: { public: true, type: 'INTEGER' },
     fType7: { public: true, type: 'INTEGER' },
     fType8: { public: true, type: 'INTEGER' },
     fType9: { public: true, type: 'INTEGER' },
     fType10: { public: true, type: 'INTEGER' },
     fType11: { public: true, type: 'INTEGER' },
     fType12: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex578: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }