module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fServerCode: { public: true, type: 'TEXT' },
     fSerNr: { public: true, type: 'INTEGER' },
     fCustCode: { public: true, type: 'TEXT' },
     fService: { public: true, type: 'TEXT' },
     fQty: { public: true, type: 'FLOAT' },
     fTransDate: { public: true, type: 'DATE' },
     fTransTime: { public: true, type: 'TIME' },
     fStatus: { public: true, type: 'INTEGER' },
     fUserCode: { public: true, type: 'TEXT' },
     fRegInCountry: { public: true, type: 'INTEGER' },
     fCommisPrc: { public: true, type: 'FLOAT' },
     fCommisSum: { public: true, type: 'FLOAT' },
     fPartner: { public: true, type: 'TEXT' },
     fCompNr: { public: true, type: 'INTEGER' },
     fIVNr: { public: true, type: 'INTEGER' },
     fUseAltItem: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex472: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }