module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     ChqDepVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fChqNr: { public: true, type: 'INTEGER' },
           fAmount: { public: true, type: 'FLOAT' } } },
     fComment: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fSum: { public: true, type: 'FLOAT' },
     fCash: { public: true, type: 'FLOAT' },
     fDepAccNr: { public: true, type: 'TEXT' },
     fTempAccNr: { public: true, type: 'TEXT' },
     fPayMode: { public: true, type: 'TEXT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRate1: { public: true, type: 'FLOAT' },
     fToRate2: { public: true, type: 'FLOAT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fPayModeCash: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fType: { public: true, type: 'INTEGER' },
     fCommision: { public: true, type: 'FLOAT' },
     fReference: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex308: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }