module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fInclVAT: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fTransTime: { public: true, type: 'TIME' },
     fPayDeal: { public: true, type: 'TEXT' },
     fSum0: { public: true, type: 'FLOAT' },
     fSum1: { public: true, type: 'FLOAT' },
     fSum2: { public: true, type: 'FLOAT' },
     fSum3: { public: true, type: 'FLOAT' },
     fSum4: { public: true, type: 'FLOAT' },
     fVATNr: { public: true, type: 'TEXT' },
     fLocation: { public: true, type: 'TEXT' },
     fCashValue: { public: true, type: 'FLOAT' },
     fCreditCard: { public: true, type: 'FLOAT' },
     fRecValue: { public: true, type: 'FLOAT' },
     fSynced: { public: true, type: 'INTEGER' },
     fTotWeight: { public: true, type: 'FLOAT' },
     fTotVolume: { public: true, type: 'FLOAT' },
     fLocalMachineCode: { public: true, type: 'TEXT' },
     POSSalesVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fSpec: { public: true, type: 'TEXT' },
           fPrice: { public: true, type: 'FLOAT' },
           fSum: { public: true, type: 'FLOAT' },
           fVRebate: { public: true, type: 'FLOAT' },
           fSalesAcc: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fBasePrice: { public: true, type: 'FLOAT' },
           fVATCode: { public: true, type: 'TEXT' },
           fPosCode: { public: true, type: 'TEXT' },
           fXVATCode: { public: true, type: 'TEXT' },
           fNotUpdStockFlag: { public: true, type: 'INTEGER' } } },
     fRetValue: { public: true, type: 'FLOAT' },
     fDrawerCode: { public: true, type: 'TEXT' },
     fInvNo: { public: true, type: 'INTEGER' },
     fSyncTransDate: { public: true, type: 'DATE' },
     fTotQty: { public: true, type: 'FLOAT' },
     fType: { public: true, type: 'INTEGER' },
     fNoTAXonVAT: { public: true, type: 'INTEGER' },
     fTotalwoTAX: { public: true, type: 'INTEGER' } },
  indexes: 
   { LocationIndex534: 
      { fields: 
         [ 'fLocation',
           'fLocalMachineCode',
           'fTransDate',
           'fTransTime',
           'fType' ],
        indicesType: 'UNIQUE' } } }