module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fRegDate: { public: true, type: 'DATE' },
     fTransDate: { public: true, type: 'DATE' },
     fComment: { public: true, type: 'TEXT' },
     fVECode: { public: true, type: 'TEXT' },
     fVEName: { public: true, type: 'TEXT' },
     fPONr: { public: true, type: 'INTEGER' },
     fLocation: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fInclVAT: { public: true, type: 'INTEGER' },
     fSumCostPrice: { public: true, type: 'FLOAT' },
     fSumQuant: { public: true, type: 'FLOAT' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fLocOKNr: { public: true, type: 'FLOAT' },
     fPUNr: { public: true, type: 'INTEGER' },
     fObjects: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fExportFlag: { public: true, type: 'INTEGER' },
     fType: { public: true, type: 'INTEGER' },
     fUpdStockFlag: { public: true, type: 'INTEGER' },
     RetPUVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fSpec: { public: true, type: 'TEXT' },
           fFIFO: { public: true, type: 'FLOAT' },
           fFIFORowVal: { public: true, type: 'FLOAT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fVEItemCode: { public: true, type: 'TEXT' },
           fBestBefore: { public: true, type: 'DATE' },
           fCoefficient: { public: true, type: 'FLOAT' },
           fObjects: { public: true, type: 'TEXT' },
           fCostAcc: { public: true, type: 'TEXT' },
           fCredAcc: { public: true, type: 'TEXT' },
           fPosCode: { public: true, type: 'TEXT' },
           fUnitXval: { public: true, type: 'FLOAT' },
           fUnitYval: { public: true, type: 'FLOAT' },
           fUnitZval: { public: true, type: 'FLOAT' },
           fVATCode: { public: true, type: 'TEXT' },
           fOrdRow: { public: true, type: 'INTEGER' },
           fVarianceAmount: { public: true, type: 'FLOAT' },
           fPUNr: { public: true, type: 'INTEGER' },
           fPURow: { public: true, type: 'INTEGER' },
           fLocation: { public: true, type: 'TEXT' },
           fPUCostPrice: { public: true, type: 'FLOAT' },
           fPONr: { public: true, type: 'INTEGER' },
           fShipCost: { public: true, type: 'FLOAT' },
           fCustomsCost: { public: true, type: 'FLOAT' },
           fRowCost1: { public: true, type: 'FLOAT' },
           fRowCost2: { public: true, type: 'FLOAT' },
           fRowCost3: { public: true, type: 'FLOAT' },
           fRowCost4: { public: true, type: 'FLOAT' },
           fRowCost5: { public: true, type: 'FLOAT' } } },
     fFreightCode: { public: true, type: 'TEXT' },
     fFreightCompanyRegNr: { public: true, type: 'TEXT' },
     fFreightCompany: { public: true, type: 'TEXT' },
     fTruckInfo: { public: true, type: 'TEXT' },
     fDriver: { public: true, type: 'TEXT' },
     fCMRText: { public: true, type: 'TEXT' },
     fDelAddrCode: { public: true, type: 'TEXT' },
     fDelAddr0: { public: true, type: 'TEXT' },
     fDelAddr1: { public: true, type: 'TEXT' },
     fDelAddr2: { public: true, type: 'TEXT' },
     fDelAddr3: { public: true, type: 'TEXT' },
     fDelAddr4: { public: true, type: 'TEXT' },
     fReason: { public: true, type: 'TEXT' },
     fInvalidDate: { public: true, type: 'DATE' },
     fSorting: { public: true, type: 'TEXT' },
     fTerminalID: { public: true, type: 'TEXT' },
     fBranchID: { public: true, type: 'TEXT' },
     fOfficialSerNr: { public: true, type: 'TEXT' },
     fHash: { public: true, type: 'TEXT' },
     fHashKeyVersion: { public: true, type: 'INTEGER' },
     fRegTime: { public: true, type: 'TIME' },
     fLocalMachineCode: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fShipCost: { public: true, type: 'FLOAT' },
     fCustomsCost: { public: true, type: 'FLOAT' },
     fExtraCost: { public: true, type: 'FLOAT' },
     fCost1: { public: true, type: 'FLOAT' },
     fCost2: { public: true, type: 'FLOAT' },
     fCost3: { public: true, type: 'FLOAT' },
     fCost4: { public: true, type: 'FLOAT' },
     fCost5: { public: true, type: 'FLOAT' },
     fShipCostRound: { public: true, type: 'FLOAT' },
     fCustomsCostRound: { public: true, type: 'FLOAT' },
     fCost1Round: { public: true, type: 'FLOAT' },
     fCost2Round: { public: true, type: 'FLOAT' },
     fCost3Round: { public: true, type: 'FLOAT' },
     fCost4Round: { public: true, type: 'FLOAT' },
     fCost5Round: { public: true, type: 'FLOAT' },
     fExtraCostsCalculation: { public: true, type: 'INTEGER' },
     fOKBy: { public: true, type: 'TEXT' },
     fPlanSendDate: { public: true, type: 'DATE' },
     fPlanSendTime: { public: true, type: 'TIME' },
     fPlanArrDate: { public: true, type: 'DATE' },
     fPlanArrTime: { public: true, type: 'TIME' },
     fTaxAdminServSeal: { public: true, type: 'TEXT' },
     fStatus: { public: true, type: 'INTEGER' },
     fOfficialSerNrSerie: { public: true, type: 'TEXT' },
     fOfficialSerNr2: { public: true, type: 'TEXT' },
     fOfficialSerNr2Serie: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fSalesGroup: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex258: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }