module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fPlanID: { public: true, type: 'INTEGER' },
     fMachineID: { public: true, type: 'TEXT' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fStartTime: { public: true, type: 'TIME' },
     fEndTime: { public: true, type: 'TIME' },
     fProdOpNr: { public: true, type: 'INTEGER' },
     fProdNr: { public: true, type: 'INTEGER' },
     fDur: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fFreezeFlag: { public: true, type: 'INTEGER' },
     fRouteCode: { public: true, type: 'TEXT' },
     fSetupTime: { public: true, type: 'INTEGER' },
     fMovedFlag: { public: true, type: 'INTEGER' },
     fQty: { public: true, type: 'FLOAT' } },
  indexes: { SerNrIndex789: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }