module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fLinkToStruct: { public: true, type: 'INTEGER' },
     fExtraArgs: { public: true, type: 'TEXT' },
     fTarget: { public: true, type: 'TEXT' },
     fNoSession: { public: true, type: 'INTEGER' },
     fParentMenu: { public: true, type: 'TEXT' },
     fGoToURL: { public: true, type: 'TEXT' },
     fLinkPict: { public: true, type: 'TEXT' },
     WebNGMenuVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fLangCode: { public: true, type: 'TEXT' },
           fText: { public: true, type: 'TEXT' } } },
     fWebElement: { public: true, type: 'TEXT' },
     fShowWhenLoggedIn: { public: true, type: 'INTEGER' },
     fShowWhenLoggedOut: { public: true, type: 'INTEGER' },
     fMenuClass: { public: true, type: 'TEXT' },
     fActMenuClass: { public: true, type: 'TEXT' } },
  indexes: { CodeIndex593: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }