module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fCompany: { public: true, type: 'TEXT' },
     fCompanyRegNr: { public: true, type: 'TEXT' },
     fTruckInfo: { public: true, type: 'TEXT' },
     fDriver: { public: true, type: 'TEXT' },
     fCMRText: { public: true, type: 'TEXT' },
     fWebService: { public: true, type: 'INTEGER' },
     fDelSignature: { public: true, type: 'INTEGER' },
     fWebServiceAccNr: { public: true, type: 'TEXT' },
     fWebServiceMeterNr: { public: true, type: 'TEXT' },
     fWebServiceKey: { public: true, type: 'TEXT' },
     fWebServicePasswd: { public: true, type: 'TEXT' },
     fVECode: { public: true, type: 'TEXT' },
     fMunicipalityCode: { public: true, type: 'TEXT' },
     fDistrictCode: { public: true, type: 'TEXT' },
     fWebServiceMode: { public: true, type: 'INTEGER' } },
  indexes: { CodeIndex444: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }