module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fDefCustCode: { public: true, type: 'TEXT' },
     fPOSNr: { public: true, type: 'INTEGER' },
     fCredAcc: { public: true, type: 'TEXT' },
     fWriteOffAcc: { public: true, type: 'TEXT' },
     fStartFromLastPOSBal: { public: true, type: 'INTEGER' },
     fPrintDetNLTrans: { public: true, type: 'INTEGER' },
     fPrinter: { public: true, type: 'INTEGER' },
     fTipPMCode: { public: true, type: 'TEXT' },
     fInclTipInCashup: { public: true, type: 'INTEGER' },
     fInclOpenInvCashup: { public: true, type: 'INTEGER' },
     fRequireOpenSession: { public: true, type: 'INTEGER' },
     fDefInvoiceField: { public: true, type: 'INTEGER' },
     fUpdStockMaint: { public: true, type: 'INTEGER' },
     fUpdStockMaintTime: { public: true, type: 'TIME' },
     fCashSalesToFiscalControlUnit: { public: true, type: 'INTEGER' },
     fMultipleSessionsPerLocalMachine: { public: true, type: 'INTEGER' },
     fDiscountItem: { public: true, type: 'TEXT' },
     fNoChangesPOSOnLiveSyncClient: { public: true, type: 'INTEGER' },
     fCashupMaint: { public: true, type: 'INTEGER' },
     fCashupMaintInterval: { public: true, type: 'TIME' },
     fRestAccBookedDiscount: { public: true, type: 'INTEGER' },
     fRestAccDiscountAcc: { public: true, type: 'TEXT' },
     fRestAccServiceChargeItem: { public: true, type: 'TEXT' },
     fRestAccARAcc: { public: true, type: 'TEXT' },
     fRequireReturnReason: { public: true, type: 'INTEGER' },
     fRequireReturnCustomer: { public: true, type: 'INTEGER' },
     fRestUpdStockMaint: { public: true, type: 'INTEGER' },
     fRestUpdStockMaintTime: { public: true, type: 'TIME' },
     fRestOKSD: { public: true, type: 'INTEGER' },
     fRestBasePriceInclVAT: { public: true, type: 'INTEGER' },
     fPOSOKSD: { public: true, type: 'INTEGER' },
     fItemPictureCashier: { public: true, type: 'INTEGER' },
     fItemPictureCustomer: { public: true, type: 'INTEGER' } } }