module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fNumber: { public: true, type: 'INTEGER' },
     fRegDate: { public: true, type: 'DATE' },
     fComment: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fSign: { public: true, type: 'TEXT' },
     fTotSum: { public: true, type: 'FLOAT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fAccName1: { public: true, type: 'TEXT' },
     fAccBal1: { public: true, type: 'FLOAT' },
     fAccName2: { public: true, type: 'TEXT' },
     fAccBal2: { public: true, type: 'FLOAT' },
     fAccName3: { public: true, type: 'TEXT' },
     fAccBal3: { public: true, type: 'FLOAT' },
     fAccName4: { public: true, type: 'TEXT' },
     fAccBal4: { public: true, type: 'FLOAT' },
     DanTRVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fOvst: { public: true, type: 'INTEGER' },
           fAccNumber1: { public: true, type: 'TEXT' },
           fPayMode: { public: true, type: 'TEXT' },
           fAccNumber2: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fDebVal: { public: true, type: 'FLOAT' },
           fCredVal: { public: true, type: 'FLOAT' },
           fVATCode: { public: true, type: 'TEXT' },
           fTransNr: { public: true, type: 'INTEGER' },
           fRefStr: { public: true, type: 'TEXT' },
           fText: { public: true, type: 'TEXT' },
           fCompCode: { public: true, type: 'TEXT' },
           fTyp: { public: true, type: 'INTEGER' },
           fRowTransDate: { public: true, type: 'DATE' },
           fInvoiceNr: { public: true, type: 'INTEGER' },
           fCurDebVal: { public: true, type: 'FLOAT' },
           fCurCredVal: { public: true, type: 'FLOAT' },
           fCurncy: { public: true, type: 'TEXT' },
           fFrRate: { public: true, type: 'FLOAT' },
           fToRateB1: { public: true, type: 'FLOAT' },
           fToRateB2: { public: true, type: 'FLOAT' },
           fBaseRate1: { public: true, type: 'FLOAT' },
           fBaseRate2: { public: true, type: 'FLOAT' },
           fDebVal2: { public: true, type: 'FLOAT' },
           fCredVal2: { public: true, type: 'FLOAT' } } } },
  indexes: { NumberIndex285: { fields: [ 'fNumber' ], indicesType: 'UNIQUE' } } }