module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fAddrName: { public: true, type: 'TEXT' },
     fAddrCode: { public: true, type: 'TEXT' },
     fMotherConf: { public: true, type: 'INTEGER' },
     fClass: { public: true, type: 'INTEGER' },
     fMaxMail: { public: true, type: 'INTEGER' },
     fMaxReadDays: { public: true, type: 'INTEGER' },
     fMaxUnreadDays: { public: true, type: 'INTEGER' },
     ConfVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fGroup: { public: true, type: 'TEXT' } } },
     fComment: { public: true, type: 'TEXT' },
     fHtmForm: { public: true, type: 'TEXT' },
     fClosed: { public: true, type: 'INTEGER' },
     fUserType: { public: true, type: 'INTEGER' },
     fIdentifier: { public: true, type: 'TEXT' },
     fSortorder: { public: true, type: 'TEXT' },
     fVersion: { public: true, type: 'INTEGER' },
     fExtEmailAddrs: { public: true, type: 'TEXT' },
     fMaxUpdateDays: { public: true, type: 'INTEGER' },
     fDefaultHtmlFlag: { public: true, type: 'INTEGER' },
     fDefaultTemplate: { public: true, type: 'TEXT' },
     fForceHtmlFlag: { public: true, type: 'INTEGER' },
     fForceDefaultTemplate: { public: true, type: 'INTEGER' },
     fRequireTemplate: { public: true, type: 'INTEGER' },
     fReplyFromConference: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex194: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }