module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fCustCode: { public: true, type: 'TEXT' },
     fVATNr: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fAddr1: { public: true, type: 'TEXT' },
     fAddr2: { public: true, type: 'TEXT' },
     fAddr3: { public: true, type: 'TEXT' },
     fCustCat: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fSalesMan: { public: true, type: 'TEXT' },
     fSum4: { public: true, type: 'FLOAT' },
     fLangCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fPrntdf: { public: true, type: 'INTEGER' },
     fLocation: { public: true, type: 'TEXT' },
     fTransTime: { public: true, type: 'TIME' },
     fLocalMachineCode: { public: true, type: 'TEXT' },
     fInvAddr3: { public: true, type: 'TEXT' },
     fInvAddr4: { public: true, type: 'TEXT' },
     fTerminalID: { public: true, type: 'TEXT' },
     fBranchID: { public: true, type: 'TEXT' },
     fDepCode: { public: true, type: 'TEXT' },
     fDrawerCode: { public: true, type: 'TEXT' },
     fIVCashNr: { public: true, type: 'INTEGER' },
     fSupervisor: { public: true, type: 'TEXT' },
     fBagger: { public: true, type: 'TEXT' },
     GiftReceiptVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fPrice: { public: true, type: 'FLOAT' },
           fSum: { public: true, type: 'FLOAT' },
           fVRebate: { public: true, type: 'FLOAT' },
           fSpec: { public: true, type: 'TEXT' },
           fSerialNr: { public: true, type: 'TEXT' } } } },
  indexes: { SerNrIndex734: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }