module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fBankAcc: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fRegDate: { public: true, type: 'DATE' },
     fTransDate: { public: true, type: 'DATE' },
     fPayMode: { public: true, type: 'TEXT' },
     fBankName: { public: true, type: 'TEXT' },
     fOrderedFlag: { public: true, type: 'INTEGER' },
     fSentFlag: { public: true, type: 'INTEGER' },
     fDoneFlag: { public: true, type: 'INTEGER' },
     fPayDate: { public: true, type: 'DATE' },
     fStatFlag: { public: true, type: 'INTEGER' },
     OPVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fOvst: { public: true, type: 'INTEGER' },
           fVISerNr: { public: true, type: 'INTEGER' },
           fBankAcc: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fVECode: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fVATVal: { public: true, type: 'FLOAT' },
           fVATCode: { public: true, type: 'TEXT' },
           fChequeNr: { public: true, type: 'INTEGER' },
           fPrepayNr: { public: true, type: 'INTEGER' },
           fPayMode: { public: true, type: 'TEXT' },
           fPInvOutstand: { public: true, type: 'FLOAT' },
           fPInvCurncy: { public: true, type: 'TEXT' },
           fPInvVal: { public: true, type: 'FLOAT' },
           fBankCurncy: { public: true, type: 'TEXT' },
           fBankVal: { public: true, type: 'FLOAT' },
           fRecCurncy: { public: true, type: 'TEXT' },
           fRecVal: { public: true, type: 'FLOAT' },
           fBankFeeVal: { public: true, type: 'FLOAT' },
           fRoundOff: { public: true, type: 'FLOAT' },
           fRoundOffAcc: { public: true, type: 'TEXT' },
           fSortCode: { public: true, type: 'TEXT' },
           fCoef: { public: true, type: 'FLOAT' },
           fBankFeePrc: { public: true, type: 'FLOAT' },
           fOrderNr: { public: true, type: 'INTEGER' },
           fB1BankVal: { public: true, type: 'FLOAT' },
           fB2BankVal: { public: true, type: 'FLOAT' },
           fToRateB1BankVal: { public: true, type: 'FLOAT' },
           fToRateB2BankVal: { public: true, type: 'FLOAT' },
           fBankRefStr: { public: true, type: 'TEXT' },
           fRkPayNumber: { public: true, type: 'TEXT' },
           fWHTax: { public: true, type: 'TEXT' },
           fWHTaxBase: { public: true, type: 'FLOAT' },
           fTAX1Sum: { public: true, type: 'FLOAT' },
           fAPAcc: { public: true, type: 'TEXT' },
           fInstNr: { public: true, type: 'INTEGER' },
           fFrRateBankVal: { public: true, type: 'FLOAT' },
           fBaseRate1BankVal: { public: true, type: 'FLOAT' },
           fBaseRate2BankVal: { public: true, type: 'FLOAT' },
           fWHTaxPrc: { public: true, type: 'FLOAT' },
           fPaymentCode: { public: true, type: 'TEXT' },
           fWHTaxAccumBase: { public: true, type: 'FLOAT' } } },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fPayNumber: { public: true, type: 'TEXT' },
     fRejectedFlag: { public: true, type: 'INTEGER' },
     fInvalid: { public: true, type: 'INTEGER' },
     fAPonTR: { public: true, type: 'INTEGER' },
     fPayCurCode: { public: true, type: 'TEXT' },
     fCurPayVal: { public: true, type: 'FLOAT' },
     fObjects: { public: true, type: 'TEXT' },
     fSortCode: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fPayperSupplier: { public: true, type: 'INTEGER' },
     fPayMethod: { public: true, type: 'INTEGER' },
     fBankfees: { public: true, type: 'INTEGER' },
     fForeignPayment: { public: true, type: 'INTEGER' },
     fAcceptanceStatus: { public: true, type: 'INTEGER' },
     fAcceptanceBy: { public: true, type: 'TEXT' },
     fAcceptanceFYI: { public: true, type: 'TEXT' },
     fOKBy: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex39: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }