module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fPerson: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fPRCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fPayVal: { public: true, type: 'FLOAT' },
     DAVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fDate: { public: true, type: 'DATE' },
           fTime: { public: true, type: 'TIME' },
           fCountry: { public: true, type: 'TEXT' },
           fBreakfast: { public: true, type: 'INTEGER' },
           fLunch: { public: true, type: 'INTEGER' },
           fDinner: { public: true, type: 'INTEGER' },
           fCompensation: { public: true, type: 'FLOAT' },
           fBreakfastSum: { public: true, type: 'FLOAT' },
           fLunchSum: { public: true, type: 'FLOAT' },
           fDinnerSum: { public: true, type: 'FLOAT' },
           fDailySum: { public: true, type: 'FLOAT' },
           fBreakfastRate: { public: true, type: 'FLOAT' },
           fLunchRate: { public: true, type: 'FLOAT' },
           fDinnerRate: { public: true, type: 'FLOAT' },
           fPaidBy: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' } } },
     fRateType: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex797: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }