module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fActType: { public: true, type: 'TEXT' },
     fActResult: { public: true, type: 'TEXT' },
     fNextType: { public: true, type: 'TEXT' },
     fNextComment: { public: true, type: 'TEXT' },
     fNrOfDays: { public: true, type: 'INTEGER' },
     fPerson: { public: true, type: 'TEXT' },
     fNrOfHours: { public: true, type: 'INTEGER' },
     fNewResState: { public: true, type: 'TEXT' },
     fTodoFlag: { public: true, type: 'INTEGER' },
     fCopyRLink: { public: true, type: 'INTEGER' },
     fCreateVc: { public: true, type: 'INTEGER' },
     fRequireSerialNr: { public: true, type: 'INTEGER' },
     fAlarmType: { public: true, type: 'INTEGER' },
     fAlarmWhen: { public: true, type: 'INTEGER' },
     fAlarmUnits: { public: true, type: 'INTEGER' },
     fPrioLevel: { public: true, type: 'INTEGER' },
     fSymbNr: { public: true, type: 'INTEGER' },
     fSetPerson: { public: true, type: 'INTEGER' } },
  indexes: { ActTypeIndex114: { fields: [ 'fActType', 'fActResult' ], indicesType: 'UNIQUE' } } }