module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fUnitType: { public: true, type: 'INTEGER' },
     fXpos: { public: true, type: 'FLOAT' },
     fYpos: { public: true, type: 'FLOAT' },
     fUnitWidth: { public: true, type: 'FLOAT' },
     fUnitHeight: { public: true, type: 'FLOAT' },
     fUnitStyle: { public: true, type: 'TEXT' },
     fUnitText: { public: true, type: 'TEXT' },
     fJust: { public: true, type: 'INTEGER' },
     fLineHeight: { public: true, type: 'INTEGER' },
     fFieldSetNr: { public: true, type: 'INTEGER' },
     fClip: { public: true, type: 'INTEGER' },
     fEscSeq: { public: true, type: 'TEXT' },
     fExcludeFirst: { public: true, type: 'INTEGER' },
     fExcludeMiddle: { public: true, type: 'INTEGER' },
     fExcludeLast: { public: true, type: 'INTEGER' },
     fExcludeOnly: { public: true, type: 'INTEGER' },
     fWordWrap: { public: true, type: 'INTEGER' },
     fFormatNr: { public: true, type: 'INTEGER' },
     fPageSumType: { public: true, type: 'INTEGER' } },
  indexes: { MainKeyIndex136: { fields: [ 'fUnitType' ], indicesType: 'UNIQUE' } } }