module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fRegDate: { public: true, type: 'DATE' },
     fTransDate: { public: true, type: 'DATE' },
     fComment: { public: true, type: 'TEXT' },
     fVECode: { public: true, type: 'TEXT' },
     fVEName: { public: true, type: 'TEXT' },
     fPONr: { public: true, type: 'INTEGER' },
     fLocation: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fInclVAT: { public: true, type: 'INTEGER' },
     fSumCostPrice: { public: true, type: 'FLOAT' },
     fSumQuant: { public: true, type: 'FLOAT' },
     fShipCost: { public: true, type: 'FLOAT' },
     fCustomsCost: { public: true, type: 'FLOAT' },
     fExtraCost: { public: true, type: 'FLOAT' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fObjects: { public: true, type: 'TEXT' },
     fPUClass: { public: true, type: 'TEXT' },
     fPOCOSerNr: { public: true, type: 'INTEGER' },
     fCost1: { public: true, type: 'FLOAT' },
     fCost2: { public: true, type: 'FLOAT' },
     fCost3: { public: true, type: 'FLOAT' },
     fCost4: { public: true, type: 'FLOAT' },
     fCost5: { public: true, type: 'FLOAT' },
     fVATVal: { public: true, type: 'FLOAT' },
     fSubTotal: { public: true, type: 'FLOAT' },
     fPayVal: { public: true, type: 'FLOAT' },
     fVEVATCode: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fPUNr: { public: true, type: 'INTEGER' },
     LateCostVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fOvst: { public: true, type: 'INTEGER' },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fSpec: { public: true, type: 'TEXT' },
           fUPrice: { public: true, type: 'FLOAT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fOrdRow: { public: true, type: 'INTEGER' },
           fExtra: { public: true, type: 'FLOAT' },
           fCostPrice: { public: true, type: 'FLOAT' },
           fVEItemCode: { public: true, type: 'TEXT' },
           fVARList: { public: true, type: 'TEXT' },
           fShipCost: { public: true, type: 'FLOAT' },
           fCustomsCost: { public: true, type: 'FLOAT' },
           fBestBefore: { public: true, type: 'DATE' },
           fCoefficient: { public: true, type: 'FLOAT' },
           fBasePrice: { public: true, type: 'FLOAT' },
           fSum: { public: true, type: 'FLOAT' },
           fComment: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fCostAcc: { public: true, type: 'TEXT' },
           fCredAcc: { public: true, type: 'TEXT' },
           fCustomsNr: { public: true, type: 'TEXT' },
           fCountryOfOrg: { public: true, type: 'TEXT' },
           fPosCode: { public: true, type: 'TEXT' },
           fBatchStatus: { public: true, type: 'TEXT' },
           fUnitXval: { public: true, type: 'FLOAT' },
           fUnitYval: { public: true, type: 'FLOAT' },
           fUnitZval: { public: true, type: 'FLOAT' },
           fRowCost1: { public: true, type: 'FLOAT' },
           fRowCost2: { public: true, type: 'FLOAT' },
           fRowCost3: { public: true, type: 'FLOAT' },
           fRowCost4: { public: true, type: 'FLOAT' },
           fRowCost5: { public: true, type: 'FLOAT' },
           fVATCode: { public: true, type: 'TEXT' },
           fSign: { public: true, type: 'TEXT' },
           fUpdDate: { public: true, type: 'DATE' },
           fPURow: { public: true, type: 'INTEGER' },
           fUsedQuant: { public: true, type: 'FLOAT' } } } },
  indexes: { SerNrIndex370: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }