#!/bin/sh

LPFA=`ls *.pfa 2>/dev/null`

if [ -n "$LPFA" ]; then
  grep FontName *.pfa | tr -d // | tr ":" " " | awk '{system("echo "$1" "$3)}' > Fontmap
  echo "./Fontmap file generated"
else
  echo "No Postscript font files found"
fi
