module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fBank: { public: true, type: 'INTEGER' },
     fLastDate: { public: true, type: 'DATE' },
     fLastSerNr: { public: true, type: 'INTEGER' },
     fRowSerNr: { public: true, type: 'INTEGER' },
     fUser: { public: true, type: 'TEXT' },
     fPayType: { public: true, type: 'TEXT' },
     fPayHeader: { public: true, type: 'TEXT' },
     fContractNumer: { public: true, type: 'TEXT' },
     fReceiptBank: { public: true, type: 'INTEGER' },
     fClientNr: { public: true, type: 'TEXT' },
     fKIDMod: { public: true, type: 'INTEGER' },
     fLocCurncyCode: { public: true, type: 'TEXT' },
     fBankIP: { public: true, type: 'TEXT' },
     fBankPort: { public: true, type: 'INTEGER' },
     fBankUser: { public: true, type: 'TEXT' },
     fBankPass: { public: true, type: 'TEXT' },
     fBankEnqKey: { public: true, type: 'TEXT' },
     fBankLocalPort: { public: true, type: 'INTEGER' },
     fBankBranchCode: { public: true, type: 'TEXT' },
     fDirectDebitBank: { public: true, type: 'INTEGER' },
     fExportSuppInvNr: { public: true, type: 'INTEGER' } } }