module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fCouponNr: { public: true, type: 'TEXT' },
     fCreditCardNr: { public: true, type: 'TEXT' },
     fIVNr: { public: true, type: 'INTEGER' },
     fConsNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fCUCode: { public: true, type: 'TEXT' },
     fCUName: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fCardType: { public: true, type: 'TEXT' },
     fAmount: { public: true, type: 'FLOAT' },
     fStatus: { public: true, type: 'INTEGER' },
     fDirect: { public: true, type: 'INTEGER' },
     fDepDate: { public: true, type: 'DATE' },
     fInst: { public: true, type: 'INTEGER' },
     fAuthDate: { public: true, type: 'DATE' },
     fCashDate: { public: true, type: 'DATE' },
     fBatchNr: { public: true, type: 'INTEGER' },
     fAuthorizationCode: { public: true, type: 'TEXT' },
     fInstrNr: { public: true, type: 'INTEGER' },
     fMachineName: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fOriginType: { public: true, type: 'INTEGER' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fNLTransDate: { public: true, type: 'DATE' },
     fBatch: { public: true, type: 'TEXT' },
     fCCTransID: { public: true, type: 'TEXT' },
     fTimestamp: { public: true, type: 'TEXT' },
     fReverseCouponNr: { public: true, type: 'TEXT' },
     fReverseCCTransID: { public: true, type: 'TEXT' },
     fReverseTimestamp: { public: true, type: 'TEXT' },
     fFileName: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex290: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }