module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCompany: { public: true, type: 'TEXT' },
     fCompName: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fAdress0: { public: true, type: 'TEXT' },
     fAdress1: { public: true, type: 'TEXT' },
     fAdress2: { public: true, type: 'TEXT' },
     fPhone: { public: true, type: 'TEXT' },
     fFax: { public: true, type: 'TEXT' },
     fEmail: { public: true, type: 'TEXT' },
     fComment0: { public: true, type: 'TEXT' },
     fComment1: { public: true, type: 'TEXT' },
     fComment2: { public: true, type: 'TEXT' },
     fTitle: { public: true, type: 'TEXT' },
     fDepartment: { public: true, type: 'TEXT' },
     fJobDesc: { public: true, type: 'TEXT' },
     fClassification: { public: true, type: 'TEXT' },
     fMobile: { public: true, type: 'TEXT' },
     fAltPhone: { public: true, type: 'TEXT' },
     fBirthDate: { public: true, type: 'DATE' },
     fClosed: { public: true, type: 'INTEGER' },
     fAdress3: { public: true, type: 'TEXT' },
     fAdress4: { public: true, type: 'TEXT' },
     fSalutation: { public: true, type: 'TEXT' },
     fRegDate: { public: true, type: 'DATE' },
     fFirstName: { public: true, type: 'TEXT' },
     fMidName: { public: true, type: 'TEXT' },
     fSalutation1: { public: true, type: 'TEXT' },
     fSalutation2: { public: true, type: 'TEXT' },
     fSalutation3: { public: true, type: 'TEXT' },
     fNoLetterPosting: { public: true, type: 'INTEGER' },
     fNoMailPosting: { public: true, type: 'INTEGER' },
     fSkypeName: { public: true, type: 'TEXT' } },
  indexes: { MainKeyIndex138: { fields: [ 'fName', 'fCompany' ], indicesType: 'UNIQUE' } } }