module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     BatchTextVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fSpec: { public: true, type: 'TEXT' } } },
     fArtCode: { public: true, type: 'TEXT' },
     fSerialNr: { public: true, type: 'TEXT' },
     fBestBefore: { public: true, type: 'DATE' },
     fProductionDate: { public: true, type: 'DATE' },
     fUnitXval: { public: true, type: 'FLOAT' },
     fUnitYval: { public: true, type: 'FLOAT' },
     fUnitZval: { public: true, type: 'FLOAT' },
     fSaleUnitXval: { public: true, type: 'FLOAT' },
     fSaleUnitYval: { public: true, type: 'FLOAT' },
     fSaleUnitZval: { public: true, type: 'FLOAT' },
     fWeight: { public: true, type: 'FLOAT' },
     fVolume: { public: true, type: 'FLOAT' },
     fConsigStock: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fSuppSerialNr: { public: true, type: 'TEXT' },
     fMajStoneDet: { public: true, type: 'TEXT' },
     fColour: { public: true, type: 'TEXT' },
     fClarity: { public: true, type: 'TEXT' },
     fCert: { public: true, type: 'TEXT' },
     fMinStoneDet: { public: true, type: 'TEXT' },
     fMetal: { public: true, type: 'TEXT' },
     fRowWeight: { public: true, type: 'TEXT' },
     fSize: { public: true, type: 'TEXT' },
     fLength: { public: true, type: 'TEXT' },
     fWatchBrand: { public: true, type: 'TEXT' },
     fStyleName: { public: true, type: 'TEXT' },
     fWatchMetal: { public: true, type: 'TEXT' },
     fMovement: { public: true, type: 'TEXT' },
     fBrcStr: { public: true, type: 'TEXT' },
     fGender: { public: true, type: 'TEXT' },
     fOther: { public: true, type: 'TEXT' },
     fOther2: { public: true, type: 'TEXT' },
     fTREOFlag: { public: true, type: 'INTEGER' } },
  indexes: { SerialNrIndex120: { fields: [ 'fSerialNr', 'fArtCode' ], indicesType: 'UNIQUE' } } }