module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fServerCode: { public: true, type: 'TEXT' },
     fDate: { public: true, type: 'DATE' },
     fTime: { public: true, type: 'TIME' },
     fSampleSeconds: { public: true, type: 'FLOAT' },
     fUserCPUTime: { public: true, type: 'FLOAT' },
     fSystemCPUTime: { public: true, type: 'FLOAT' },
     fIOWaitCPUTime: { public: true, type: 'FLOAT' },
     fDiskIORead: { public: true, type: 'INTEGER' },
     fDiskIOWrite: { public: true, type: 'INTEGER' },
     fSwap: { public: true, type: 'INTEGER' },
     fServerDiskTotal: { public: true, type: 'INTEGER' },
     fServerDiskFree: { public: true, type: 'INTEGER' },
     fMemUsed: { public: true, type: 'INTEGER' },
     fMemBuffers: { public: true, type: 'INTEGER' },
     fMemTotal: { public: true, type: 'INTEGER' },
     fAvgRespTime: { public: true, type: 'INTEGER' },
     fHostName: { public: true, type: 'TEXT' },
     fReachableFlag: { public: true, type: 'INTEGER' },
     fVersionBuild: { public: true, type: 'INTEGER' },
     fIs64BitFlag: { public: true, type: 'INTEGER' },
     fSwapUsed: { public: true, type: 'INTEGER' },
     fSwapFree: { public: true, type: 'INTEGER' } },
  indexes: 
   { MainKeyIndex557: 
      { fields: [ 'fServerCode', 'fDate', 'fTime' ],
        indicesType: 'UNIQUE' } } }