module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fWHTaxSerNr: { public: true, type: 'INTEGER' },
     fCalcForm: { public: true, type: 'TEXT' },
     fPayMode: { public: true, type: 'TEXT' },
     fVECode: { public: true, type: 'TEXT' },
     fVEName: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fUserName: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fOPNr: { public: true, type: 'INTEGER' },
     fOPTransDate: { public: true, type: 'DATE' },
     fOPRefStr: { public: true, type: 'TEXT' },
     fOPComment: { public: true, type: 'TEXT' },
     fBankCurncy: { public: true, type: 'TEXT' },
     fCalcBase: { public: true, type: 'FLOAT' },
     fAmount: { public: true, type: 'FLOAT' },
     fLangCode: { public: true, type: 'TEXT' },
     fOPRow: { public: true, type: 'INTEGER' },
     fDocName: { public: true, type: 'TEXT' },
     fWHTax: { public: true, type: 'TEXT' },
     fMinAmount: { public: true, type: 'FLOAT' },
     fNoTaxAmount: { public: true, type: 'FLOAT' },
     fBaseAmount: { public: true, type: 'FLOAT' },
     fBaseCalc: { public: true, type: 'INTEGER' },
     fTaxCalc: { public: true, type: 'INTEGER' },
     fWHTaxComment: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fAccBaseAmount: { public: true, type: 'FLOAT' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fTaxPrc: { public: true, type: 'FLOAT' },
     WHCertificateVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fOPRow: { public: true, type: 'INTEGER' },
           fBaseAmount: { public: true, type: 'FLOAT' },
           fInvoiceNr: { public: true, type: 'TEXT' },
           fAmount: { public: true, type: 'FLOAT' },
           fAccBaseAmount: { public: true, type: 'FLOAT' } } } },
  indexes: { SerNrIndex477: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }