module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fCredManNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fRecordNr: { public: true, type: 'INTEGER' },
     fFileName: { public: true, type: 'TEXT' },
     fInvSum: { public: true, type: 'FLOAT' },
     fPaidSum: { public: true, type: 'FLOAT' },
     fComment: { public: true, type: 'TEXT' },
     fCredManEventNr: { public: true, type: 'INTEGER' },
     fNLTrans: { public: true, type: 'INTEGER' },
     fPaidFlag: { public: true, type: 'INTEGER' },
     CredManEventVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fChargeType: { public: true, type: 'INTEGER' },
           fSum: { public: true, type: 'FLOAT' } } },
     fTotSum: { public: true, type: 'FLOAT' },
     fDueDate: { public: true, type: 'DATE' },
     fCredManBal: { public: true, type: 'FLOAT' } },
  indexes: { SerNrIndex623: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }