module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fUser: { public: true, type: 'TEXT' },
     fGroup: { public: true, type: 'TEXT' },
     fFileName: { public: true, type: 'TEXT' },
     fRecSerNr: { public: true, type: 'INTEGER' },
     fRecCode: { public: true, type: 'TEXT' },
     fCreateDate: { public: true, type: 'DATE' },
     fCreateTime: { public: true, type: 'TIME' },
     fDecisionDate: { public: true, type: 'DATE' },
     fDecisionTime: { public: true, type: 'TIME' },
     fStatus: { public: true, type: 'INTEGER' },
     fOneLineComment: { public: true, type: 'TEXT' },
     fTotalSum: { public: true, type: 'FLOAT' },
     fRowNo: { public: true, type: 'INTEGER' },
     fAccNumber: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fSum: { public: true, type: 'FLOAT' },
     fItem: { public: true, type: 'TEXT' },
     fQty: { public: true, type: 'FLOAT' },
     fPRCode: { public: true, type: 'TEXT' },
     fVATCode: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex440: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }