module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fInactive: { public: true, type: 'INTEGER' },
     fDescription: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fAT2Class: { public: true, type: 'TEXT' },
     fAT2Group: { public: true, type: 'TEXT' },
     fComment0: { public: true, type: 'TEXT' },
     fD1: { public: true, type: 'TEXT' },
     fD2: { public: true, type: 'TEXT' },
     fD3: { public: true, type: 'TEXT' },
     fLastSTDate: { public: true, type: 'DATE' },
     fCurQuant: { public: true, type: 'FLOAT' },
     fAssetType: { public: true, type: 'INTEGER' },
     fModel1: { public: true, type: 'TEXT' },
     fModel2: { public: true, type: 'TEXT' },
     fMinModel: { public: true, type: 'TEXT' },
     fMaxModel: { public: true, type: 'TEXT' },
     fAcumulateDpr: { public: true, type: 'INTEGER' },
     fExclude: { public: true, type: 'INTEGER' },
     AT2VcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fLangCode: { public: true, type: 'TEXT' },
           fText: { public: true, type: 'TEXT' } } } },
  indexes: { CodeIndex243: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }