module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fTBtype: { public: true, type: 'INTEGER' },
     fTransTime: { public: true, type: 'TEXT' },
     fPath: { public: true, type: 'TEXT' },
     fCloseTime: { public: true, type: 'TEXT' },
     fOpenTime: { public: true, type: 'TEXT' },
     fUpdateBrowse: { public: true, type: 'INTEGER' },
     fXxx: { public: true, type: 'INTEGER' },
     fMailCleanup: { public: true, type: 'INTEGER' },
     fBackup: { public: true, type: 'INTEGER' },
     fDailyHAL: { public: true, type: 'TEXT' },
     fBackgroundHAL: { public: true, type: 'TEXT' },
     fBackgroundTimer: { public: true, type: 'INTEGER' },
     fClientTimeOut: { public: true, type: 'INTEGER' },
     fDBCopyTime: { public: true, type: 'TEXT' },
     fDBCopyTime2: { public: true, type: 'TEXT' },
     fHTSConnectionTime: { public: true, type: 'TEXT' },
     fHTSBackgroundTimer: { public: true, type: 'INTEGER' },
     fContDBCopyf: { public: true, type: 'INTEGER' },
     fContDBCopyMinDelay: { public: true, type: 'INTEGER' },
     fReportTimeout: { public: true, type: 'INTEGER' } } }