module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fType: { public: true, type: 'INTEGER' },
     fHALFunc: { public: true, type: 'TEXT' },
     fWebMenu: { public: true, type: 'TEXT' },
     fTemplateElement: { public: true, type: 'TEXT' },
     fDivID: { public: true, type: 'TEXT' },
     fDivClass: { public: true, type: 'TEXT' },
     fNoDiv: { public: true, type: 'INTEGER' },
     WebNGElementVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fWebElement: { public: true, type: 'TEXT' },
           fPosition: { public: true, type: 'INTEGER' } } },
     fMath2: { public: true, type: 'TEXT' },
     fLinkToStruct: { public: true, type: 'INTEGER' },
     fDefLangCode: { public: true, type: 'TEXT' },
     fWrapContentInDiv: { public: true, type: 'INTEGER' },
     fContentDivID: { public: true, type: 'TEXT' },
     fContentDivClass: { public: true, type: 'TEXT' },
     fLogAccess: { public: true, type: 'INTEGER' } },
  indexes: { CodeIndex590: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }