module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCompanyNr: { public: true, type: 'INTEGER' },
     fCustCode: { public: true, type: 'TEXT' },
     fSessionID: { public: true, type: 'TEXT' },
     fBasketNo: { public: true, type: 'INTEGER' },
     fValidUntil: { public: true, type: 'DATE' },
     WebNGShopBasketVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fProduct: { public: true, type: 'TEXT' },
           fProductConfig: { public: true, type: 'INTEGER' },
           fQty: { public: true, type: 'FLOAT' },
           fPrice: { public: true, type: 'FLOAT' },
           fDiscount: { public: true, type: 'FLOAT' },
           fDateAdded: { public: true, type: 'DATE' },
           fTimeAdded: { public: true, type: 'TIME' },
           fComment: { public: true, type: 'TEXT' },
           fVATCode: { public: true, type: 'TEXT' },
           fCUServiceHistNr: { public: true, type: 'INTEGER' },
           fCUServiceValidUntil: { public: true, type: 'DATE' },
           fPeriodStartDate: { public: true, type: 'DATE' },
           fMaintQty: { public: true, type: 'FLOAT' },
           fMaintPrice: { public: true, type: 'FLOAT' },
           fMaintRowSum: { public: true, type: 'FLOAT' },
           fMonths: { public: true, type: 'FLOAT' },
           fSubINPackageType: { public: true, type: 'INTEGER' },
           fQtyType: { public: true, type: 'INTEGER' },
           fPalletQty: { public: true, type: 'FLOAT' } } },
     fFreight: { public: true, type: 'FLOAT' },
     fVAT: { public: true, type: 'FLOAT' },
     fSum: { public: true, type: 'FLOAT' },
     fCurrencyCode: { public: true, type: 'TEXT' },
     fDelAddrCode: { public: true, type: 'TEXT' },
     fTAX1Sum: { public: true, type: 'FLOAT' },
     fMaintSum: { public: true, type: 'FLOAT' },
     fOrderNr: { public: true, type: 'INTEGER' },
     fShipDate: { public: true, type: 'DATE' },
     fFileName: { public: true, type: 'TEXT' },
     fTransNr: { public: true, type: 'INTEGER' },
     fPeriodLength: { public: true, type: 'INTEGER' },
     fDelMode: { public: true, type: 'TEXT' },
     fFreightCompDesc: { public: true, type: 'TEXT' } },
  indexes: 
   { BasketIndex605: 
      { fields: [ 'fCompanyNr', 'fCustCode', 'fBasketNo', 'fSessionID' ],
        indicesType: 'UNIQUE' } } }