module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fStaffCode: { public: true, type: 'TEXT' },
     RebVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fITCode: { public: true, type: 'TEXT' },
           fStaffCode: { public: true, type: 'TEXT' },
           fVra0: { public: true, type: 'FLOAT' },
           fVra1: { public: true, type: 'FLOAT' },
           fVra2: { public: true, type: 'FLOAT' },
           fVra3: { public: true, type: 'FLOAT' },
           fVra4: { public: true, type: 'FLOAT' },
           fVra5: { public: true, type: 'FLOAT' },
           fVra6: { public: true, type: 'FLOAT' },
           fVra7: { public: true, type: 'FLOAT' },
           fVra8: { public: true, type: 'FLOAT' },
           fVra9: { public: true, type: 'FLOAT' },
           fCodeType: { public: true, type: 'INTEGER' } } },
     fVra0: { public: true, type: 'FLOAT' },
     fVra1: { public: true, type: 'FLOAT' },
     fVra2: { public: true, type: 'FLOAT' },
     fVra3: { public: true, type: 'FLOAT' },
     fVra4: { public: true, type: 'FLOAT' },
     fVra5: { public: true, type: 'FLOAT' },
     fVra6: { public: true, type: 'FLOAT' },
     fVra7: { public: true, type: 'FLOAT' },
     fVra8: { public: true, type: 'FLOAT' },
     fVra9: { public: true, type: 'FLOAT' },
     fDiscAcc: { public: true, type: 'TEXT' },
     fDiscPerc: { public: true, type: 'FLOAT' },
     fVATCode: { public: true, type: 'TEXT' },
     fFromDate: { public: true, type: 'DATE' },
     fToDate: { public: true, type: 'DATE' },
     fReplaces: { public: true, type: 'TEXT' } },
  indexes: { CodeIndex79: { fields: [ 'fCode', 'fFromDate' ], indicesType: 'UNIQUE' } } }