module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fCardType: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fInterest: { public: true, type: 'FLOAT' },
     fFee: { public: true, type: 'FLOAT' },
     fDirect: { public: true, type: 'INTEGER' },
     fVECode: { public: true, type: 'TEXT' },
     fAccNumber: { public: true, type: 'TEXT' },
     fAccNumber1: { public: true, type: 'TEXT' },
     fAccNumber2: { public: true, type: 'TEXT' },
     fCompCode1: { public: true, type: 'TEXT' },
     fCompCode2: { public: true, type: 'TEXT' },
     fCompCode3: { public: true, type: 'TEXT' },
     fCompCode4: { public: true, type: 'TEXT' },
     fCompCode5: { public: true, type: 'TEXT' },
     fPayMode: { public: true, type: 'TEXT' },
     fUseOnWeb: { public: true, type: 'INTEGER' },
     fUseOnPos: { public: true, type: 'INTEGER' },
     fPayTerm: { public: true, type: 'TEXT' },
     fTargetAcc: { public: true, type: 'TEXT' } },
  indexes: { CodeIndex293: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }