module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fTRNumber: { public: true, type: 'TEXT' },
     fOrdNumber: { public: true, type: 'TEXT' },
     fType: { public: true, type: 'INTEGER' },
     fTypeRef: { public: true, type: 'TEXT' },
     fSum: { public: true, type: 'FLOAT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fReference: { public: true, type: 'TEXT' },
     fOffReference: { public: true, type: 'TEXT' },
     fClass: { public: true, type: 'TEXT' },
     fPrc: { public: true, type: 'FLOAT' },
     fComment: { public: true, type: 'TEXT' },
     fPayName: { public: true, type: 'TEXT' },
     fPayBankAcc: { public: true, type: 'TEXT' },
     fPayVATNr: { public: true, type: 'TEXT' },
     fPayRegNr1: { public: true, type: 'TEXT' },
     fPayRegNr2: { public: true, type: 'TEXT' },
     fPayTransDate: { public: true, type: 'DATE' },
     fPayReference: { public: true, type: 'TEXT' },
     fRcpName: { public: true, type: 'TEXT' },
     fRcpBankAcc: { public: true, type: 'TEXT' },
     fRcpVATNr: { public: true, type: 'TEXT' },
     fRcpRegNr1: { public: true, type: 'TEXT' },
     fRcpRegNr2: { public: true, type: 'TEXT' },
     fRcpTransDate: { public: true, type: 'DATE' },
     fRcpReference: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fReconsf: { public: true, type: 'INTEGER' },
     fMath: { public: true, type: 'INTEGER' },
     fFileName: { public: true, type: 'TEXT' },
     fTransNr: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex504: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }