module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fRegDate: { public: true, type: 'DATE' },
     fComment: { public: true, type: 'TEXT' },
     fLocation: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fInclVAT: { public: true, type: 'INTEGER' },
     fSumQuant: { public: true, type: 'FLOAT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fSign: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fSalesMan: { public: true, type: 'TEXT' },
     INTransferVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fSpec: { public: true, type: 'TEXT' },
           fStatus: { public: true, type: 'INTEGER' },
           fFIFO: { public: true, type: 'FLOAT' },
           fValue: { public: true, type: 'FLOAT' },
           fPurchaseDate: { public: true, type: 'DATE' },
           fWarrantyUntil: { public: true, type: 'DATE' },
           fVECode: { public: true, type: 'TEXT' },
           fContact: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fCostAcc: { public: true, type: 'TEXT' },
           fFIFORowVal: { public: true, type: 'FLOAT' },
           fLocation: { public: true, type: 'TEXT' },
           fCoefficient: { public: true, type: 'FLOAT' },
           fInventoryNr: { public: true, type: 'TEXT' },
           fRentResRow: { public: true, type: 'INTEGER' },
           fPosCode: { public: true, type: 'TEXT' },
           fPURow: { public: true, type: 'INTEGER' } } },
     fLocOKNr: { public: true, type: 'FLOAT' },
     fObjects: { public: true, type: 'TEXT' },
     fCostAcc: { public: true, type: 'TEXT' },
     fFrLocation: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fInvalidDate: { public: true, type: 'DATE' },
     fPUNr: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex351: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }