module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fResCode: { public: true, type: 'TEXT' },
     fXPRPlNo: { public: true, type: 'TEXT' },
     fXPlace: { public: true, type: 'TEXT' },
     fResName: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fStartTime: { public: true, type: 'TIME' },
     fEndTime: { public: true, type: 'TIME' },
     fLangCode: { public: true, type: 'TEXT' },
     fXUserSign: { public: true, type: 'TEXT' },
     fXPlanShip: { public: true, type: 'TEXT' },
     fXInvd: { public: true, type: 'INTEGER' },
     fXExSerNr: { public: true, type: 'TEXT' },
     fXTSgen: { public: true, type: 'TEXT' },
     fXTSNr: { public: true, type: 'TEXT' },
     fType: { public: true, type: 'TEXT' },
     fXPRPlName: { public: true, type: 'TEXT' },
     fXPlaceName: { public: true, type: 'TEXT' },
     fCustContact: { public: true, type: 'TEXT' },
     JobVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math2',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fCUCode: { public: true, type: 'TEXT' },
           fCUName: { public: true, type: 'TEXT' },
           fPriceList: { public: true, type: 'TEXT' },
           fGuestCode: { public: true, type: 'TEXT' },
           fBarTab: { public: true, type: 'INTEGER' },
           fVisaNo: { public: true, type: 'TEXT' },
           fVisaType: { public: true, type: 'TEXT' },
           fVisaValid: { public: true, type: 'DATE' },
           fVRebate: { public: true, type: 'FLOAT' },
           fCClass: { public: true, type: 'TEXT' },
           fArrivalSequence: { public: true, type: 'INTEGER' } } },
     fEndDate: { public: true, type: 'DATE' },
     fRegDate: { public: true, type: 'DATE' },
     fComment: { public: true, type: 'TEXT' },
     fResStatus: { public: true, type: 'TEXT' },
     fSource: { public: true, type: 'TEXT' },
     fLengthClass: { public: true, type: 'INTEGER' },
     fCUCode: { public: true, type: 'TEXT' },
     fCUName: { public: true, type: 'TEXT' },
     fPersons: { public: true, type: 'INTEGER' },
     fLastTransferDate: { public: true, type: 'DATE' },
     fLastTransferTime: { public: true, type: 'TIME' },
     fPriceList: { public: true, type: 'TEXT' },
     fMaxPersons: { public: true, type: 'INTEGER' },
     fSalesMan: { public: true, type: 'TEXT' },
     fSalesGroup: { public: true, type: 'TEXT' },
     fResUsage: { public: true, type: 'TEXT' },
     fBookOrigin: { public: true, type: 'TEXT' },
     fMother: { public: true, type: 'INTEGER' },
     fPLPrice: { public: true, type: 'FLOAT' },
     fAgreedPrice: { public: true, type: 'FLOAT' },
     fAgreedDiscount: { public: true, type: 'FLOAT' },
     fSum4: { public: true, type: 'FLOAT' },
     fXQtyConv: { public: true, type: 'TEXT' },
     fBookDate: { public: true, type: 'DATE' },
     fRequestType: { public: true, type: 'TEXT' },
     fSourceName: { public: true, type: 'TEXT' },
     fConfComment: { public: true, type: 'TEXT' },
     fTotalSum4: { public: true, type: 'FLOAT' },
     fSwitchFlag: { public: true, type: 'INTEGER' },
     fSign: { public: true, type: 'TEXT' },
     fNrOfDays: { public: true, type: 'INTEGER' },
     fLTxtCode: { public: true, type: 'TEXT' },
     fRoomChangeFlag: { public: true, type: 'INTEGER' },
     fGroupWillNotPay: { public: true, type: 'INTEGER' },
     fVatSum: { public: true, type: 'FLOAT' },
     fTotalVatSum: { public: true, type: 'FLOAT' },
     fConfDate: { public: true, type: 'DATE' },
     fNewspapers: { public: true, type: 'TEXT' },
     fCreditCard: { public: true, type: 'TEXT' },
     fAuthorizationCode: { public: true, type: 'TEXT' },
     fPreAuthorized: { public: true, type: 'INTEGER' },
     fExtraBeds: { public: true, type: 'INTEGER' },
     fChildren: { public: true, type: 'INTEGER' },
     fMaxChildren: { public: true, type: 'INTEGER' },
     fBranchID: { public: true, type: 'TEXT' },
     fSum4ExclDisc: { public: true, type: 'FLOAT' },
     fRefStr: { public: true, type: 'TEXT' },
     fWebSession: { public: true, type: 'TEXT' },
     fPax: { public: true, type: 'INTEGER' },
     fMaxPax: { public: true, type: 'INTEGER' },
     fVisitPurpose: { public: true, type: 'TEXT' },
     fReservationType: { public: true, type: 'INTEGER' },
     fResLoc: { public: true, type: 'TEXT' },
     fElectronicCardsNo: { public: true, type: 'INTEGER' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fBorderCheckPoint: { public: true, type: 'TEXT' },
     fTourOperator: { public: true, type: 'TEXT' },
     fTourOperatorName: { public: true, type: 'TEXT' },
     fResources: { public: true, type: 'TEXT' },
     fAgentCommision: { public: true, type: 'FLOAT' },
     fInclVAT: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex226: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }