module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fCustCode: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fCustCat: { public: true, type: 'TEXT' },
     fFirstInvDate: { public: true, type: 'DATE' },
     fTransDate: { public: true, type: 'DATE' },
     fOurContact: { public: true, type: 'TEXT' },
     fClientContact: { public: true, type: 'TEXT' },
     fExportFlag: { public: true, type: 'INTEGER' },
     fPriceList: { public: true, type: 'TEXT' },
     fRebCode: { public: true, type: 'TEXT' },
     fPayDeal: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fObjects: { public: true, type: 'TEXT' },
     fApproved: { public: true, type: 'INTEGER' },
     fSalesMan: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fInvUntil: { public: true, type: 'DATE' },
     fInvoiceToCode: { public: true, type: 'TEXT' },
     fXCustVATCode: { public: true, type: 'TEXT' },
     fInvSum4: { public: true, type: 'FLOAT' },
     fXPaidInvSum4: { public: true, type: 'FLOAT' },
     fTotalSum: { public: true, type: 'FLOAT' },
     fMonthlySum: { public: true, type: 'FLOAT' },
     fXDepositItem: { public: true, type: 'TEXT' },
     fDepositSum: { public: true, type: 'FLOAT' },
     fDepositPrc: { public: true, type: 'FLOAT' },
     fInstalment: { public: true, type: 'TEXT' },
     fXInstalmentItem: { public: true, type: 'TEXT' },
     fInstalmentType: { public: true, type: 'INTEGER' },
     fInstalmentMonths: { public: true, type: 'INTEGER' },
     CredManVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fChargeType: { public: true, type: 'INTEGER' },
           fQuant: { public: true, type: 'FLOAT' },
           fPrice: { public: true, type: 'FLOAT' },
           fSum: { public: true, type: 'FLOAT' },
           fVRebate: { public: true, type: 'FLOAT' },
           fPriceFactor: { public: true, type: 'FLOAT' },
           fInvoicedOn: { public: true, type: 'INTEGER' },
           fInvoicedSum: { public: true, type: 'FLOAT' } } },
     fIntRate: { public: true, type: 'FLOAT' },
     fRateType: { public: true, type: 'INTEGER' },
     fIVNr: { public: true, type: 'INTEGER' },
     fQTNr: { public: true, type: 'INTEGER' },
     fXRateItem: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fCredManAcc: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fTotalSumExclDep: { public: true, type: 'FLOAT' },
     fTotalInterest: { public: true, type: 'FLOAT' },
     fARAcc: { public: true, type: 'TEXT' },
     fARAccObject: { public: true, type: 'TEXT' },
     fBaseTotalSum: { public: true, type: 'FLOAT' },
     fFirstIntDate: { public: true, type: 'DATE' },
     fType: { public: true, type: 'TEXT' },
     fLateRateOption: { public: true, type: 'INTEGER' },
     fLateFeeDays: { public: true, type: 'INTEGER' },
     fChargeMethod: { public: true, type: 'INTEGER' },
     fFreeDays: { public: true, type: 'INTEGER' },
     fSettleLimit: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex622: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }