module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fPayMode: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fCurPayVal: { public: true, type: 'FLOAT' },
     fRegDate: { public: true, type: 'DATE' },
     fOKMark: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     IPVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fOvst: { public: true, type: 'INTEGER' },
           fInvoiceNr: { public: true, type: 'INTEGER' },
           fPayDate: { public: true, type: 'DATE' },
           fCustCode: { public: true, type: 'TEXT' },
           fLatedays: { public: true, type: 'INTEGER' },
           fCustName: { public: true, type: 'TEXT' },
           fCUPNr: { public: true, type: 'INTEGER' },
           fChequeNr: { public: true, type: 'INTEGER' },
           fVATVal: { public: true, type: 'FLOAT' },
           fVATCode: { public: true, type: 'TEXT' },
           fInvOutstand: { public: true, type: 'FLOAT' },
           fInvCurncy: { public: true, type: 'TEXT' },
           fInvVal: { public: true, type: 'FLOAT' },
           fPayMode: { public: true, type: 'TEXT' },
           fBankCurncy: { public: true, type: 'TEXT' },
           fBankVal: { public: true, type: 'FLOAT' },
           fRecCurncy: { public: true, type: 'TEXT' },
           fRecVal: { public: true, type: 'FLOAT' },
           fBankFeeVal: { public: true, type: 'FLOAT' },
           fRoundOff: { public: true, type: 'FLOAT' },
           fRoundOffAcc: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fCoef: { public: true, type: 'FLOAT' },
           fBankFeePrc: { public: true, type: 'FLOAT' },
           fTAX1Sum: { public: true, type: 'FLOAT' },
           fOrderNr: { public: true, type: 'INTEGER' },
           fComment: { public: true, type: 'TEXT' },
           fB1BankVal: { public: true, type: 'FLOAT' },
           fB2BankVal: { public: true, type: 'FLOAT' },
           fToRateB1BankVal: { public: true, type: 'FLOAT' },
           fToRateB2BankVal: { public: true, type: 'FLOAT' },
           fRkRecNumber: { public: true, type: 'TEXT' },
           fARAcc: { public: true, type: 'TEXT' },
           fTAX2Prc: { public: true, type: 'FLOAT' },
           fCredManNr: { public: true, type: 'INTEGER' },
           fSuggestVal: { public: true, type: 'FLOAT' },
           fInstNr: { public: true, type: 'INTEGER' },
           fWriteOffAcc: { public: true, type: 'TEXT' },
           fFrRateBankVal: { public: true, type: 'FLOAT' },
           fBaseRate1BankVal: { public: true, type: 'FLOAT' },
           fBaseRate2BankVal: { public: true, type: 'FLOAT' },
           fTaxTemplateCode: { public: true, type: 'TEXT' },
           fTaxMatrix: { public: true, type: 'TEXT' },
           fInvoiceOfficialSerNr: { public: true, type: 'TEXT' } } },
     fSign: { public: true, type: 'TEXT' },
     fARonTR: { public: true, type: 'INTEGER' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fReceivedFlag: { public: true, type: 'INTEGER' },
     fRejectedFlag: { public: true, type: 'INTEGER' },
     fRecNumber: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fPayCurCode: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fPrntdf: { public: true, type: 'INTEGER' },
     fAuthorizationCode: { public: true, type: 'TEXT' },
     fMachineName: { public: true, type: 'TEXT' },
     fDrawerCode: { public: true, type: 'TEXT' },
     fRegTime: { public: true, type: 'TIME' },
     fIPBookVAT: { public: true, type: 'INTEGER' },
     fOfficialSerNr: { public: true, type: 'TEXT' },
     fOfficialSerNr2: { public: true, type: 'TEXT' },
     fStatus: { public: true, type: 'INTEGER' },
     fBranchID: { public: true, type: 'TEXT' },
     fTerminalID: { public: true, type: 'TEXT' },
     fOfficialSerNrSerie: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex36: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }