module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCompName: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fAddr1: { public: true, type: 'TEXT' },
     fAddr2: { public: true, type: 'TEXT' },
     fAddr3: { public: true, type: 'TEXT' },
     fAddr4: { public: true, type: 'TEXT' },
     fPhone: { public: true, type: 'TEXT' },
     fFax: { public: true, type: 'TEXT' },
     fEmailAddr: { public: true, type: 'TEXT' },
     fRegNr1: { public: true, type: 'TEXT' },
     fVATNr: { public: true, type: 'TEXT' },
     fRegNr2: { public: true, type: 'TEXT' },
     fHomeCommunity: { public: true, type: 'TEXT' },
     fBusinessName: { public: true, type: 'TEXT' },
     fManager: { public: true, type: 'TEXT' },
     fChiefAccountant: { public: true, type: 'TEXT' },
     fWwwAddr: { public: true, type: 'TEXT' },
     fUseremailAddr: { public: true, type: 'TEXT' },
     fUserName: { public: true, type: 'TEXT' },
     fSkypeName: { public: true, type: 'TEXT' },
     fSIPCode: { public: true, type: 'TEXT' },
     fVATLaw: { public: true, type: 'INTEGER' },
     fMarketUserName: { public: true, type: 'TEXT' },
     fMarketUserPassword: { public: true, type: 'TEXT' },
     fRegisterWithOtherMarketUserName: { public: true, type: 'INTEGER' },
     fDontShowExpiringLiceneses: { public: true, type: 'INTEGER' },
     fDontShowExpiringDate: { public: true, type: 'DATE' },
     fBillingType: { public: true, type: 'INTEGER' },
     fRetriveRegistration: { public: true, type: 'INTEGER' } } }