module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     CurncyRoundOffBlockMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fCurncyCode: { public: true, type: 'TEXT' },
           fRndTotal: { public: true, type: 'INTEGER' },
           fRndLine: { public: true, type: 'INTEGER' },
           fRndVAT: { public: true, type: 'INTEGER' },
           fPayDeal: { public: true, type: 'TEXT' },
           fVcName: { public: true, type: 'TEXT' },
           fRndTotalDecs: { public: true, type: 'INTEGER' },
           fRndTotalStep: { public: true, type: 'INTEGER' },
           fRndTotalMode: { public: true, type: 'INTEGER' },
           fRndTotalDirec: { public: true, type: 'INTEGER' },
           fRndVATDecs: { public: true, type: 'INTEGER' },
           fRndVATStep: { public: true, type: 'INTEGER' },
           fRndVATMode: { public: true, type: 'INTEGER' },
           fRndVATDirec: { public: true, type: 'INTEGER' },
           fRndRowsumDecs: { public: true, type: 'INTEGER' },
           fRndRowsumStep: { public: true, type: 'INTEGER' },
           fRndRowsumMode: { public: true, type: 'INTEGER' },
           fRndRowsumDirec: { public: true, type: 'INTEGER' } } } } }