module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fRegInCountry: { public: true, type: 'INTEGER' },
     fLangCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fLastChanged: { public: true, type: 'DATE' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fSentFlag: { public: true, type: 'INTEGER' },
     fCustCode: { public: true, type: 'TEXT' },
     fCustCat: { public: true, type: 'TEXT' },
     fClassification: { public: true, type: 'TEXT' },
     fContClass: { public: true, type: 'TEXT' },
     fJobDesc: { public: true, type: 'TEXT' },
     fPersColCode: { public: true, type: 'TEXT' },
     fProduct: { public: true, type: 'TEXT' },
     fHeader: { public: true, type: 'TEXT' },
     fGreet: { public: true, type: 'TEXT' },
     fSignature: { public: true, type: 'TEXT' },
     fURLLink: { public: true, type: 'TEXT' },
     fMessWinName: { public: true, type: 'TEXT' },
     fMath2: { public: true, type: 'TEXT' },
     fLetterNr: { public: true, type: 'INTEGER' },
     fNewPresenceNr: { public: true, type: 'INTEGER' },
     fOldPresenceNr: { public: true, type: 'INTEGER' },
     fDeletedFlag: { public: true, type: 'INTEGER' },
     fReplyToAddr: { public: true, type: 'TEXT' },
     fBackupPresenceNr: { public: true, type: 'INTEGER' },
     fAllCont: { public: true, type: 'INTEGER' },
     fVATLaw: { public: true, type: 'INTEGER' },
     fProductCode: { public: true, type: 'TEXT' } },
  indexes: 
   { SerNrIndex650: 
      { fields: [ 'fSerNr', 'fRegInCountry', 'fLangCode' ],
        indicesType: 'UNIQUE' } } }