module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fUUID: { public: true, type: 'TEXT' },
     fAppID: { public: true, type: 'INTEGER' },
     fPayMethod: { public: true, type: 'TEXT' },
     fCompleted: { public: true, type: 'INTEGER' },
     fCompletedDate: { public: true, type: 'DATE' },
     fCreatedDate: { public: true, type: 'DATE' },
     fCreatedTime: { public: true, type: 'TIME' },
     fCurrency: { public: true, type: 'TEXT' },
     fInclAmount: { public: true, type: 'FLOAT' },
     fVAT: { public: true, type: 'FLOAT' },
     fCustCode: { public: true, type: 'TEXT' },
     fCustOrderNr: { public: true, type: 'TEXT' },
     fDelAddrCode: { public: true, type: 'TEXT' },
     fOrderClass: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fStatus: { public: true, type: 'INTEGER' },
     fRecordNr: { public: true, type: 'INTEGER' },
     fDisplayCurrency: { public: true, type: 'TEXT' },
     fDisplayAmount: { public: true, type: 'FLOAT' },
     fExternalSession: { public: true, type: 'TEXT' },
     fDisplayVAT: { public: true, type: 'FLOAT' },
     fCustomField1: { public: true, type: 'TEXT' },
     fPayMentDesc: { public: true, type: 'TEXT' } },
  indexes: { UUIDIndex606: { fields: [ 'fUUID', 'fCompleted' ], indicesType: 'UNIQUE' } } }