module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fXSerNr: { public: true, type: 'INTEGER' },
     fClosedf: { public: true, type: 'INTEGER' },
     fPBXConnection: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fUsername: { public: true, type: 'TEXT' },
     fXAuthUserName: { public: true, type: 'TEXT' },
     fPassword: { public: true, type: 'TEXT' },
     fHost: { public: true, type: 'TEXT' },
     fXPort: { public: true, type: 'INTEGER' },
     fXExtension: { public: true, type: 'INTEGER' },
     fType: { public: true, type: 'INTEGER' },
     fXRegisterType: { public: true, type: 'INTEGER' },
     fDomain: { public: true, type: 'TEXT' },
     fXFromUser: { public: true, type: 'TEXT' },
     fXContext: { public: true, type: 'TEXT' },
     fXDefaultUser: { public: true, type: 'TEXT' },
     SipTrunk2VcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'xMath',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fUsername: { public: true, type: 'TEXT' },
           fAuthUsername: { public: true, type: 'TEXT' },
           fPassword: { public: true, type: 'TEXT' },
           fDomain: { public: true, type: 'TEXT' },
           fExtension: { public: true, type: 'TEXT' } } },
     fXNatf: { public: true, type: 'INTEGER' },
     fCode: { public: true, type: 'TEXT' },
     fCountryCode: { public: true, type: 'TEXT' },
     fDefaultCallerId: { public: true, type: 'TEXT' },
     fAllowGuestf: { public: true, type: 'INTEGER' },
     fAllowedIPs: { public: true, type: 'TEXT' },
     fSkipDigit: { public: true, type: 'TEXT' },
     fIAXf: { public: true, type: 'INTEGER' },
     fInsecure: { public: true, type: 'TEXT' } },
  indexes: { CodeIndex821: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }