module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fOVc: { public: true, type: 'INTEGER' },
     fRow: { public: true, type: 'INTEGER' },
     fArtCode: { public: true, type: 'TEXT' },
     fPRCode: { public: true, type: 'TEXT' },
     fEMCode: { public: true, type: 'TEXT' },
     fQty: { public: true, type: 'FLOAT' },
     fPrice: { public: true, type: 'FLOAT' },
     fDiscount: { public: true, type: 'FLOAT' },
     fSum: { public: true, type: 'FLOAT' },
     fInvQty: { public: true, type: 'FLOAT' },
     fInvoice: { public: true, type: 'INTEGER' },
     fInvAfter: { public: true, type: 'DATE' },
     fMarkup: { public: true, type: 'FLOAT' },
     fInvSeparately: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fItemType: { public: true, type: 'INTEGER' },
     fGP: { public: true, type: 'FLOAT' },
     fCostPrice: { public: true, type: 'FLOAT' },
     fObjects: { public: true, type: 'TEXT' },
     fINGroup: { public: true, type: 'TEXT' },
     fInvDate: { public: true, type: 'DATE' },
     fChildNr: { public: true, type: 'INTEGER' },
     fComment1: { public: true, type: 'TEXT' },
     fComment2: { public: true, type: 'TEXT' },
     fPRName: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fPriceInCur: { public: true, type: 'FLOAT' },
     fMarkupInCur: { public: true, type: 'FLOAT' },
     fCostPriceInCur: { public: true, type: 'FLOAT' },
     fSumInCur: { public: true, type: 'FLOAT' },
     fGPInCur: { public: true, type: 'FLOAT' },
     fPRStage: { public: true, type: 'TEXT' },
     fWIPAcc: { public: true, type: 'TEXT' },
     fWIPBalAcc: { public: true, type: 'TEXT' } },
  indexes: 
   { MainKeyIndex168: 
      { fields: 
         [ 'fPRCode',
           'fOVc',
           'fSerNr',
           'fRow',
           'fArtCode',
           'fEMCode',
           'fChildNr' ],
        indicesType: 'UNIQUE' } } }