module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fPUQuant: { public: true, type: 'INTEGER' },
     fDefaultSupplier: { public: true, type: 'TEXT' },
     fTransAccObjToPU: { public: true, type: 'INTEGER' },
     fWarnNotDefSup: { public: true, type: 'INTEGER' },
     fUseNormOrdMult: { public: true, type: 'INTEGER' },
     fCredVIUpdatePO: { public: true, type: 'INTEGER' },
     fReqPOClass: { public: true, type: 'INTEGER' },
     fOpenCreateVIFromPO: { public: true, type: 'INTEGER' },
     fNoRetPUFromPO: { public: true, type: 'INTEGER' },
     fPOMustBeOKToPU: { public: true, type: 'INTEGER' },
     fPUFromPORate: { public: true, type: 'INTEGER' },
     fCreateVIonPUOK: { public: true, type: 'INTEGER' },
     fCreateVIonRetPUOK: { public: true, type: 'INTEGER' } } }