module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fVECode: { public: true, type: 'TEXT' },
     fArtCode: { public: true, type: 'TEXT' },
     fPICode: { public: true, type: 'TEXT' },
     fQuant: { public: true, type: 'FLOAT' },
     fLocation: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fPONr: { public: true, type: 'INTEGER' },
     fPORow: { public: true, type: 'INTEGER' },
     fFromFileName: { public: true, type: 'INTEGER' },
     fFromSerNr: { public: true, type: 'INTEGER' },
     fStockReservNr: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex634: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }