module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fMacFont: { public: true, type: 'TEXT' },
     fMacSize: { public: true, type: 'INTEGER' },
     fMacFace: { public: true, type: 'INTEGER' },
     fWinFont: { public: true, type: 'TEXT' },
     fWinSize: { public: true, type: 'INTEGER' },
     fWinFace: { public: true, type: 'INTEGER' },
     fAnsiChar: { public: true, type: 'INTEGER' },
     fCharSpacing: { public: true, type: 'FLOAT' },
     fLinuxFont: { public: true, type: 'TEXT' },
     fLinuxSize: { public: true, type: 'INTEGER' },
     fLinuxFace: { public: true, type: 'INTEGER' },
     fBinaryFont: { public: true, type: 'INTEGER' },
     fPdfFontFile: { public: true, type: 'TEXT' },
     fPdfFont: { public: true, type: 'INTEGER' },
     fPdfSize: { public: true, type: 'INTEGER' },
     fPdfFace: { public: true, type: 'INTEGER' },
     fBarcodeType: { public: true, type: 'INTEGER' },
     fBarcodeVersion: { public: true, type: 'INTEGER' },
     fBarcodeECLevel: { public: true, type: 'INTEGER' },
     fRotation: { public: true, type: 'INTEGER' } },
  indexes: { MainKeyIndex60: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }