module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fQueDate: { public: true, type: 'DATE' },
     fQueTime: { public: true, type: 'TIME' },
     fEMailSent: { public: true, type: 'INTEGER' },
     fHeader: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fTransTime: { public: true, type: 'TIME' },
     fHasFileAtt: { public: true, type: 'INTEGER' },
     fHasRecAtt: { public: true, type: 'INTEGER' },
     EMailQueVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math2',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fRowTyp: { public: true, type: 'INTEGER' },
           fAddrCode: { public: true, type: 'TEXT' },
           fAddrStatus: { public: true, type: 'INTEGER' },
           fAddrFolder: { public: true, type: 'TEXT' },
           fMailbox: { public: true, type: 'INTEGER' } } },
     fMath: { public: true, type: 'TEXT' },
     fPriority: { public: true, type: 'INTEGER' },
     fLifespan: { public: true, type: 'INTEGER' },
     fOrgSerNr: { public: true, type: 'INTEGER' },
     fMessageID: { public: true, type: 'TEXT' },
     fDirection: { public: true, type: 'INTEGER' },
     fFileName: { public: true, type: 'TEXT' },
     fHtmlFlag: { public: true, type: 'INTEGER' },
     fHtmlTemplate: { public: true, type: 'TEXT' },
     fRetryCount: { public: true, type: 'INTEGER' },
     fRetryDate: { public: true, type: 'DATE' },
     fRetryTime: { public: true, type: 'TIME' },
     fSendDate: { public: true, type: 'DATE' },
     fSendTime: { public: true, type: 'TIME' } },
  indexes: 
   { SerNrIndex202: 
      { fields: [ 'fSerNr', 'fQueDate', 'fQueTime', 'fDirection' ],
        indicesType: 'UNIQUE' } } }