module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fBPCode: { public: true, type: 'TEXT' },
     fDBVers: { public: true, type: 'INTEGER' },
     fCountry: { public: true, type: 'INTEGER' },
     fPlatform: { public: true, type: 'INTEGER' },
     fURL: { public: true, type: 'TEXT' },
     fLastChangedDate: { public: true, type: 'DATE' },
     fLastChangedTime: { public: true, type: 'TIME' },
     fTestRelease: { public: true, type: 'INTEGER' },
     fClosedf: { public: true, type: 'INTEGER' },
     WebAvailableApp2VcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fCountry: { public: true, type: 'TEXT' },
           fUseAsDefault: { public: true, type: 'INTEGER' } } },
     fReleaseDate: { public: true, type: 'DATE' },
     fDescription: { public: true, type: 'TEXT' },
     fVersionBuild: { public: true, type: 'INTEGER' },
     fCustCode: { public: true, type: 'TEXT' },
     fPackType: { public: true, type: 'INTEGER' },
     fCountryCode: { public: true, type: 'TEXT' },
     fReleaseTime: { public: true, type: 'TIME' },
     fShowToCust: { public: true, type: 'INTEGER' },
     fUseAsDefault: { public: true, type: 'INTEGER' },
     fVerString: { public: true, type: 'TEXT' },
     fOrigTestRelease: { public: true, type: 'INTEGER' } },
  indexes: { MainKeyIndex838: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }