module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fFr2ARows: { public: true, type: 'TEXT' },
     fFr2ACols: { public: true, type: 'TEXT' },
     fFr3ARows: { public: true, type: 'TEXT' },
     fFr3ACols: { public: true, type: 'TEXT' },
     fFr3BRows: { public: true, type: 'TEXT' },
     fFr3BCols: { public: true, type: 'TEXT' },
     fFr4ARows: { public: true, type: 'TEXT' },
     fFr4ACols: { public: true, type: 'TEXT' },
     fFr4BRows: { public: true, type: 'TEXT' },
     fFr4BCols: { public: true, type: 'TEXT' },
     fFr5ARows: { public: true, type: 'TEXT' },
     fFr5ACols: { public: true, type: 'TEXT' },
     fFr5BRows: { public: true, type: 'TEXT' },
     fFr5BCols: { public: true, type: 'TEXT' } } }