module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fAccessDate: { public: true, type: 'DATE' },
     fHost: { public: true, type: 'TEXT' },
     fType: { public: true, type: 'INTEGER' },
     fCode: { public: true, type: 'TEXT' },
     fLangRequested: { public: true, type: 'TEXT' },
     fLangSent: { public: true, type: 'TEXT' },
     fCustCode: { public: true, type: 'TEXT' },
     fCountry: { public: true, type: 'TEXT' },
     fEnabRegNo: { public: true, type: 'INTEGER' },
     fCounter: { public: true, type: 'INTEGER' },
     fPathRequested: { public: true, type: 'TEXT' },
     fSortKey: { public: true, type: 'TEXT' },
     fUserCode: { public: true, type: 'TEXT' },
     fProgram: { public: true, type: 'TEXT' },
     fVersion: { public: true, type: 'TEXT' },
     fIP: { public: true, type: 'TEXT' },
     fSessionID: { public: true, type: 'TEXT' },
     fStartTime: { public: true, type: 'TIME' },
     fEndTime: { public: true, type: 'TIME' },
     fCity: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex607: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }