module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     AC2BlockMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fCode: { public: true, type: 'TEXT' },
           fAsset1Acc: { public: true, type: 'TEXT' },
           fDepr1Acc: { public: true, type: 'TEXT' },
           fCost1Acc: { public: true, type: 'TEXT' },
           fAsset2Acc: { public: true, type: 'TEXT' },
           fDepr2Acc: { public: true, type: 'TEXT' },
           fCost2Acc: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fAsset1Objects: { public: true, type: 'TEXT' },
           fDepr1Objects: { public: true, type: 'TEXT' },
           fCost1Objects: { public: true, type: 'TEXT' },
           fAsset2Objects: { public: true, type: 'TEXT' },
           fDepr2Objects: { public: true, type: 'TEXT' },
           fCost2Objects: { public: true, type: 'TEXT' },
           fRevDepr1Acc: { public: true, type: 'TEXT' },
           fRevDepr1Objects: { public: true, type: 'TEXT' },
           fCapCorr1Acc: { public: true, type: 'TEXT' },
           fCapCorr1Objects: { public: true, type: 'TEXT' } } } } }