module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSignature: { public: true, type: 'TEXT' },
     fActivities: { public: true, type: 'INTEGER' },
     fNotOKAct: { public: true, type: 'INTEGER' },
     fNrOfAct: { public: true, type: 'FLOAT' },
     fInvoices: { public: true, type: 'INTEGER' },
     fNotOKIV: { public: true, type: 'INTEGER' },
     fNrOfIV: { public: true, type: 'FLOAT' },
     fContQuote: { public: true, type: 'INTEGER' },
     fTermCQ: { public: true, type: 'INTEGER' },
     fNrOfCQ: { public: true, type: 'FLOAT' },
     fContract: { public: true, type: 'INTEGER' },
     fNotOKCO: { public: true, type: 'INTEGER' },
     fNrOfCO: { public: true, type: 'FLOAT' },
     fContractClass: { public: true, type: 'TEXT' },
     fMonthBal: { public: true, type: 'INTEGER' },
     fCustItem: { public: true, type: 'INTEGER' },
     fCustItemMonthNr: { public: true, type: 'INTEGER' },
     fQuotations: { public: true, type: 'INTEGER' },
     fQTClass: { public: true, type: 'TEXT' },
     fNrOfQT: { public: true, type: 'FLOAT' },
     fOrders: { public: true, type: 'INTEGER' },
     fORClass: { public: true, type: 'TEXT' },
     fNrOfOR: { public: true, type: 'FLOAT' },
     fChecks: { public: true, type: 'INTEGER' },
     fExcludeActTypes: { public: true, type: 'TEXT' },
     fPaymentHistory: { public: true, type: 'INTEGER' },
     fShowActivityClasses: { public: true, type: 'INTEGER' },
     fSMSes: { public: true, type: 'INTEGER' },
     fNrOfSMS: { public: true, type: 'FLOAT' },
     fProjects: { public: true, type: 'INTEGER' },
     fNrOfPR: { public: true, type: 'FLOAT' },
     fProjectBudgets: { public: true, type: 'INTEGER' },
     fNrOfTBBU: { public: true, type: 'FLOAT' },
     fAgreements: { public: true, type: 'INTEGER' },
     fNrOfAgreements: { public: true, type: 'FLOAT' },
     fRentalReservations: { public: true, type: 'INTEGER' },
     fNrOfRentRes: { public: true, type: 'FLOAT' },
     fServiceOrders: { public: true, type: 'INTEGER' },
     fNrOfSVO: { public: true, type: 'FLOAT' },
     fWorkSheets: { public: true, type: 'INTEGER' },
     fNrOfWS: { public: true, type: 'FLOAT' },
     fContactRelations: { public: true, type: 'INTEGER' },
     fIVCash: { public: true, type: 'INTEGER' },
     fNrOfIVCash: { public: true, type: 'FLOAT' } },
  indexes: { SignatureIndex154: { fields: [ 'fSignature' ], indicesType: 'UNIQUE' } } }