module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fAllSentFlag: { public: true, type: 'INTEGER' },
     fAsLetter: { public: true, type: 'INTEGER' },
     fAsMessage: { public: true, type: 'INTEGER' },
     fCustCode: { public: true, type: 'TEXT' },
     fCustCat: { public: true, type: 'TEXT' },
     fClassification: { public: true, type: 'TEXT' },
     fContClass: { public: true, type: 'TEXT' },
     fJobDesc: { public: true, type: 'TEXT' },
     fPersColCode: { public: true, type: 'TEXT' },
     fProduct: { public: true, type: 'TEXT' },
     fReplyToAddr: { public: true, type: 'TEXT' },
     fProductCode: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex649: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }