module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fType: { public: true, type: 'INTEGER' },
     fRow: { public: true, type: 'INTEGER' },
     fArtCode: { public: true, type: 'TEXT' },
     fCUCode: { public: true, type: 'TEXT' },
     fEMCode: { public: true, type: 'TEXT' },
     fUsedQty: { public: true, type: 'FLOAT' },
     fPrice: { public: true, type: 'FLOAT' },
     fDiscount: { public: true, type: 'FLOAT' },
     fSum: { public: true, type: 'FLOAT' },
     fInvQty: { public: true, type: 'FLOAT' },
     fInvNr: { public: true, type: 'INTEGER' },
     fMarkup: { public: true, type: 'FLOAT' },
     fComment: { public: true, type: 'TEXT' },
     fItemType: { public: true, type: 'INTEGER' },
     fGP: { public: true, type: 'FLOAT' },
     fCostPrice: { public: true, type: 'FLOAT' },
     fMotherNr: { public: true, type: 'TEXT' },
     fWONr: { public: true, type: 'INTEGER' },
     fInvoiceTo: { public: true, type: 'TEXT' },
     fSVONr: { public: true, type: 'INTEGER' },
     fSerialNr: { public: true, type: 'TEXT' },
     fCoefficient: { public: true, type: 'FLOAT' },
     fContractNr: { public: true, type: 'INTEGER' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fRecType: { public: true, type: 'INTEGER' },
     fWSNr: { public: true, type: 'INTEGER' },
     fRegTime: { public: true, type: 'TIME' } },
  indexes: 
   { MainKeyIndex208: 
      { fields: [ 'fCUCode', 'fRecType', 'fSerNr', 'fRow', 'fArtCode', 'fEMCode' ],
        indicesType: 'UNIQUE' } } }