module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fTransTime: { public: true, type: 'TIME' },
     fPerson: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fASProduct: { public: true, type: 'TEXT' },
     fASStore: { public: true, type: 'TEXT' },
     fASCountry: { public: true, type: 'TEXT' },
     fASInApp: { public: true, type: 'TEXT' },
     fCountry: { public: true, type: 'TEXT' },
     fStoreVersion: { public: true, type: 'TEXT' },
     fStoreStatus: { public: true, type: 'INTEGER' },
     fSubmissionStatus: { public: true, type: 'INTEGER' },
     fRespPM: { public: true, type: 'TEXT' },
     fASProdStatSerNr: { public: true, type: 'INTEGER' },
     ASProdStatHistVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fASInApp: { public: true, type: 'TEXT' },
           fASInAppSKU: { public: true, type: 'TEXT' },
           fASInAppMonths: { public: true, type: 'INTEGER' },
           fCountry: { public: true, type: 'TEXT' } } },
     fDateVersion: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex782: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }