module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fRegDate: { public: true, type: 'DATE' },
     fCollectionDate: { public: true, type: 'DATE' },
     fComment: { public: true, type: 'TEXT' },
     fCustCode: { public: true, type: 'TEXT' },
     fAgreementNr: { public: true, type: 'INTEGER' },
     fLocation: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fHaltInvoice: { public: true, type: 'INTEGER' },
     fSumQuant: { public: true, type: 'FLOAT' },
     fDelAddrCode: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fAddr1: { public: true, type: 'TEXT' },
     fAddr2: { public: true, type: 'TEXT' },
     fAddr3: { public: true, type: 'TEXT' },
     fDelAddr3: { public: true, type: 'TEXT' },
     fDelAddr4: { public: true, type: 'TEXT' },
     fClientContact: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fSalesMan: { public: true, type: 'TEXT' },
     CollectionVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fSpec: { public: true, type: 'TEXT' },
           fAccountedFor: { public: true, type: 'FLOAT' },
           fMissing: { public: true, type: 'FLOAT' },
           fRentResSerNo: { public: true, type: 'INTEGER' },
           fRentResRow: { public: true, type: 'INTEGER' } } },
     fOrdered: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex349: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }