module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fClosed: { public: true, type: 'INTEGER' },
     fEventType: { public: true, type: 'TEXT' },
     fResLoc: { public: true, type: 'TEXT' },
     fResCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fPeriodType: { public: true, type: 'INTEGER' },
     fStartTime: { public: true, type: 'TIME' },
     fEndTime: { public: true, type: 'TIME' },
     fDayInterval: { public: true, type: 'INTEGER' },
     fDayTimeInterval: { public: true, type: 'TIME' },
     fDayType: { public: true, type: 'INTEGER' },
     fDayDuration: { public: true, type: 'TIME' },
     fMonthInterval: { public: true, type: 'INTEGER' },
     fMonthType: { public: true, type: 'INTEGER' },
     fWeekDay: { public: true, type: 'INTEGER' },
     fWeekInterval: { public: true, type: 'INTEGER' },
     fMon: { public: true, type: 'INTEGER' },
     fTue: { public: true, type: 'INTEGER' },
     fWed: { public: true, type: 'INTEGER' },
     fThu: { public: true, type: 'INTEGER' },
     fFri: { public: true, type: 'INTEGER' },
     fSat: { public: true, type: 'INTEGER' },
     fSun: { public: true, type: 'INTEGER' },
     RsrtEventScheduleVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStartTime: { public: true, type: 'TIME' },
           fEndTime: { public: true, type: 'TIME' } } } },
  indexes: { SerNrIndex670: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }