module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fTransDate: { public: true, type: 'DATE' },
     fPRCode: { public: true, type: 'TEXT' },
     fPRName: { public: true, type: 'TEXT' },
     fCustCode: { public: true, type: 'TEXT' },
     fCustName: { public: true, type: 'TEXT' },
     fInvAddr0: { public: true, type: 'TEXT' },
     fInvAddr1: { public: true, type: 'TEXT' },
     fInvAddr2: { public: true, type: 'TEXT' },
     fInvAddr3: { public: true, type: 'TEXT' },
     fInvAddr4: { public: true, type: 'TEXT' },
     fCustContact: { public: true, type: 'TEXT' },
     fLanguage: { public: true, type: 'TEXT' },
     fVersionNr: { public: true, type: 'INTEGER' },
     fClosed: { public: true, type: 'INTEGER' },
     fSign: { public: true, type: 'INTEGER' },
     fTotalPerc: { public: true, type: 'FLOAT' },
     fCompletePerc: { public: true, type: 'FLOAT' },
     fOutstandingPerc: { public: true, type: 'FLOAT' },
     PRScheduleVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fPRStage: { public: true, type: 'TEXT' },
           fPRStageComment: { public: true, type: 'TEXT' },
           fStartDate: { public: true, type: 'DATE' },
           fEndDate: { public: true, type: 'DATE' },
           fDueDate: { public: true, type: 'DATE' },
           fDurDays: { public: true, type: 'FLOAT' },
           fDurHours: { public: true, type: 'FLOAT' },
           fHoursPerDay: { public: true, type: 'FLOAT' },
           fResponsible: { public: true, type: 'TEXT' },
           fComplete: { public: true, type: 'FLOAT' },
           fPRStageSign: { public: true, type: 'TEXT' },
           fStp: { public: true, type: 'INTEGER' } } },
     fSalesGroup: { public: true, type: 'TEXT' },
     fPrSalesMan: { public: true, type: 'TEXT' },
     fMembers: { public: true, type: 'TEXT' } },
  indexes: { PRCodeIndex661: { fields: [ 'fPRCode', 'fVersionNr' ], indicesType: 'UNIQUE' } } }