module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fClosed: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fCreateDate: { public: true, type: 'DATE' },
     fOKDate: { public: true, type: 'DATE' },
     fSign: { public: true, type: 'TEXT' },
     fVECode: { public: true, type: 'TEXT' },
     POPlanVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fItemCode: { public: true, type: 'TEXT' },
           fSpec: { public: true, type: 'TEXT' },
           fSugQty: { public: true, type: 'FLOAT' },
           fQty: { public: true, type: 'FLOAT' },
           fPONr: { public: true, type: 'INTEGER' },
           fDaysToGet: { public: true, type: 'FLOAT' },
           fPOOrdDate: { public: true, type: 'DATE' },
           fVECode: { public: true, type: 'TEXT' },
           fNeededDate: { public: true, type: 'DATE' },
           fFromItemCode: { public: true, type: 'TEXT' } } },
     fEarliestPODate: { public: true, type: 'DATE' } },
  indexes: { SerNrIndex519: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }