module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fCheckNr: { public: true, type: 'TEXT' },
     fBankCode: { public: true, type: 'TEXT' },
     fBankName: { public: true, type: 'TEXT' },
     fCUCode: { public: true, type: 'TEXT' },
     fCUName: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fEmissionDate: { public: true, type: 'DATE' },
     fEffectDate: { public: true, type: 'DATE' },
     fClearingDate: { public: true, type: 'DATE' },
     fOpenf: { public: true, type: 'INTEGER' },
     fAmount: { public: true, type: 'FLOAT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fBase1Amount: { public: true, type: 'FLOAT' },
     fBase2Amount: { public: true, type: 'FLOAT' },
     fClearedAmount: { public: true, type: 'FLOAT' },
     fBankFee: { public: true, type: 'FLOAT' },
     fComment: { public: true, type: 'TEXT' },
     fOrigAccNr: { public: true, type: 'TEXT' },
     fOrigObjects: { public: true, type: 'TEXT' },
     fTempAccNr: { public: true, type: 'TEXT' },
     fTempObjects: { public: true, type: 'TEXT' },
     fTargetAccNr: { public: true, type: 'TEXT' },
     fTargetObjects: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fChkMode: { public: true, type: 'INTEGER' },
     fECDate: { public: true, type: 'DATE' },
     fDesc: { public: true, type: 'TEXT' },
     fBankAcc: { public: true, type: 'TEXT' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fFromNo: { public: true, type: 'INTEGER' },
     fToNo: { public: true, type: 'INTEGER' },
     fToType: { public: true, type: 'INTEGER' },
     fFromFileName: { public: true, type: 'TEXT' },
     fVATNr: { public: true, type: 'TEXT' },
     fId: { public: true, type: 'TEXT' },
     fBouncedDate: { public: true, type: 'DATE' },
     fCancelledDate: { public: true, type: 'DATE' },
     fAcceptedDate: { public: true, type: 'DATE' },
     fEndorsedDate: { public: true, type: 'DATE' },
     fToFileName: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex211: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }