module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fAccNumber: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fAccType: { public: true, type: 'INTEGER' },
     fNVD: { public: true, type: 'INTEGER' },
     fNVC: { public: true, type: 'INTEGER' },
     fAutCode: { public: true, type: 'TEXT' },
     fBlockedFlag: { public: true, type: 'INTEGER' },
     fVATCode: { public: true, type: 'TEXT' },
     fControlType: { public: true, type: 'INTEGER' },
     fCurncy: { public: true, type: 'TEXT' },
     fConsAccNumber: { public: true, type: 'TEXT' },
     fConspr: { public: true, type: 'INTEGER' },
     fObjects: { public: true, type: 'TEXT' },
     fSRUCode: { public: true, type: 'TEXT' },
     fExclFrRep: { public: true, type: 'INTEGER' },
     fPeriodCode: { public: true, type: 'TEXT' },
     fGroupAcc: { public: true, type: 'INTEGER' },
     fTransAutCode: { public: true, type: 'TEXT' },
     AccVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fLangCode: { public: true, type: 'TEXT' },
           fText: { public: true, type: 'TEXT' } } },
     fTaxTemplateCode: { public: true, type: 'TEXT' },
     fAccClass: { public: true, type: 'TEXT' },
     fNotBalSheet: { public: true, type: 'INTEGER' } },
  indexes: { AccNumberIndex0: { fields: [ 'fAccNumber' ], indicesType: 'UNIQUE' } } }