module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fDivID: { public: true, type: 'TEXT' },
     fDivClass: { public: true, type: 'TEXT' },
     fNoDiv: { public: true, type: 'INTEGER' },
     fListViewFlag: { public: true, type: 'INTEGER' },
     fHandlerAppNode: { public: true, type: 'INTEGER' },
     fElementCount: { public: true, type: 'INTEGER' },
     fElementTemplate: { public: true, type: 'TEXT' },
     fHeadingClass: { public: true, type: 'TEXT' },
     fPrintDate: { public: true, type: 'INTEGER' },
     fCommentFlag: { public: true, type: 'INTEGER' },
     fSortingFlag: { public: true, type: 'INTEGER' },
     fGroupByCountry: { public: true, type: 'INTEGER' },
     fGroupByCategory: { public: true, type: 'INTEGER' },
     fCountryHeaderDivClass: { public: true, type: 'TEXT' },
     fCatHeaderDivClass: { public: true, type: 'TEXT' },
     fPageTemplate: { public: true, type: 'TEXT' },
     fPrintDateList: { public: true, type: 'INTEGER' },
     fCommentListFlag: { public: true, type: 'INTEGER' },
     fListDateClass: { public: true, type: 'TEXT' },
     fDateClass: { public: true, type: 'TEXT' },
     fListTextClass: { public: true, type: 'TEXT' },
     fTextClass: { public: true, type: 'TEXT' },
     fListHeadingClass: { public: true, type: 'TEXT' } },
  indexes: { CodeIndex598: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }