module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fDispGroup: { public: true, type: 'TEXT' },
     fAgreeStatusCreated: { public: true, type: 'TEXT' },
     fAgreeStatusReturned: { public: true, type: 'TEXT' },
     fAgreeStatusDelivered: { public: true, type: 'TEXT' },
     fStartDateFromDispatch: { public: true, type: 'INTEGER' },
     fEndDateFromOffHire: { public: true, type: 'INTEGER' },
     fAuthCustf: { public: true, type: 'INTEGER' },
     fNormalOut: { public: true, type: 'TIME' },
     fNormalIn: { public: true, type: 'TIME' },
     fStartNewDay: { public: true, type: 'TIME' },
     fEndOfDay: { public: true, type: 'TIME' },
     fAgreeStatusDone: { public: true, type: 'TEXT' },
     fNotActiveCol: { public: true, type: 'INTEGER' },
     fSetSerialNoToAssetNo: { public: true, type: 'INTEGER' },
     fChargeForFirstDay: { public: true, type: 'INTEGER' },
     fCheckCustOrdNr: { public: true, type: 'INTEGER' },
     fCheckLanguage: { public: true, type: 'INTEGER' },
     fMaxOneQTPerAgr: { public: true, type: 'INTEGER' },
     fPrintQTOnAgr: { public: true, type: 'INTEGER' },
     fRentQTMustHaveEndDate: { public: true, type: 'INTEGER' },
     fUseInQty: { public: true, type: 'INTEGER' },
     fChrPerAdvPric: { public: true, type: 'INTEGER' },
     fAdvUseInvItemPrice: { public: true, type: 'INTEGER' },
     fAdvSkipIfNotOnPL: { public: true, type: 'INTEGER' } } }