module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSharedPoolSize: { public: true, type: 'INTEGER' },
     fSharedHostingConfig: { public: true, type: 'INTEGER' },
     fSharedHostingConfigComment: { public: true, type: 'TEXT' },
     fSharedAmazonInstanceType: { public: true, type: 'TEXT' },
     fSharedDiskSize: { public: true, type: 'INTEGER' },
     fSharedSSDFlag: { public: true, type: 'INTEGER' },
     fMedPoolSize: { public: true, type: 'INTEGER' },
     fMedHostingConfig: { public: true, type: 'INTEGER' },
     fMedHostingConfigComment: { public: true, type: 'TEXT' },
     fMedAmazonInstanceType: { public: true, type: 'TEXT' },
     fMedDiskSize: { public: true, type: 'INTEGER' },
     fMedSSDFlag: { public: true, type: 'INTEGER' },
     fLargePoolSize: { public: true, type: 'INTEGER' },
     fLargeHostingConfig: { public: true, type: 'INTEGER' },
     fLargeHostingConfigComment: { public: true, type: 'TEXT' },
     fLargeAmazonInstanceType: { public: true, type: 'TEXT' },
     fLargeDiskSize: { public: true, type: 'INTEGER' },
     fLargeSSDFlag: { public: true, type: 'INTEGER' },
     fSmallPoolSize: { public: true, type: 'INTEGER' },
     fSmallHostingConfig: { public: true, type: 'INTEGER' },
     fSmallHostingConfigComment: { public: true, type: 'TEXT' },
     fSmallAmazonInstanceType: { public: true, type: 'TEXT' },
     fSmallDiskSize: { public: true, type: 'INTEGER' },
     fSmallSSDFlag: { public: true, type: 'INTEGER' },
     fSharedPoolMaxCapacity: { public: true, type: 'INTEGER' },
     fSharedReadyState: { public: true, type: 'INTEGER' },
     fMedReadyState: { public: true, type: 'INTEGER' },
     fLargeReadyState: { public: true, type: 'INTEGER' },
     fSmallReadyState: { public: true, type: 'INTEGER' } } }