module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fDepCode: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fAccount: { public: true, type: 'TEXT' },
     fWriteoff: { public: true, type: 'INTEGER' },
     fWriteoffMark: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fRefStr: { public: true, type: 'TEXT' },
     fCause: { public: true, type: 'TEXT' },
     AT2WrofVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fAT2Code: { public: true, type: 'TEXT' },
           fDescription: { public: true, type: 'TEXT' },
           fInventoryNr: { public: true, type: 'TEXT' },
           fAccount: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fSalesVal: { public: true, type: 'FLOAT' },
           fQty: { public: true, type: 'FLOAT' },
           fDprVal: { public: true, type: 'FLOAT' } } },
     fTransTime: { public: true, type: 'TIME' },
     fLangCode: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex251: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }