module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fOurUser: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fPlanShip: { public: true, type: 'TEXT' },
     fReceivedDate: { public: true, type: 'DATE' },
     fOSFlag: { public: true, type: 'INTEGER' },
     fStatusFlag: { public: true, type: 'INTEGER' },
     fStatusMark: { public: true, type: 'INTEGER' },
     fOKPersons: { public: true, type: 'TEXT' },
     fReference: { public: true, type: 'TEXT' },
     fDepartment: { public: true, type: 'TEXT' },
     fLocation: { public: true, type: 'TEXT' },
     fShipMode: { public: true, type: 'TEXT' },
     fShipDeal: { public: true, type: 'TEXT' },
     fShipAddr0: { public: true, type: 'TEXT' },
     fShipAddr1: { public: true, type: 'TEXT' },
     fShipAddr2: { public: true, type: 'TEXT' },
     fShipAddr3: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fInclVAT: { public: true, type: 'INTEGER' },
     fTotal: { public: true, type: 'FLOAT' },
     fPhone: { public: true, type: 'TEXT' },
     fFax: { public: true, type: 'TEXT' },
     fEmailAddr: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     IntORVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math2',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fOvst: { public: true, type: 'INTEGER' },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fSpec: { public: true, type: 'TEXT' },
           fPrice: { public: true, type: 'FLOAT' },
           fSum: { public: true, type: 'FLOAT' },
           fVATCode: { public: true, type: 'TEXT' },
           fVARList: { public: true, type: 'TEXT' },
           fCostAcc: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fRecepy: { public: true, type: 'TEXT' },
           fShipd1: { public: true, type: 'FLOAT' },
           fShipd2: { public: true, type: 'FLOAT' },
           fPOOrd: { public: true, type: 'FLOAT' },
           fSent: { public: true, type: 'FLOAT' },
           fSerialNr: { public: true, type: 'TEXT' } } },
     fMath: { public: true, type: 'TEXT' },
     fDelAddr3: { public: true, type: 'TEXT' },
     fDelAddr4: { public: true, type: 'TEXT' },
     fXAcceptanceGroup: { public: true, type: 'TEXT' },
     fClosed: { public: true, type: 'INTEGER' },
     fPlanShipDate: { public: true, type: 'DATE' },
     fIntORClass: { public: true, type: 'TEXT' },
     fFrLocation: { public: true, type: 'TEXT' },
     fSalesGroup: { public: true, type: 'TEXT' },
     fAcceptanceStatus: { public: true, type: 'INTEGER' },
     fAcceptanceBy: { public: true, type: 'TEXT' },
     fAcceptanceFYI: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex179: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }