module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fVECode: { public: true, type: 'TEXT' },
     fVEName: { public: true, type: 'TEXT' },
     fOrdDate: { public: true, type: 'DATE' },
     ORProgVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fPrice: { public: true, type: 'FLOAT' },
           fSum: { public: true, type: 'FLOAT' },
           fObjects: { public: true, type: 'TEXT' },
           fBasePrice: { public: true, type: 'FLOAT' },
           fRowGP: { public: true, type: 'FLOAT' },
           fSpec: { public: true, type: 'TEXT' },
           fVATCode: { public: true, type: 'TEXT' },
           fRecepy: { public: true, type: 'TEXT' },
           fPriceFactor: { public: true, type: 'FLOAT' } } },
     fObjects: { public: true, type: 'TEXT' },
     fSalesMan: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fClosed: { public: true, type: 'INTEGER' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fComment: { public: true, type: 'TEXT' },
     fInclVAT: { public: true, type: 'INTEGER' },
     fSum0: { public: true, type: 'FLOAT' },
     fSum1: { public: true, type: 'FLOAT' },
     fSum2: { public: true, type: 'FLOAT' },
     fSum3: { public: true, type: 'FLOAT' },
     fSum4: { public: true, type: 'FLOAT' },
     fLocation: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fTotQty: { public: true, type: 'FLOAT' },
     fTotWeight: { public: true, type: 'FLOAT' },
     fTotVolume: { public: true, type: 'FLOAT' },
     fMaintDate: { public: true, type: 'DATE' },
     fChangedDate: { public: true, type: 'DATE' } },
  indexes: { SerNrIndex410: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }