module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fFromTR: { public: true, type: 'INTEGER' },
     fFromVI: { public: true, type: 'INTEGER' },
     fFromExp: { public: true, type: 'INTEGER' },
     fFromIV: { public: true, type: 'INTEGER' },
     fFromProd: { public: true, type: 'INTEGER' },
     fFromAT2Rev: { public: true, type: 'INTEGER' },
     fFromAT2Wrof: { public: true, type: 'INTEGER' },
     fFromOP: { public: true, type: 'INTEGER' },
     fFromIP: { public: true, type: 'INTEGER' },
     fFromPP: { public: true, type: 'INTEGER' },
     fFromSD: { public: true, type: 'INTEGER' },
     fFromSH: { public: true, type: 'INTEGER' },
     fFromRet: { public: true, type: 'INTEGER' },
     fFromRetPU: { public: true, type: 'INTEGER' },
     fFromPU: { public: true, type: 'INTEGER' },
     fFromCLIn: { public: true, type: 'INTEGER' },
     fFromCLOut: { public: true, type: 'INTEGER' },
     fFromIntIV: { public: true, type: 'INTEGER' },
     fFromSR: { public: true, type: 'INTEGER' } } }