module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fRebArtCode: { public: true, type: 'TEXT' },
     fRebArtName: { public: true, type: 'TEXT' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fPLCode: { public: true, type: 'TEXT' },
     fType: { public: true, type: 'INTEGER' },
     fRebType: { public: true, type: 'INTEGER' },
     fClosed: { public: true, type: 'INTEGER' },
     fLocation: { public: true, type: 'TEXT' },
     fBuyAnyQty: { public: true, type: 'FLOAT' },
     fFixedDiscount: { public: true, type: 'FLOAT' },
     fFixedPrice: { public: true, type: 'FLOAT' },
     MultiBuyRebVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fArtName: { public: true, type: 'TEXT' },
           fBuyQty: { public: true, type: 'FLOAT' },
           fGetQty: { public: true, type: 'FLOAT' },
           fVRebate: { public: true, type: 'FLOAT' },
           fPrice: { public: true, type: 'FLOAT' },
           fRebArtCode: { public: true, type: 'TEXT' },
           fRebArtName: { public: true, type: 'TEXT' } } },
     fAddDiscountToLastRow: { public: true, type: 'INTEGER' } },
  indexes: { CodeIndex720: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }