module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCourseCode: { public: true, type: 'TEXT' },
     fCourseName: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fPerson: { public: true, type: 'TEXT' },
     fPersonName: { public: true, type: 'TEXT' },
     fStartDate: { public: true, type: 'DATE' },
     fStartTime: { public: true, type: 'TIME' },
     fEndDate: { public: true, type: 'DATE' },
     fEndTime: { public: true, type: 'TIME' },
     fNoOfQuestions: { public: true, type: 'INTEGER' },
     fCorrectAnswers: { public: true, type: 'INTEGER' },
     UnivTestAnswerVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fQuestion: { public: true, type: 'TEXT' },
           fAlt1: { public: true, type: 'TEXT' },
           fAlt2: { public: true, type: 'TEXT' },
           fAlt3: { public: true, type: 'TEXT' },
           fAnswer: { public: true, type: 'TEXT' },
           fAlt4: { public: true, type: 'TEXT' },
           fAlt5: { public: true, type: 'TEXT' },
           fAlt6: { public: true, type: 'TEXT' },
           fOrigRowNo: { public: true, type: 'INTEGER' } } },
     fCustCode: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fLastRowUpdated: { public: true, type: 'INTEGER' } },
  indexes: 
   { CustCodeIndex549: 
      { fields: [ 'fCustCode', 'fCourseCode', 'fEndDate', 'fStartTime' ],
        indicesType: 'UNIQUE' } } }