module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     PreQTVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fPrice: { public: true, type: 'FLOAT' },
           fSum: { public: true, type: 'FLOAT' },
           fVRebate: { public: true, type: 'FLOAT' },
           fSalesAcc: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fBasePrice: { public: true, type: 'FLOAT' },
           fRowGP: { public: true, type: 'FLOAT' },
           fVATCode: { public: true, type: 'TEXT' },
           fPriceFactor: { public: true, type: 'FLOAT' },
           fSpec: { public: true, type: 'TEXT' },
           fCustArtCode: { public: true, type: 'TEXT' } } },
     fQTDate: { public: true, type: 'DATE' },
     fCustCode: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fAddr1: { public: true, type: 'TEXT' },
     fAddr2: { public: true, type: 'TEXT' },
     fAddr3: { public: true, type: 'TEXT' },
     fOurContact: { public: true, type: 'TEXT' },
     fCustContact: { public: true, type: 'TEXT' },
     fExportFlag: { public: true, type: 'INTEGER' },
     fPayDeal: { public: true, type: 'TEXT' },
     fCustCat: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fSalesMan: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fClosed: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fRealQTNr: { public: true, type: 'INTEGER' },
     fPriceList: { public: true, type: 'TEXT' },
     fInclVAT: { public: true, type: 'INTEGER' },
     fSum0: { public: true, type: 'FLOAT' },
     fSum1: { public: true, type: 'FLOAT' },
     fSum2: { public: true, type: 'FLOAT' },
     fSum3: { public: true, type: 'FLOAT' },
     fSum4: { public: true, type: 'FLOAT' },
     fQuoteClass: { public: true, type: 'TEXT' },
     fCustVATCode: { public: true, type: 'TEXT' },
     fRebCode: { public: true, type: 'TEXT' },
     fVATNr: { public: true, type: 'TEXT' },
     fPhone: { public: true, type: 'TEXT' },
     fFax: { public: true, type: 'TEXT' },
     fBaseSum4: { public: true, type: 'FLOAT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fDiscPerc: { public: true, type: 'FLOAT' },
     fDiscSum: { public: true, type: 'FLOAT' },
     fTotGP: { public: true, type: 'FLOAT' },
     fSalesGroup: { public: true, type: 'TEXT' },
     fInvAddr3: { public: true, type: 'TEXT' },
     fInvAddr4: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex612: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }