module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fPayVal: { public: true, type: 'FLOAT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fPerson: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     ExpVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fOvst: { public: true, type: 'INTEGER' },
           fAccNumber: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fSum: { public: true, type: 'FLOAT' },
           fItem: { public: true, type: 'TEXT' },
           fQty: { public: true, type: 'FLOAT' },
           fPRCode: { public: true, type: 'TEXT' },
           fVATCode: { public: true, type: 'TEXT' },
           fVATSum: { public: true, type: 'FLOAT' },
           fExpDate: { public: true, type: 'DATE' },
           fDocNr: { public: true, type: 'TEXT' },
           fVECode: { public: true, type: 'TEXT' },
           fWayList: { public: true, type: 'INTEGER' },
           fIdentifier: { public: true, type: 'TEXT' },
           fACShort: { public: true, type: 'TEXT' },
           fVEName: { public: true, type: 'TEXT' },
           fLegalInvNr: { public: true, type: 'TEXT' },
           fTaxAuthID: { public: true, type: 'TEXT' },
           fTaxAuthIDCC: { public: true, type: 'TEXT' },
           fRefStr: { public: true, type: 'TEXT' },
           fPPNr: { public: true, type: 'INTEGER' },
           fPPRow: { public: true, type: 'INTEGER' },
           fBaseSum: { public: true, type: 'FLOAT' },
           fCAE: { public: true, type: 'TEXT' },
           fCAEExpiry: { public: true, type: 'DATE' },
           fDANr: { public: true, type: 'INTEGER' },
           fBankCurncy: { public: true, type: 'TEXT' },
           fFrRateBankVal: { public: true, type: 'FLOAT' },
           fBaseRate1BankVal: { public: true, type: 'FLOAT' },
           fBaseRate2BankVal: { public: true, type: 'FLOAT' },
           fToRateB1BankVal: { public: true, type: 'FLOAT' },
           fToRateB2BankVal: { public: true, type: 'FLOAT' },
           fXBaseSum: { public: true, type: 'TEXT' },
           fBaseVATSum: { public: true, type: 'FLOAT' } } },
     fTransDate: { public: true, type: 'DATE' },
     fOKSign: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fComment: { public: true, type: 'TEXT' },
     fCalcVATVal: { public: true, type: 'FLOAT' },
     fStatFlag: { public: true, type: 'INTEGER' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fPPOKNr: { public: true, type: 'INTEGER' },
     fObjects: { public: true, type: 'TEXT' },
     fSalesGroup: { public: true, type: 'TEXT' },
     fNrofRecs: { public: true, type: 'FLOAT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fDocDate: { public: true, type: 'DATE' },
     fTaxAuthID: { public: true, type: 'TEXT' },
     fTaxAuthIDCC: { public: true, type: 'TEXT' },
     fAcceptanceStatus: { public: true, type: 'INTEGER' },
     fAcceptanceBy: { public: true, type: 'TEXT' },
     fAcceptanceFYI: { public: true, type: 'TEXT' },
     fBasePayVal: { public: true, type: 'FLOAT' },
     fBaseCalcVATVal: { public: true, type: 'FLOAT' } },
  indexes: { SerNrIndex133: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }