module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fAddress0: { public: true, type: 'TEXT' },
     fAddress1: { public: true, type: 'TEXT' },
     fAddress2: { public: true, type: 'TEXT' },
     fNr1: { public: true, type: 'TEXT' },
     fNr2: { public: true, type: 'TEXT' },
     fSWIFT: { public: true, type: 'TEXT' },
     fSorting: { public: true, type: 'TEXT' },
     fSortCode: { public: true, type: 'TEXT' },
     fCorrspAcc: { public: true, type: 'TEXT' },
     fAddress3: { public: true, type: 'TEXT' },
     fAddress4: { public: true, type: 'TEXT' },
     fVATNr: { public: true, type: 'TEXT' },
     fBank: { public: true, type: 'INTEGER' },
     fLangCode: { public: true, type: 'TEXT' },
     fBankIDCode: { public: true, type: 'TEXT' },
     fCountryCode: { public: true, type: 'TEXT' },
     fExchangeRateContract: { public: true, type: 'TEXT' },
     fCustCode: { public: true, type: 'TEXT' },
     fFactoringType: { public: true, type: 'TEXT' },
     fDirectDebitBank: { public: true, type: 'INTEGER' },
     fDirectDebitSorting: { public: true, type: 'TEXT' } },
  indexes: { MainKeyIndex108: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }