module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fBankAcc: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fPayVal: { public: true, type: 'FLOAT' },
     fRegDate: { public: true, type: 'DATE' },
     fTransDate: { public: true, type: 'DATE' },
     fPayMode: { public: true, type: 'TEXT' },
     PPVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fOvst: { public: true, type: 'INTEGER' },
           fPerson: { public: true, type: 'TEXT' },
           fBankAcc: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fPayVal: { public: true, type: 'FLOAT' },
           fObjects: { public: true, type: 'TEXT' },
           fPayMode: { public: true, type: 'TEXT' },
           fChequeNr: { public: true, type: 'INTEGER' },
           fRkPayNumber: { public: true, type: 'TEXT' },
           fExpUsedPayVal: { public: true, type: 'FLOAT' },
           fB1ExpUsedPayVal: { public: true, type: 'FLOAT' },
           fSortCode: { public: true, type: 'TEXT' } } },
     fOrderedFlag: { public: true, type: 'INTEGER' },
     fSentFlag: { public: true, type: 'INTEGER' },
     fDoneFlag: { public: true, type: 'INTEGER' },
     fBankName: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fBasePayVal: { public: true, type: 'FLOAT' },
     fExtraCost: { public: true, type: 'FLOAT' },
     fPayDate: { public: true, type: 'DATE' },
     fXStatFlag: { public: true, type: 'INTEGER' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fPPOKNr: { public: true, type: 'INTEGER' },
     fInvalid: { public: true, type: 'INTEGER' },
     fOSFlag: { public: true, type: 'INTEGER' },
     fSortCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex134: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }