module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fDurTime: { public: true, type: 'TIME' },
     fDurDays: { public: true, type: 'INTEGER' },
     RoutingVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStdOperation: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fSequence: { public: true, type: 'INTEGER' },
           fSubSequence: { public: true, type: 'INTEGER' },
           fSetupTime: { public: true, type: 'TIME' },
           fQueueTime: { public: true, type: 'TIME' },
           fMoveTime: { public: true, type: 'TIME' },
           fRunTime: { public: true, type: 'TIME' },
           fMachine: { public: true, type: 'TEXT' },
           fMachineGroup: { public: true, type: 'TEXT' },
           fMinQty: { public: true, type: 'FLOAT' },
           fOptQty: { public: true, type: 'FLOAT' },
           fMinCoef: { public: true, type: 'FLOAT' },
           fOptCoef: { public: true, type: 'FLOAT' } } },
     fClassification: { public: true, type: 'TEXT' },
     fValidFrom: { public: true, type: 'DATE' },
     fValidTo: { public: true, type: 'DATE' },
     fRegDate: { public: true, type: 'DATE' },
     fLastChangeDate: { public: true, type: 'DATE' },
     fRouteMinQty: { public: true, type: 'FLOAT' },
     fRouteOptQty: { public: true, type: 'FLOAT' },
     fRouteMinCoef: { public: true, type: 'FLOAT' },
     fRouteOptCoef: { public: true, type: 'FLOAT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fClosedFlag: { public: true, type: 'INTEGER' } },
  indexes: { CodeIndex529: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }