module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCustCode: { public: true, type: 'TEXT' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fSignedDate: { public: true, type: 'DATE' },
     fClientContact: { public: true, type: 'TEXT' },
     fOurContact: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fAddr1: { public: true, type: 'TEXT' },
     fAddr2: { public: true, type: 'TEXT' },
     fAddr3: { public: true, type: 'TEXT' },
     fInvAddr3: { public: true, type: 'TEXT' },
     fInvAddr4: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fEMail: { public: true, type: 'TEXT' },
     fPhone: { public: true, type: 'TEXT' },
     fFax: { public: true, type: 'TEXT' },
     fVATNr: { public: true, type: 'TEXT' },
     fMaxUnits: { public: true, type: 'FLOAT' },
     fMaxSales: { public: true, type: 'FLOAT' },
     fMaxCost: { public: true, type: 'FLOAT' },
     AuthCustVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fAuthorisedContact: { public: true, type: 'TEXT' } } } },
  indexes: { CustCodeIndex353: { fields: [ 'fCustCode', 'fStartDate' ], indicesType: 'UNIQUE' } } }