module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fInclVAT: { public: true, type: 'INTEGER' },
     PLDefVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fItemCode: { public: true, type: 'TEXT' },
           fFormula: { public: true, type: 'TEXT' },
           fCodeType: { public: true, type: 'INTEGER' },
           fVATCode: { public: true, type: 'TEXT' },
           fTaxTemplateCode: { public: true, type: 'TEXT' } } },
     fDepPrice: { public: true, type: 'INTEGER' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fPLReplCode: { public: true, type: 'TEXT' },
     fPLBasedOn: { public: true, type: 'INTEGER' },
     fVATCode: { public: true, type: 'TEXT' },
     fBBVECode: { public: true, type: 'TEXT' },
     fBBVarAcc: { public: true, type: 'TEXT' },
     fBBGenTrans: { public: true, type: 'INTEGER' },
     fLengthClass: { public: true, type: 'INTEGER' },
     fStartTime: { public: true, type: 'TIME' },
     fEndTime: { public: true, type: 'TIME' } },
  indexes: { CodeIndex64: { fields: [ 'fCode', 'fStartDate' ], indicesType: 'UNIQUE' } } }