module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fEmployee: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fTrialEndDate: { public: true, type: 'DATE' },
     fJobTitle: { public: true, type: 'TEXT' },
     fSalaryType: { public: true, type: 'INTEGER' },
     fGrossSalary: { public: true, type: 'FLOAT' },
     fSuperior: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fTerminatedFlag: { public: true, type: 'INTEGER' },
     fHRMCOSerNr: { public: true, type: 'INTEGER' },
     fDepCode: { public: true, type: 'TEXT' },
     fClass: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fLeaveScheme: { public: true, type: 'TEXT' },
     fReason: { public: true, type: 'INTEGER' },
     fReasonDetails: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fJobType: { public: true, type: 'INTEGER' },
     fJobHours: { public: true, type: 'FLOAT' },
     fLeaveFwdBal: { public: true, type: 'FLOAT' },
     fLeaveFwdBalDate: { public: true, type: 'DATE' } },
  indexes: { SerNrIndex700: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }