module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fNetVal: { public: true, type: 'FLOAT' },
     fVATVal: { public: true, type: 'FLOAT' },
     fTotal: { public: true, type: 'FLOAT' },
     fTransDate: { public: true, type: 'DATE' },
     fPayMode: { public: true, type: 'TEXT' },
     fPerson: { public: true, type: 'TEXT' },
     fCorspCode: { public: true, type: 'TEXT' },
     fCorspComment: { public: true, type: 'TEXT' },
     fCUCode: { public: true, type: 'TEXT' },
     fCUName: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fAddr1: { public: true, type: 'TEXT' },
     fAddr2: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fVATCode: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fRefStr: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fFileName: { public: true, type: 'TEXT' },
     fFSerNr: { public: true, type: 'INTEGER' },
     fTAX1Sum: { public: true, type: 'FLOAT' },
     fPMObjects: { public: true, type: 'TEXT' },
     fAddr3: { public: true, type: 'TEXT' },
     fAddr4: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fColFlag: { public: true, type: 'INTEGER' },
     fInvalid: { public: true, type: 'INTEGER' },
     fARonTR: { public: true, type: 'INTEGER' },
     fPPOKNr: { public: true, type: 'INTEGER' },
     fOfficialSerNr: { public: true, type: 'TEXT' },
     fTAX2Sum: { public: true, type: 'FLOAT' },
     CLInVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fType: { public: true, type: 'INTEGER' },
           fCompany: { public: true, type: 'TEXT' },
           fTransNr: { public: true, type: 'INTEGER' },
           fSum: { public: true, type: 'FLOAT' },
           fObjects: { public: true, type: 'TEXT' },
           fOrderNr: { public: true, type: 'INTEGER' },
           fCorspCode: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fStp: { public: true, type: 'INTEGER' },
           fTAX1Sum: { public: true, type: 'FLOAT' },
           fTAX2Sum: { public: true, type: 'FLOAT' },
           fARAPAcc: { public: true, type: 'TEXT' },
           fPayMode: { public: true, type: 'TEXT' },
           fTransOfficialSerNr: { public: true, type: 'TEXT' } } },
     fSalesGroup: { public: true, type: 'TEXT' },
     fOfficialSerNrSerie: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex46: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }