module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fSDate: { public: true, type: 'DATE' },
     fEDate: { public: true, type: 'DATE' },
     fCarCode: { public: true, type: 'TEXT' },
     fCarName: { public: true, type: 'TEXT' },
     fCarNumber: { public: true, type: 'TEXT' },
     fDriver: { public: true, type: 'TEXT' },
     fUsedBy: { public: true, type: 'TEXT' },
     fPetroilCode: { public: true, type: 'TEXT' },
     fNormAmount: { public: true, type: 'FLOAT' },
     fRealAmount: { public: true, type: 'FLOAT' },
     fStkm: { public: true, type: 'FLOAT' },
     fEndkm: { public: true, type: 'FLOAT' },
     fPurposeCode: { public: true, type: 'TEXT' },
     fPurpose: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fObjects: { public: true, type: 'TEXT' },
     fTotalkm: { public: true, type: 'FLOAT' },
     fTotall: { public: true, type: 'FLOAT' },
     fCostPerkm: { public: true, type: 'FLOAT' },
     fTotalCost: { public: true, type: 'FLOAT' },
     WayListVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fWDate: { public: true, type: 'DATE' },
           fWDistCode: { public: true, type: 'TEXT' },
           fWComment: { public: true, type: 'TEXT' },
           fWSTime: { public: true, type: 'TIME' },
           fWETime: { public: true, type: 'TIME' },
           fWDistVal: { public: true, type: 'FLOAT' },
           fStkm: { public: true, type: 'FLOAT' },
           fEndkm: { public: true, type: 'FLOAT' },
           fCUCode: { public: true, type: 'TEXT' },
           fCUName: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fPRCode: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' } } },
     fPRCode: { public: true, type: 'TEXT' },
     fWSTime1: { public: true, type: 'TIME' },
     fWETime1: { public: true, type: 'TIME' },
     fWDistVal: { public: true, type: 'FLOAT' },
     fWDistCode: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex313: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }