module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fCUCode: { public: true, type: 'TEXT' },
     fCUName: { public: true, type: 'TEXT' },
     fIntCode: { public: true, type: 'TEXT' },
     fMainAcc: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fLimit: { public: true, type: 'FLOAT' },
     fExtraLimit: { public: true, type: 'FLOAT' },
     CuAccVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fPlanDate: { public: true, type: 'DATE' },
           fInvNr: { public: true, type: 'INTEGER' },
           fValStr: { public: true, type: 'TEXT' },
           fPerson: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' } } },
     fInstNr: { public: true, type: 'FLOAT' },
     fClosed: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fLoanStatus: { public: true, type: 'TEXT' },
     fLoanSuccess: { public: true, type: 'TEXT' } },
  indexes: { CodeIndex56: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }