module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fReportType: { public: true, type: 'INTEGER' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fPeriodType: { public: true, type: 'INTEGER' },
     fExported: { public: true, type: 'INTEGER' },
     VATDeclVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fElementCode: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fValue: { public: true, type: 'TEXT' } } },
     fTaxRepCode: { public: true, type: 'TEXT' },
     fTaxServID: { public: true, type: 'TEXT' },
     fTaxServStatus: { public: true, type: 'INTEGER' },
     fShortname: { public: true, type: 'TEXT' } },
  indexes: { CodeIndex810: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }