module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     ResUsageVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fCodeType: { public: true, type: 'INTEGER' },
           fAddPer: { public: true, type: 'INTEGER' },
           fMessageToHK: { public: true, type: 'TEXT' },
           fOBType: { public: true, type: 'TEXT' },
           fDescription: { public: true, type: 'TEXT' } } },
     fMessCkIn: { public: true, type: 'TEXT' },
     fMessCkOut: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fXCommentToInv: { public: true, type: 'TEXT' },
     fAddDateToMatrix: { public: true, type: 'INTEGER' },
     fXNoAdditionalToInv: { public: true, type: 'TEXT' },
     fAddItemIncPrice: { public: true, type: 'INTEGER' },
     fAddNegateItems: { public: true, type: 'INTEGER' },
     fNegateComment: { public: true, type: 'TEXT' },
     fDontShowOnWeb: { public: true, type: 'INTEGER' },
     fType: { public: true, type: 'TEXT' } },
  indexes: { CodeIndex291: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }