module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fTrSkipObj: { public: true, type: 'INTEGER' },
     fTrSkipCom: { public: true, type: 'INTEGER' },
     fTrDoNVTest: { public: true, type: 'INTEGER' },
     fTrDemandSign2: { public: true, type: 'INTEGER' },
     fAutoVATflag: { public: true, type: 'INTEGER' },
     fAutoVATVal: { public: true, type: 'FLOAT' },
     fTransferItems: { public: true, type: 'INTEGER' },
     fFullQtyTrans: { public: true, type: 'INTEGER' },
     fRequireRcvDate: { public: true, type: 'INTEGER' },
     fCalcWithholdingTax: { public: true, type: 'INTEGER' },
     fVIBasedOnPU: { public: true, type: 'INTEGER' },
     fDisallowInvDateAfterTransDate: { public: true, type: 'INTEGER' },
     fVIFromPORate: { public: true, type: 'INTEGER' } } }