module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fClosed: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fCreateDate: { public: true, type: 'DATE' },
     fOKDate: { public: true, type: 'DATE' },
     fSign: { public: true, type: 'TEXT' },
     fDateChanged: { public: true, type: 'DATE' },
     ProdPlanVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fItemCode: { public: true, type: 'TEXT' },
           fSpec: { public: true, type: 'TEXT' },
           fSugQty: { public: true, type: 'FLOAT' },
           fQty: { public: true, type: 'FLOAT' },
           fProdPlanRow: { public: true, type: 'INTEGER' },
           fRecipe: { public: true, type: 'TEXT' },
           fAboveRecipeRow: { public: true, type: 'INTEGER' },
           fProdOrder: { public: true, type: 'INTEGER' },
           fSugQtyDate: { public: true, type: 'DATE' },
           fAdjQtyDate: { public: true, type: 'DATE' },
           fProdDays: { public: true, type: 'FLOAT' },
           fProdStartDate: { public: true, type: 'DATE' },
           fNeededDate: { public: true, type: 'DATE' } } },
     fEarliestProdDate: { public: true, type: 'DATE' } },
  indexes: { SerNrIndex518: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }