module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fTransTime: { public: true, type: 'TIME' },
     fCloudWatchpointNr: { public: true, type: 'INTEGER' },
     fContactCode: { public: true, type: 'TEXT' },
     fContactName: { public: true, type: 'TEXT' },
     fMobile: { public: true, type: 'TEXT' },
     fController: { public: true, type: 'TEXT' },
     fRemoteCloudServer: { public: true, type: 'TEXT' },
     fServerName: { public: true, type: 'TEXT' },
     fDurStatus: { public: true, type: 'INTEGER' },
     fLastSendDate: { public: true, type: 'DATE' },
     fLastSendTime: { public: true, type: 'TIME' },
     fRepeatInterval: { public: true, type: 'TIME' },
     SWMVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fContactCode: { public: true, type: 'TEXT' },
           fMobile: { public: true, type: 'TEXT' },
           fContactStatus: { public: true, type: 'INTEGER' },
           fNotifCnt: { public: true, type: 'INTEGER' },
           fNotifLevel: { public: true, type: 'INTEGER' } } },
     fInfo: { public: true, type: 'TEXT' },
     fSolvedBy: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex768: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }