module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fRegDate: { public: true, type: 'DATE' },
     fTransDate: { public: true, type: 'DATE' },
     fSellUserCode: { public: true, type: 'TEXT' },
     fSellName: { public: true, type: 'TEXT' },
     fBuyUserCode: { public: true, type: 'TEXT' },
     fBuyName: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fTotQty: { public: true, type: 'FLOAT' },
     fTotSum: { public: true, type: 'FLOAT' },
     SharesTranVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fQty: { public: true, type: 'FLOAT' },
           fFromSerNo: { public: true, type: 'TEXT' },
           fToSerNo: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fPrice: { public: true, type: 'FLOAT' },
           fSum: { public: true, type: 'FLOAT' },
           fNominalValue: { public: true, type: 'FLOAT' },
           fOfficialValue: { public: true, type: 'FLOAT' },
           fSharePremium: { public: true, type: 'FLOAT' } } },
     fType: { public: true, type: 'INTEGER' },
     fTransTime: { public: true, type: 'TIME' } },
  indexes: { SerNrIndex466: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }