module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fDescription: { public: true, type: 'TEXT' },
     fATClass: { public: true, type: 'TEXT' },
     fOwner: { public: true, type: 'TEXT' },
     fDepartment: { public: true, type: 'TEXT' },
     fSerialNo: { public: true, type: 'TEXT' },
     fPurchaseDate: { public: true, type: 'DATE' },
     fComment: { public: true, type: 'TEXT' },
     fBookedDepr: { public: true, type: 'FLOAT' },
     fPurchVal: { public: true, type: 'FLOAT' },
     fEndDate: { public: true, type: 'DATE' },
     fVECode: { public: true, type: 'TEXT' },
     fVEName: { public: true, type: 'TEXT' },
     fInsuranceVal: { public: true, type: 'FLOAT' },
     fStockDate: { public: true, type: 'DATE' },
     fQuantity: { public: true, type: 'FLOAT' },
     ATVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStartDate: { public: true, type: 'DATE' },
           fModel1: { public: true, type: 'TEXT' },
           fModel2: { public: true, type: 'TEXT' },
           fStartVal: { public: true, type: 'FLOAT' },
           fStartVal2: { public: true, type: 'FLOAT' },
           fComment: { public: true, type: 'TEXT' },
           fDeprVal: { public: true, type: 'FLOAT' },
           fDeprVal2: { public: true, type: 'FLOAT' } } },
     fSalesVal: { public: true, type: 'FLOAT' },
     fFinalDeprVal: { public: true, type: 'FLOAT' },
     fObjects: { public: true, type: 'TEXT' },
     fInactive: { public: true, type: 'INTEGER' },
     fInitDeprVal: { public: true, type: 'FLOAT' },
     fInitDepr2Val: { public: true, type: 'FLOAT' },
     fProdDate: { public: true, type: 'DATE' } },
  indexes: { CodeIndex142: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }