module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fIntRate: { public: true, type: 'FLOAT' },
     fMinInt: { public: true, type: 'FLOAT' },
     fMinDays: { public: true, type: 'INTEGER' },
     fPayDeal: { public: true, type: 'TEXT' },
     fX1: { public: true, type: 'TEXT' },
     fX2: { public: true, type: 'TEXT' },
     fIntModel: { public: true, type: 'INTEGER' },
     fInt2Model: { public: true, type: 'INTEGER' },
     fArtCode: { public: true, type: 'TEXT' },
     fInclNotDue: { public: true, type: 'INTEGER' },
     fFeeItem: { public: true, type: 'TEXT' },
     fIncreaseRem: { public: true, type: 'INTEGER' },
     fIntCode: { public: true, type: 'TEXT' },
     fIncLeapYear: { public: true, type: 'INTEGER' } } }