module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fPayDate: { public: true, type: 'DATE' },
     fPlanPayDate: { public: true, type: 'DATE' },
     fAgreedPayDate: { public: true, type: 'DATE' },
     fCompCode: { public: true, type: 'TEXT' },
     fCompName: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fTransNr: { public: true, type: 'INTEGER' },
     fFileName: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fSum: { public: true, type: 'FLOAT' },
     fBaseSum: { public: true, type: 'FLOAT' },
     fClosed: { public: true, type: 'INTEGER' },
     fApproved: { public: true, type: 'INTEGER' },
     fPaid: { public: true, type: 'INTEGER' },
     fPriority: { public: true, type: 'TEXT' },
     fTransRow: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex825: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }