module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCurncyCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fXRndTotal: { public: true, type: 'INTEGER' },
     fDefaultFrom: { public: true, type: 'FLOAT' },
     fDefaultTo1: { public: true, type: 'FLOAT' },
     fDefaultTo2: { public: true, type: 'FLOAT' },
     fMaxFrom: { public: true, type: 'FLOAT' },
     fMaxTo1: { public: true, type: 'FLOAT' },
     fMaxTo2: { public: true, type: 'FLOAT' },
     fMinFrom: { public: true, type: 'FLOAT' },
     fMinTo1: { public: true, type: 'FLOAT' },
     fMinTo2: { public: true, type: 'FLOAT' },
     fCurText: { public: true, type: 'TEXT' },
     fMinorCurText: { public: true, type: 'TEXT' },
     fNoChangeBase: { public: true, type: 'INTEGER' },
     fNoChangeForeign: { public: true, type: 'INTEGER' },
     fEMUCurncy: { public: true, type: 'INTEGER' },
     fEMUDate: { public: true, type: 'DATE' },
     fAutoRoundof: { public: true, type: 'FLOAT' },
     fAutoWriteof: { public: true, type: 'FLOAT' },
     fCurText1: { public: true, type: 'TEXT' },
     fCurText2: { public: true, type: 'TEXT' },
     fMinorCurText1: { public: true, type: 'TEXT' },
     fMinorCurText2: { public: true, type: 'TEXT' },
     fCurGender: { public: true, type: 'INTEGER' },
     fMinorCurGender: { public: true, type: 'INTEGER' },
     fXRoundLines: { public: true, type: 'INTEGER' },
     fXRoundVAT: { public: true, type: 'INTEGER' },
     fTaxOfficeCode: { public: true, type: 'TEXT' },
     CurncyCodeVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fLangCode: { public: true, type: 'TEXT' },
           fRowCurText: { public: true, type: 'TEXT' },
           fRowCurText1: { public: true, type: 'TEXT' },
           fRowCurText2: { public: true, type: 'TEXT' },
           fRowMinorCurText: { public: true, type: 'TEXT' },
           fRowMinorCurText1: { public: true, type: 'TEXT' },
           fRowMinorCurText2: { public: true, type: 'TEXT' },
           fRowCurGender: { public: true, type: 'INTEGER' },
           fRowMinorCurGender: { public: true, type: 'INTEGER' } } } },
  indexes: { MainKeyIndex164: { fields: [ 'fCurncyCode' ], indicesType: 'UNIQUE' } } }