module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerialNr: { public: true, type: 'TEXT' },
     fItemCode: { public: true, type: 'TEXT' },
     fItemName: { public: true, type: 'TEXT' },
     fCustCode: { public: true, type: 'TEXT' },
     fCustName: { public: true, type: 'TEXT' },
     fXInStock: { public: true, type: 'FLOAT' },
     fSalesPrice: { public: true, type: 'FLOAT' },
     fCostPrice: { public: true, type: 'FLOAT' },
     fSoldDate: { public: true, type: 'DATE' },
     fWarrantyUntil: { public: true, type: 'DATE' },
     fMotherNr: { public: true, type: 'TEXT' },
     fVECode: { public: true, type: 'TEXT' },
     fContract: { public: true, type: 'INTEGER' },
     fChildCONr: { public: true, type: 'INTEGER' },
     SVOSerVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fPartNumber: { public: true, type: 'TEXT' },
           fPartWarranty: { public: true, type: 'TEXT' },
           fCoverageRefNo: { public: true, type: 'TEXT' },
           fPartError: { public: true, type: 'TEXT' },
           fStockPrice: { public: true, type: 'FLOAT' },
           fExchangePrice: { public: true, type: 'FLOAT' },
           fEEECode: { public: true, type: 'TEXT' },
           fIsSerialized: { public: true, type: 'TEXT' },
           fLaborTier: { public: true, type: 'TEXT' },
           fPartDescription: { public: true, type: 'TEXT' },
           fPartType: { public: true, type: 'TEXT' },
           fComponentCode: { public: true, type: 'TEXT' },
           fOriginalPartNumber: { public: true, type: 'TEXT' } } },
     fWarrantyStatus: { public: true, type: 'TEXT' },
     fCoverageStartDate: { public: true, type: 'DATE' },
     fEstimatedPurchaseDate: { public: true, type: 'DATE' },
     fGlobalWarranty: { public: true, type: 'INTEGER' },
     fOnsiteStartDate: { public: true, type: 'DATE' },
     fOnsiteEndDate: { public: true, type: 'DATE' },
     fPurchaseCountry: { public: true, type: 'TEXT' },
     fRegistrationDate: { public: true, type: 'DATE' },
     fImageURL: { public: true, type: 'TEXT' },
     fExplodedViewURL: { public: true, type: 'TEXT' },
     fManualURL: { public: true, type: 'TEXT' },
     fProductDescription: { public: true, type: 'TEXT' },
     fConfigDescription: { public: true, type: 'TEXT' },
     fSLAGroupDesc: { public: true, type: 'TEXT' },
     fPowerTrainFlag: { public: true, type: 'INTEGER' },
     fTriCareFlag: { public: true, type: 'INTEGER' },
     fEcorathFlag: { public: true, type: 'INTEGER' },
     fContractCoverageEndDate: { public: true, type: 'DATE' },
     fContractCoverageStartDate: { public: true, type: 'DATE' },
     fContractType: { public: true, type: 'TEXT' },
     fLaborCovered: { public: true, type: 'INTEGER' },
     fLimitedWarranty: { public: true, type: 'INTEGER' },
     fPartCovered: { public: true, type: 'INTEGER' },
     fCSCode: { public: true, type: 'TEXT' },
     fCSType: { public: true, type: 'TEXT' },
     fPersonalized: { public: true, type: 'INTEGER' },
     fLastGSXQuery: { public: true, type: 'DATE' },
     fWarrantyRefNo: { public: true, type: 'TEXT' },
     fCoverageEndDate: { public: true, type: 'DATE' },
     fAPPAgreementNumber: { public: true, type: 'TEXT' },
     fAPPTotalFromOrder: { public: true, type: 'TEXT' },
     fAPPCoverageDurationStatement: { public: true, type: 'TEXT' },
     fSecondarySerialNr: { public: true, type: 'TEXT' },
     fAlternateDeviceID: { public: true, type: 'TEXT' } },
  indexes: { MainKeyIndex188: { fields: [ 'fSerialNr', 'fItemCode' ], indicesType: 'UNIQUE' } } }