module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fUserStr01: { public: true, type: 'TEXT' },
     fUserStr02: { public: true, type: 'TEXT' },
     fUserStr03: { public: true, type: 'TEXT' },
     fUserStr04: { public: true, type: 'TEXT' },
     fUserStr05: { public: true, type: 'TEXT' },
     fUserStr06: { public: true, type: 'TEXT' },
     fUserStr07: { public: true, type: 'TEXT' },
     fUserStr08: { public: true, type: 'TEXT' },
     fUserStr09: { public: true, type: 'TEXT' },
     fUserStr10: { public: true, type: 'TEXT' },
     fUserStr11: { public: true, type: 'TEXT' },
     fUserStr12: { public: true, type: 'TEXT' },
     fUserStr13: { public: true, type: 'TEXT' },
     fUserStr14: { public: true, type: 'TEXT' },
     fUserStr15: { public: true, type: 'TEXT' },
     fUserStr16: { public: true, type: 'TEXT' },
     fUserStr17: { public: true, type: 'TEXT' },
     fUserStr18: { public: true, type: 'TEXT' },
     fUserStr19: { public: true, type: 'TEXT' },
     fUserStr20: { public: true, type: 'TEXT' } } }