module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fInStock: { public: true, type: 'INTEGER' },
     fOrddOut: { public: true, type: 'INTEGER' },
     fPOQty: { public: true, type: 'INTEGER' },
     fShpble: { public: true, type: 'INTEGER' },
     fNotRsrvd: { public: true, type: 'INTEGER' },
     fGP: { public: true, type: 'INTEGER' },
     fGPPrc: { public: true, type: 'INTEGER' },
     fDiscUPr: { public: true, type: 'INTEGER' },
     fInstock2: { public: true, type: 'INTEGER' },
     fVar: { public: true, type: 'INTEGER' },
     fLeadDate: { public: true, type: 'INTEGER' },
     fStatf: { public: true, type: 'INTEGER' },
     fLoc: { public: true, type: 'INTEGER' },
     fInPrice: { public: true, type: 'INTEGER' } } }