module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fDefCustCat: { public: true, type: 'TEXT' },
     fDefPayDeal: { public: true, type: 'TEXT' },
     fNoLetterPosting: { public: true, type: 'INTEGER' },
     fNoMailPosting: { public: true, type: 'INTEGER' },
     fOnAccount: { public: true, type: 'INTEGER' },
     fAllowLogin: { public: true, type: 'INTEGER' },
     fDemandCustomerCategory: { public: true, type: 'INTEGER' },
     fShowRegNr1notVATNr: { public: true, type: 'INTEGER' },
     fDontUseAddrLookup: { public: true, type: 'INTEGER' },
     fRegion: { public: true, type: 'TEXT' },
     fCreditLimit: { public: true, type: 'FLOAT' },
     fCreditLimitDays: { public: true, type: 'INTEGER' },
     fCurrentUserasSalesman: { public: true, type: 'INTEGER' },
     fDemandVATRegNo: { public: true, type: 'INTEGER' },
     fSalesOTCode: { public: true, type: 'TEXT' },
     fPurchOTCode: { public: true, type: 'TEXT' },
     fAutSalesObject: { public: true, type: 'INTEGER' },
     fAutPurchObject: { public: true, type: 'INTEGER' } } }