module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fCOSerNr: { public: true, type: 'INTEGER' },
     fCOChildNr: { public: true, type: 'INTEGER' },
     fCQSerNr: { public: true, type: 'INTEGER' },
     fCQVersion: { public: true, type: 'INTEGER' },
     fCustCode: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fASoldDate: { public: true, type: 'DATE' },
     fASignedDate: { public: true, type: 'DATE' },
     fADelAcceptDate: { public: true, type: 'DATE' },
     fAInsuranceDate: { public: true, type: 'DATE' },
     fATransNotDate: { public: true, type: 'DATE' },
     fAFundinDate: { public: true, type: 'DATE' },
     fACreditDate: { public: true, type: 'DATE' },
     fAQAcceptDate: { public: true, type: 'DATE' },
     fSSoldDate: { public: true, type: 'DATE' },
     fSSignedDate: { public: true, type: 'DATE' },
     fSDelAcceptDate: { public: true, type: 'DATE' },
     fSInsuranceDate: { public: true, type: 'DATE' },
     fSTransNotDate: { public: true, type: 'DATE' },
     fSFundinDate: { public: true, type: 'DATE' },
     fSCreditDate: { public: true, type: 'DATE' },
     fSQAcceptDate: { public: true, type: 'DATE' },
     fSoldOK: { public: true, type: 'INTEGER' },
     fSignedOK: { public: true, type: 'INTEGER' },
     fDelAcceptOK: { public: true, type: 'INTEGER' },
     fInsuranceOK: { public: true, type: 'INTEGER' },
     fTransNotOK: { public: true, type: 'INTEGER' },
     fFundinOK: { public: true, type: 'INTEGER' },
     fCreditOK: { public: true, type: 'INTEGER' },
     fQAcceptOK: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex131: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }