module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fCustID: { public: true, type: 'TEXT' },
     fVESerNr: { public: true, type: 'INTEGER' },
     fVersionNr: { public: true, type: 'INTEGER' },
     fInvDate: { public: true, type: 'DATE' },
     fCustCode: { public: true, type: 'TEXT' },
     fPayDate: { public: true, type: 'DATE' },
     fAddr0: { public: true, type: 'TEXT' },
     fAddr1: { public: true, type: 'TEXT' },
     fAddr2: { public: true, type: 'TEXT' },
     fAddr3: { public: true, type: 'TEXT' },
     fOurContact: { public: true, type: 'TEXT' },
     fClientContact: { public: true, type: 'TEXT' },
     fExportFlag: { public: true, type: 'INTEGER' },
     fPayDeal: { public: true, type: 'TEXT' },
     fOrderNr: { public: true, type: 'INTEGER' },
     fPrntdf: { public: true, type: 'INTEGER' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fPdays: { public: true, type: 'INTEGER' },
     fPdvrebt: { public: true, type: 'FLOAT' },
     fPdrdays: { public: true, type: 'INTEGER' },
     fPdComment: { public: true, type: 'TEXT' },
     fInvType: { public: true, type: 'INTEGER' },
     fInclVAT: { public: true, type: 'INTEGER' },
     fInvComment: { public: true, type: 'TEXT' },
     fCredInv: { public: true, type: 'INTEGER' },
     fCredMark: { public: true, type: 'TEXT' },
     fSalesMan: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fFrPrice: { public: true, type: 'FLOAT' },
     fFrBase: { public: true, type: 'FLOAT' },
     fFrItem: { public: true, type: 'TEXT' },
     fFrVATCode: { public: true, type: 'TEXT' },
     fOrgCust: { public: true, type: 'TEXT' },
     fSum0: { public: true, type: 'FLOAT' },
     fSum1: { public: true, type: 'FLOAT' },
     fSum2: { public: true, type: 'FLOAT' },
     fSum3: { public: true, type: 'FLOAT' },
     fSum4: { public: true, type: 'FLOAT' },
     fVATNr: { public: true, type: 'TEXT' },
     fShipAddr0: { public: true, type: 'TEXT' },
     fShipAddr1: { public: true, type: 'TEXT' },
     fShipAddr2: { public: true, type: 'TEXT' },
     fShipAddr3: { public: true, type: 'TEXT' },
     fTAX1Sum: { public: true, type: 'FLOAT' },
     fCalcFinRef: { public: true, type: 'TEXT' },
     fPhone: { public: true, type: 'TEXT' },
     fFax: { public: true, type: 'TEXT' },
     fCustOrdNr: { public: true, type: 'TEXT' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fBaseSum4: { public: true, type: 'FLOAT' },
     fInvoiceNr: { public: true, type: 'TEXT' },
     fSVONr: { public: true, type: 'INTEGER' },
     fOfficialSerNr: { public: true, type: 'TEXT' },
     fLegalInvNr: { public: true, type: 'TEXT' },
     fTotQty: { public: true, type: 'FLOAT' },
     fTotWeight: { public: true, type: 'FLOAT' },
     fTotVolume: { public: true, type: 'FLOAT' },
     fInvAddr3: { public: true, type: 'TEXT' },
     fInvAddr4: { public: true, type: 'TEXT' },
     fDelAddr3: { public: true, type: 'TEXT' },
     fDelAddr4: { public: true, type: 'TEXT' },
     fDelAddrCode: { public: true, type: 'TEXT' },
     fQTNr: { public: true, type: 'INTEGER' },
     fFiscalFlag: { public: true, type: 'INTEGER' },
     fJobNr: { public: true, type: 'INTEGER' },
     fTransTime: { public: true, type: 'TIME' },
     fStatVal: { public: true, type: 'FLOAT' },
     fEInvExpFlag: { public: true, type: 'INTEGER' },
     fEInvExpDate: { public: true, type: 'DATE' },
     fServiceDelDate: { public: true, type: 'DATE' },
     fRegion: { public: true, type: 'TEXT' },
     fRefStr: { public: true, type: 'TEXT' },
     fTAX2Sum: { public: true, type: 'FLOAT' },
     fPdvrebt2: { public: true, type: 'FLOAT' },
     fPdrdays2: { public: true, type: 'INTEGER' },
     fNoTax1: { public: true, type: 'INTEGER' },
     fNoTax2: { public: true, type: 'INTEGER' },
     fRegInCountry: { public: true, type: 'INTEGER' },
     fVEVATNr: { public: true, type: 'TEXT' },
     fVERegNr1: { public: true, type: 'TEXT' },
     fVERegNr2: { public: true, type: 'TEXT' },
     TXIVVIVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fPrice: { public: true, type: 'FLOAT' },
           fSum: { public: true, type: 'FLOAT' },
           fVRebate: { public: true, type: 'FLOAT' },
           fOrdRow: { public: true, type: 'INTEGER' },
           fSpec: { public: true, type: 'TEXT' },
           fVATCode: { public: true, type: 'TEXT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fPriceFactor: { public: true, type: 'FLOAT' },
           fCUPNr: { public: true, type: 'INTEGER' },
           fExciseNr: { public: true, type: 'TEXT' },
           fPeriodCode: { public: true, type: 'TEXT' },
           fVECode: { public: true, type: 'TEXT' },
           fGCNr: { public: true, type: 'INTEGER' },
           fCustOrdNr: { public: true, type: 'TEXT' },
           fRepaExVAT: { public: true, type: 'FLOAT' },
           fTAX2Code: { public: true, type: 'TEXT' },
           fTAX2Prc: { public: true, type: 'FLOAT' },
           fTAX2Reb: { public: true, type: 'FLOAT' },
           fTAX1Reb: { public: true, type: 'FLOAT' } } },
     fNoTAXonVAT: { public: true, type: 'INTEGER' },
     fTotalwoTAX: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex492: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }