module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fMerchantID: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fLocalMachineCode: { public: true, type: 'TEXT' },
     fType: { public: true, type: 'INTEGER' },
     fAccountRef: { public: true, type: 'TEXT' },
     fRefundPW: { public: true, type: 'TEXT' },
     fTestAddress: { public: true, type: 'INTEGER' },
     fKEY: { public: true, type: 'TEXT' },
     fSerialNr: { public: true, type: 'TEXT' },
     fTerminalID: { public: true, type: 'TEXT' },
     fDuplicateTime: { public: true, type: 'INTEGER' },
     fSendDelInfof: { public: true, type: 'INTEGER' },
     fSendInvInfof: { public: true, type: 'INTEGER' },
     fSendCorpInfof: { public: true, type: 'INTEGER' },
     fKEY2: { public: true, type: 'TEXT' },
     fProfileID: { public: true, type: 'TEXT' },
     fAccessKey: { public: true, type: 'TEXT' },
     fKeyCreatedDate: { public: true, type: 'DATE' },
     fKeyExpireDate: { public: true, type: 'DATE' },
     fURL: { public: true, type: 'TEXT' } },
  indexes: 
   { CodeIndex503: 
      { fields: [ 'fCode', 'fType', 'fLocalMachineCode' ],
        indicesType: 'UNIQUE' } } }