module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fVECode: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fPayDeal: { public: true, type: 'TEXT' },
     fExportFlag: { public: true, type: 'INTEGER' },
     fAddr0: { public: true, type: 'TEXT' },
     fAddr1: { public: true, type: 'TEXT' },
     fAddr2: { public: true, type: 'TEXT' },
     fAddr3: { public: true, type: 'TEXT' },
     fShipAddr0: { public: true, type: 'TEXT' },
     fShipAddr1: { public: true, type: 'TEXT' },
     fShipAddr2: { public: true, type: 'TEXT' },
     fShipAddr3: { public: true, type: 'TEXT' },
     fVEContact: { public: true, type: 'TEXT' },
     fOurContact: { public: true, type: 'TEXT' },
     fShipMode: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fPlanShip: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fShipDeal: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fOrdNr: { public: true, type: 'INTEGER' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fClosed: { public: true, type: 'INTEGER' },
     fCostPerUnit: { public: true, type: 'FLOAT' },
     fSum0: { public: true, type: 'FLOAT' },
     fSum1: { public: true, type: 'FLOAT' },
     fSum2: { public: true, type: 'FLOAT' },
     fSum3: { public: true, type: 'FLOAT' },
     fSum4: { public: true, type: 'FLOAT' },
     POQTVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fOvst: { public: true, type: 'INTEGER' },
           fVEArtCode: { public: true, type: 'TEXT' },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fSpec: { public: true, type: 'TEXT' },
           fPrice: { public: true, type: 'FLOAT' },
           fSum: { public: true, type: 'FLOAT' },
           fVRebate: { public: true, type: 'FLOAT' },
           fVATCode: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fVEQuant: { public: true, type: 'FLOAT' },
           fPIFactor: { public: true, type: 'FLOAT' },
           fPriceFactor: { public: true, type: 'FLOAT' },
           fVARList: { public: true, type: 'TEXT' },
           fPRCode: { public: true, type: 'TEXT' },
           fWSNr: { public: true, type: 'INTEGER' },
           fCostAcc: { public: true, type: 'TEXT' },
           fRentSerialNr: { public: true, type: 'TEXT' },
           fTAX2Code: { public: true, type: 'TEXT' },
           fTAX2Prc: { public: true, type: 'FLOAT' },
           fTAX2Reb: { public: true, type: 'FLOAT' },
           fTAX1Reb: { public: true, type: 'FLOAT' },
           fTAX2Acc: { public: true, type: 'TEXT' },
           fStockType: { public: true, type: 'INTEGER' },
           fUnitCode: { public: true, type: 'TEXT' },
           fVEUnit: { public: true, type: 'TEXT' },
           fPalletNr: { public: true, type: 'FLOAT' },
           fCustomsCost: { public: true, type: 'FLOAT' } } },
     fPRCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fInclVAT: { public: true, type: 'INTEGER' },
     fLocation: { public: true, type: 'TEXT' },
     fVEFactoring: { public: true, type: 'TEXT' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fWONr: { public: true, type: 'INTEGER' },
     fObjects: { public: true, type: 'TEXT' },
     fReference: { public: true, type: 'TEXT' },
     fSalesMan: { public: true, type: 'TEXT' },
     fPONr: { public: true, type: 'INTEGER' },
     fPOClass: { public: true, type: 'TEXT' },
     fPOCQStatNr: { public: true, type: 'INTEGER' },
     fInvAddr3: { public: true, type: 'TEXT' },
     fInvAddr4: { public: true, type: 'TEXT' },
     fDelAddr3: { public: true, type: 'TEXT' },
     fDelAddr4: { public: true, type: 'TEXT' },
     fPOCOSerNr: { public: true, type: 'INTEGER' },
     fPlanShipDate: { public: true, type: 'DATE' },
     fTAX1Sum: { public: true, type: 'FLOAT' },
     fTAX2Sum: { public: true, type: 'FLOAT' },
     fBranchID: { public: true, type: 'TEXT' },
     fNoTAXonVAT: { public: true, type: 'INTEGER' },
     fRebCode: { public: true, type: 'TEXT' },
     fVEVATCode: { public: true, type: 'TEXT' },
     fSalesGroup: { public: true, type: 'TEXT' },
     fInvoiceToCode: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex63: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }