module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fUserCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fClosedFlag: { public: true, type: 'INTEGER' },
     fMGroups: { public: true, type: 'TEXT' },
     fNewPlanFlag: { public: true, type: 'INTEGER' },
     fRecalcPlanFlag: { public: true, type: 'INTEGER' },
     fChangeOpFlag: { public: true, type: 'INTEGER' },
     fChangeRouteFlag: { public: true, type: 'INTEGER' },
     fChWeek1Flag: { public: true, type: 'INTEGER' },
     fChWeek2Flag: { public: true, type: 'INTEGER' },
     fChWeek3Flag: { public: true, type: 'INTEGER' },
     fChWeek4Flag: { public: true, type: 'INTEGER' },
     fChWeek5Flag: { public: true, type: 'INTEGER' },
     fChWeek6Flag: { public: true, type: 'INTEGER' },
     fChWeek7Flag: { public: true, type: 'INTEGER' },
     fChWeek8Flag: { public: true, type: 'INTEGER' },
     fChWeek9Flag: { public: true, type: 'INTEGER' },
     fChWeek10Flag: { public: true, type: 'INTEGER' },
     fChWeek11Flag: { public: true, type: 'INTEGER' },
     fChWeek12Flag: { public: true, type: 'INTEGER' },
     fChWeek13Flag: { public: true, type: 'INTEGER' },
     fChWeek14Flag: { public: true, type: 'INTEGER' },
     fChWeek15Flag: { public: true, type: 'INTEGER' },
     fDefault1Flag: { public: true, type: 'INTEGER' },
     fDefault2Flag: { public: true, type: 'INTEGER' },
     fDefault3Flag: { public: true, type: 'INTEGER' },
     fDefault4Flag: { public: true, type: 'INTEGER' },
     fDefault5Flag: { public: true, type: 'INTEGER' },
     fDefault6Flag: { public: true, type: 'INTEGER' },
     fDefault7Flag: { public: true, type: 'INTEGER' },
     fDefault8Flag: { public: true, type: 'INTEGER' },
     fDefault9Flag: { public: true, type: 'INTEGER' },
     fDefault10Flag: { public: true, type: 'INTEGER' },
     fDefault11Flag: { public: true, type: 'INTEGER' },
     fDefault12Flag: { public: true, type: 'INTEGER' },
     fDefault13Flag: { public: true, type: 'INTEGER' },
     fDefault14Flag: { public: true, type: 'INTEGER' },
     fDefault15Flag: { public: true, type: 'INTEGER' },
     fLateFlag: { public: true, type: 'INTEGER' },
     fConstrFlag: { public: true, type: 'INTEGER' },
     fProdNrFlag: { public: true, type: 'INTEGER' },
     fProdOpNrFlag: { public: true, type: 'INTEGER' },
     fUseDefFlag: { public: true, type: 'INTEGER' },
     fDeletePlanFlag: { public: true, type: 'INTEGER' } },
  indexes: { UserCodeIndex793: { fields: [ 'fUserCode' ], indicesType: 'UNIQUE' } } }