module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fEmployeeCode: { public: true, type: 'TEXT' },
     fEmployeeName: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fDepartment: { public: true, type: 'TEXT' },
     fUserCode: { public: true, type: 'TEXT' },
     fLoyalty: { public: true, type: 'INTEGER' },
     fAttitude: { public: true, type: 'INTEGER' },
     fLearningCurve: { public: true, type: 'INTEGER' },
     fCustomerRelations: { public: true, type: 'INTEGER' },
     fSalesEffort: { public: true, type: 'INTEGER' },
     fWorkEffort: { public: true, type: 'INTEGER' },
     fResponsibility: { public: true, type: 'INTEGER' },
     fInternalTraining: { public: true, type: 'INTEGER' },
     fPrivateLife: { public: true, type: 'INTEGER' },
     fLoyaltyStr: { public: true, type: 'TEXT' },
     fAttitudeStr: { public: true, type: 'TEXT' },
     fLearningCurveStr: { public: true, type: 'TEXT' },
     fCustomerRelationsStr: { public: true, type: 'TEXT' },
     fSalesEffortStr: { public: true, type: 'TEXT' },
     fWorkEffortStr: { public: true, type: 'TEXT' },
     fResponsibilityStr: { public: true, type: 'TEXT' },
     fInternalTrainingStr: { public: true, type: 'TEXT' },
     fPrivateLifeStr: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fImprovement1: { public: true, type: 'TEXT' },
     fImprovement2: { public: true, type: 'TEXT' },
     fImprovement3: { public: true, type: 'TEXT' },
     fImprovement4: { public: true, type: 'TEXT' },
     fImprovement5: { public: true, type: 'TEXT' } },
  indexes: 
   { EmployeeCodeIndex574: 
      { fields: [ 'fEmployeeCode', 'fTransDate' ],
        indicesType: 'UNIQUE' } } }