module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fMachineCostItem: { public: true, type: 'TEXT' },
     fAutoCalcCostf: { public: true, type: 'INTEGER' },
     fAutoGenProd: { public: true, type: 'INTEGER' },
     fDayBuffer: { public: true, type: 'INTEGER' },
     fRoundUpToOneDay: { public: true, type: 'INTEGER' },
     fWorkCostPerHour: { public: true, type: 'FLOAT' },
     fAddWorkCost: { public: true, type: 'INTEGER' },
     fAddDiscardedCost: { public: true, type: 'INTEGER' },
     fActType: { public: true, type: 'TEXT' },
     fSetupActType: { public: true, type: 'TEXT' },
     fMakeSDFromDiscard: { public: true, type: 'INTEGER' },
     fXDiscardedAccount: { public: true, type: 'TEXT' },
     fSetNormalPlanned: { public: true, type: 'INTEGER' },
     fProdRowsHoldActualQty: { public: true, type: 'INTEGER' },
     fCompleteSequence: { public: true, type: 'INTEGER' },
     fLabourCostItem: { public: true, type: 'TEXT' },
     fSetupCostItem: { public: true, type: 'TEXT' },
     fMoveCostItem: { public: true, type: 'TEXT' },
     fQueueCostItem: { public: true, type: 'TEXT' },
     fFixedTime: { public: true, type: 'INTEGER' },
     fMoveActType: { public: true, type: 'TEXT' },
     fQueueActType: { public: true, type: 'TEXT' },
     fUpdProdInQtyFromStockMov: { public: true, type: 'INTEGER' },
     fOrdClassToProd: { public: true, type: 'INTEGER' } } }