module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     StockTakeVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fSpec: { public: true, type: 'TEXT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fQty: { public: true, type: 'FLOAT' },
           fLocation: { public: true, type: 'TEXT' },
           fVARList: { public: true, type: 'TEXT' },
           fCoefficient: { public: true, type: 'FLOAT' },
           fBasePrice: { public: true, type: 'FLOAT' },
           fUnitXval: { public: true, type: 'FLOAT' },
           fUnitYval: { public: true, type: 'FLOAT' },
           fUnitZval: { public: true, type: 'FLOAT' },
           fPosition: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fCostAcc: { public: true, type: 'TEXT' },
           fFIFO: { public: true, type: 'FLOAT' },
           fFIFORowVal: { public: true, type: 'FLOAT' },
           fOldFIFO: { public: true, type: 'FLOAT' },
           fOldFIFORowVal: { public: true, type: 'FLOAT' },
           fInStock: { public: true, type: 'FLOAT' } } },
     fTransDate: { public: true, type: 'DATE' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fLocation: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fPosition: { public: true, type: 'TEXT' },
     fSetStockValue: { public: true, type: 'INTEGER' },
     fOverrideBackdated: { public: true, type: 'INTEGER' },
     fAcceptanceStatus: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex3: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }