module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fPlanDate: { public: true, type: 'DATE' },
     fPlanTime: { public: true, type: 'TIME' },
     fRecalcWeeks: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fLastChanged: { public: true, type: 'DATE' },
     fUserCode: { public: true, type: 'TEXT' },
     ProdPlanIDVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fFromDate: { public: true, type: 'DATE' },
           fToDate: { public: true, type: 'DATE' },
           fMonStart: { public: true, type: 'TIME' },
           fMonEnd: { public: true, type: 'FLOAT' },
           fTueStart: { public: true, type: 'TIME' },
           fTueEnd: { public: true, type: 'FLOAT' },
           fWedStart: { public: true, type: 'TIME' },
           fWedEnd: { public: true, type: 'FLOAT' },
           fThuStart: { public: true, type: 'TIME' },
           fThuEnd: { public: true, type: 'FLOAT' },
           fFriStart: { public: true, type: 'TIME' },
           fFriEnd: { public: true, type: 'FLOAT' },
           fSatStart: { public: true, type: 'TIME' },
           fSatEnd: { public: true, type: 'FLOAT' },
           fSunStart: { public: true, type: 'TIME' },
           fSunEnd: { public: true, type: 'FLOAT' },
           fMGroup: { public: true, type: 'TEXT' },
           fMachine: { public: true, type: 'TEXT' },
           fType: { public: true, type: 'INTEGER' },
           fRecid: { public: true, type: 'TEXT' } } } },
  indexes: { SerNrIndex790: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }