module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fPeriodType: { public: true, type: 'INTEGER' },
     fStartTime: { public: true, type: 'TIME' },
     fEndTime: { public: true, type: 'TIME' },
     fDayInterval: { public: true, type: 'INTEGER' },
     fDayTimeInterval: { public: true, type: 'TIME' },
     fDayType: { public: true, type: 'INTEGER' },
     fMonthInterval: { public: true, type: 'INTEGER' },
     fMonthType: { public: true, type: 'INTEGER' },
     fWeekDay: { public: true, type: 'INTEGER' },
     fWeekInterval: { public: true, type: 'INTEGER' },
     fMon: { public: true, type: 'INTEGER' },
     fTue: { public: true, type: 'INTEGER' },
     fWed: { public: true, type: 'INTEGER' },
     fThu: { public: true, type: 'INTEGER' },
     fFri: { public: true, type: 'INTEGER' },
     fSat: { public: true, type: 'INTEGER' },
     fSun: { public: true, type: 'INTEGER' } },
  indexes: { CodeIndex640: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }