module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fRecSerNr: { public: true, type: 'INTEGER' },
     fVcNr: { public: true, type: 'INTEGER' },
     fCompnr: { public: true, type: 'INTEGER' },
     fFromDate: { public: true, type: 'DATE' },
     fFromTime: { public: true, type: 'TIME' },
     fToDate: { public: true, type: 'DATE' },
     fToTime: { public: true, type: 'TIME' },
     fColor: { public: true, type: 'INTEGER' },
     fLabel: { public: true, type: 'TEXT' },
     fColumn: { public: true, type: 'TEXT' },
     fCalTimeFlag: { public: true, type: 'INTEGER' },
     fSubColumn: { public: true, type: 'INTEGER' },
     fTotSubColumns: { public: true, type: 'INTEGER' } } }