module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fRegDate: { public: true, type: 'DATE' },
     fComment: { public: true, type: 'TEXT' },
     fCustCode: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fAgreementNr: { public: true, type: 'INTEGER' },
     fCollectionNr: { public: true, type: 'INTEGER' },
     fLocation: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fInclVAT: { public: true, type: 'INTEGER' },
     fSumQuant: { public: true, type: 'FLOAT' },
     fTotFee: { public: true, type: 'FLOAT' },
     fSVONr: { public: true, type: 'INTEGER' },
     fSign: { public: true, type: 'TEXT' },
     fClientContact: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fSalesMan: { public: true, type: 'TEXT' },
     OffHireVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fSpec: { public: true, type: 'TEXT' },
           fStatus: { public: true, type: 'INTEGER' },
           fRentResSerNo: { public: true, type: 'INTEGER' },
           fContact: { public: true, type: 'TEXT' },
           fLocation: { public: true, type: 'TEXT' },
           fRentResRow: { public: true, type: 'INTEGER' },
           fCost: { public: true, type: 'FLOAT' },
           fValue: { public: true, type: 'FLOAT' },
           fPurchaseDate: { public: true, type: 'DATE' },
           fWarrantyUntil: { public: true, type: 'DATE' },
           fVECode: { public: true, type: 'TEXT' },
           fReturnedQty: { public: true, type: 'FLOAT' },
           fServiceQty: { public: true, type: 'FLOAT' },
           fSoldQty: { public: true, type: 'FLOAT' },
           fMissingQty: { public: true, type: 'FLOAT' },
           fScrapedQty: { public: true, type: 'FLOAT' } } },
     fSite: { public: true, type: 'TEXT' },
     fOKCheck: { public: true, type: 'INTEGER' },
     fInvalid: { public: true, type: 'INTEGER' },
     fInvalidDate: { public: true, type: 'DATE' } },
  indexes: { SerNrIndex350: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }