module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fQueType: { public: true, type: 'INTEGER' },
     fStockMovNr: { public: true, type: 'INTEGER' },
     fAttempts: { public: true, type: 'INTEGER' },
     fStatus: { public: true, type: 'INTEGER' },
     fForkLiftSystemID: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fSHNr: { public: true, type: 'INTEGER' },
     fFrPosCode: { public: true, type: 'TEXT' },
     fToPosCode: { public: true, type: 'TEXT' },
     fArtCode: { public: true, type: 'TEXT' },
     fQuant: { public: true, type: 'FLOAT' },
     fForkLift: { public: true, type: 'TEXT' },
     fFullPallet: { public: true, type: 'INTEGER' },
     fLocArea: { public: true, type: 'TEXT' },
     fNextInPickMode: { public: true, type: 'INTEGER' },
     fQuePriority: { public: true, type: 'INTEGER' },
     fDone: { public: true, type: 'INTEGER' },
     fFrLocation: { public: true, type: 'TEXT' },
     fToLocation: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex424: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }