module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fOrderNr: { public: true, type: 'INTEGER' },
     fPOOrderNr: { public: true, type: 'INTEGER' },
     fShipDate: { public: true, type: 'DATE' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fCustCode: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fAddr1: { public: true, type: 'TEXT' },
     fAddr2: { public: true, type: 'TEXT' },
     fAddr3: { public: true, type: 'TEXT' },
     fDelAddr3: { public: true, type: 'TEXT' },
     fDelAddr4: { public: true, type: 'TEXT' },
     fDelAddrCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fPrntdf: { public: true, type: 'INTEGER' },
     fShipMode: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fTotQty: { public: true, type: 'FLOAT' },
     fObjects: { public: true, type: 'TEXT' },
     fTotWeight: { public: true, type: 'FLOAT' },
     fTotVolume: { public: true, type: 'FLOAT' },
     fSorting: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     DropSHVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fOrdered: { public: true, type: 'FLOAT' },
           fShip: { public: true, type: 'FLOAT' },
           fSpec: { public: true, type: 'TEXT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fBestBefore: { public: true, type: 'DATE' },
           fCostPrice: { public: true, type: 'FLOAT' },
           fBasePrice: { public: true, type: 'FLOAT' },
           fDespatchRowDate: { public: true, type: 'DATE' },
           fDespatchRowTime: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fCOSAcc: { public: true, type: 'TEXT' },
           fPurAccrualsAcc: { public: true, type: 'TEXT' },
           fOrdRow: { public: true, type: 'INTEGER' },
           fPOOrdRow: { public: true, type: 'INTEGER' },
           fVATCode: { public: true, type: 'TEXT' },
           fInPrice: { public: true, type: 'FLOAT' },
           fStockType: { public: true, type: 'INTEGER' },
           fSuppSerialNr: { public: true, type: 'TEXT' },
           fMajStoneDet: { public: true, type: 'TEXT' },
           fColour: { public: true, type: 'TEXT' },
           fClarity: { public: true, type: 'TEXT' },
           fCert: { public: true, type: 'TEXT' },
           fMinStoneDet: { public: true, type: 'TEXT' },
           fMetal: { public: true, type: 'TEXT' },
           fRowWeight: { public: true, type: 'TEXT' },
           fSize: { public: true, type: 'TEXT' },
           fLength: { public: true, type: 'TEXT' },
           fWatchBrand: { public: true, type: 'TEXT' },
           fStyleName: { public: true, type: 'TEXT' },
           fWatchMetal: { public: true, type: 'TEXT' },
           fMovement: { public: true, type: 'TEXT' },
           fBrcStr: { public: true, type: 'TEXT' },
           fGender: { public: true, type: 'TEXT' },
           fOther: { public: true, type: 'TEXT' },
           fOther2: { public: true, type: 'TEXT' } } } },
  indexes: { SerNrIndex684: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }