module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fHeader: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fTransTime: { public: true, type: 'TIME' },
     fLockedFlag: { public: true, type: 'INTEGER' },
     fSendFlag: { public: true, type: 'INTEGER' },
     fHasFileAtt: { public: true, type: 'INTEGER' },
     fHasRecAtt: { public: true, type: 'INTEGER' },
     MailVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math2',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fRowTyp: { public: true, type: 'INTEGER' },
           fAddrCode: { public: true, type: 'TEXT' },
           fAddrStatus: { public: true, type: 'INTEGER' },
           fAddrFolder: { public: true, type: 'TEXT' },
           fMailbox: { public: true, type: 'INTEGER' } } },
     fMath: { public: true, type: 'TEXT' },
     fPriority: { public: true, type: 'INTEGER' },
     fLifespan: { public: true, type: 'INTEGER' },
     fMessageID: { public: true, type: 'TEXT' },
     fIdentifier: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fSortorder: { public: true, type: 'TEXT' },
     fVersion: { public: true, type: 'INTEGER' },
     fHtmlTranslation: { public: true, type: 'INTEGER' },
     fHtmlTemplate: { public: true, type: 'TEXT' },
     fHtmlFlag: { public: true, type: 'INTEGER' },
     fSendDate: { public: true, type: 'DATE' },
     fSendTime: { public: true, type: 'TIME' },
     fTags: { public: true, type: 'TEXT' },
     fHtmlRev: { public: true, type: 'INTEGER' },
     fRequireAcceptance: { public: true, type: 'INTEGER' },
     fIsComment: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex199: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }