module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fName: { public: true, type: 'TEXT' },
     fCompileType: { public: true, type: 'INTEGER' },
     fTitle: { public: true, type: 'TEXT' },
     fDescription: { public: true, type: 'TEXT' },
     fRegister: { public: true, type: 'TEXT' },
     WindowDefinitionVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fFieldName: { public: true, type: 'TEXT' },
           fHPos: { public: true, type: 'INTEGER' },
           fVPos: { public: true, type: 'INTEGER' },
           fWidth: { public: true, type: 'INTEGER' },
           fLabel: { public: true, type: 'TEXT' },
           fOverrideType: { public: true, type: 'INTEGER' },
           fEditMode: { public: true, type: 'INTEGER' },
           fOverrideCharacters: { public: true, type: 'INTEGER' },
           fAdjustment: { public: true, type: 'INTEGER' },
           fPasteSpecialFunction: { public: true, type: 'TEXT' },
           fDescription: { public: true, type: 'TEXT' },
           fSelVal: { public: true, type: 'INTEGER' },
           fHeight: { public: true, type: 'INTEGER' },
           fTile: { public: true, type: 'INTEGER' },
           fFlip: { public: true, type: 'INTEGER' },
           fVarName: { public: true, type: 'TEXT' },
           fHalFunction: { public: true, type: 'TEXT' } } },
     fWindowType: { public: true, type: 'INTEGER' },
     fLanguage: { public: true, type: 'TEXT' },
     fWidth: { public: true, type: 'INTEGER' },
     fHeight: { public: true, type: 'INTEGER' },
     fXxSpawnClass: { public: true, type: 'TEXT' },
     fAdjustTiles: { public: true, type: 'INTEGER' },
     fApp: { public: true, type: 'TEXT' },
     fType: { public: true, type: 'INTEGER' },
     fSpawnType: { public: true, type: 'INTEGER' } },
  indexes: 
   { MainKeyIndex565: 
      { fields: [ 'fRegister', 'fType', 'fCompileType', 'fLanguage', 'fName' ],
        indicesType: 'UNIQUE' } } }