module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSessionUUID: { public: true, type: 'TEXT' },
     fRequestedVersionBuild: { public: true, type: 'INTEGER' },
     fRequestedNewVersionBuild: { public: true, type: 'INTEGER' },
     fProgramType: { public: true, type: 'INTEGER' },
     fProductCode: { public: true, type: 'TEXT' },
     fCountryLocalizations: { public: true, type: 'TEXT' },
     fCUCode: { public: true, type: 'TEXT' },
     fEMail: { public: true, type: 'TEXT' },
     fCompName: { public: true, type: 'TEXT' },
     fVersionString: { public: true, type: 'TEXT' },
     fProtocolVersion: { public: true, type: 'INTEGER' },
     fCountryCode: { public: true, type: 'TEXT' } },
  indexes: { MainKeyIndex865: { fields: [ 'fSessionUUID' ], indicesType: 'UNIQUE' } } }