module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fStatus: { public: true, type: 'INTEGER' },
     fDesc: { public: true, type: 'TEXT' },
     fPrio: { public: true, type: 'INTEGER' },
     fReportedBy: { public: true, type: 'TEXT' },
     fLastVerifiedBy: { public: true, type: 'TEXT' },
     fFixedBy: { public: true, type: 'TEXT' },
     fTestedBy: { public: true, type: 'TEXT' },
     fCouldBeFixedBy: { public: true, type: 'TEXT' },
     fModules: { public: true, type: 'TEXT' },
     fReportedDate: { public: true, type: 'DATE' },
     fLastVerifiedDate: { public: true, type: 'DATE' },
     fFixedDate: { public: true, type: 'DATE' },
     fTestedDate: { public: true, type: 'DATE' },
     fProgrammersAssigned: { public: true, type: 'INTEGER' },
     fProgrammersAssignedDate: { public: true, type: 'DATE' },
     fReportedVersion: { public: true, type: 'TEXT' },
     fLastVerifiedVersion: { public: true, type: 'TEXT' },
     fFixedVersion: { public: true, type: 'TEXT' },
     fMath: { public: true, type: 'TEXT' },
     fRepPrio: { public: true, type: 'INTEGER' },
     fPrioAssigned: { public: true, type: 'INTEGER' },
     fPrioAssignedDate: { public: true, type: 'DATE' },
     fProgrammersAssignedBy: { public: true, type: 'TEXT' },
     fPrioAssignedBy: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex694: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }