module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fCourseCode: { public: true, type: 'TEXT' },
     fCourseName: { public: true, type: 'TEXT' },
     fType: { public: true, type: 'TEXT' },
     fItemCode: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fStartTime: { public: true, type: 'TIME' },
     fEndTime: { public: true, type: 'TIME' },
     fLangCode: { public: true, type: 'TEXT' },
     CourseEventVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fContactCode: { public: true, type: 'TEXT' },
           fContactName: { public: true, type: 'TEXT' },
           fPrice: { public: true, type: 'FLOAT' },
           fPriceListRow: { public: true, type: 'TEXT' },
           fDiscount: { public: true, type: 'FLOAT' },
           fHotel: { public: true, type: 'TEXT' },
           fNights: { public: true, type: 'INTEGER' },
           fInvoiceNo: { public: true, type: 'INTEGER' },
           fItemCode: { public: true, type: 'TEXT' },
           fHotelPrice: { public: true, type: 'FLOAT' },
           fReference: { public: true, type: 'TEXT' },
           fBookingDate: { public: true, type: 'DATE' },
           fStatus: { public: true, type: 'INTEGER' },
           fSource: { public: true, type: 'TEXT' },
           fCancelDate: { public: true, type: 'DATE' },
           fConfDate: { public: true, type: 'DATE' },
           fNotifyDate: { public: true, type: 'DATE' },
           fCustCode: { public: true, type: 'TEXT' },
           fSum: { public: true, type: 'FLOAT' },
           fPRCode: { public: true, type: 'TEXT' } } },
     fTransDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fLastTransferDate: { public: true, type: 'DATE' },
     fNextConfDate: { public: true, type: 'DATE' },
     fComment: { public: true, type: 'TEXT' },
     fResStatus: { public: true, type: 'TEXT' },
     fCUCode: { public: true, type: 'TEXT' },
     fCUName: { public: true, type: 'TEXT' },
     fPriceList: { public: true, type: 'TEXT' },
     fMaxPersons: { public: true, type: 'INTEGER' },
     fNoOfPersons: { public: true, type: 'INTEGER' },
     fSalesMan: { public: true, type: 'TEXT' },
     fSalesGroup: { public: true, type: 'TEXT' },
     fConferenceLocation: { public: true, type: 'TEXT' },
     fConferenceLocationName: { public: true, type: 'TEXT' },
     fHotel: { public: true, type: 'TEXT' },
     fHotelName: { public: true, type: 'TEXT' },
     fPLPrice: { public: true, type: 'FLOAT' },
     fPrice: { public: true, type: 'FLOAT' },
     fDiscount: { public: true, type: 'FLOAT' },
     fSum: { public: true, type: 'FLOAT' },
     fInvoicedSum: { public: true, type: 'FLOAT' },
     fBookDate: { public: true, type: 'DATE' },
     fTotalSum4: { public: true, type: 'FLOAT' },
     fNrOfDays: { public: true, type: 'INTEGER' },
     fRoomChangeFlag: { public: true, type: 'INTEGER' },
     fVatSum: { public: true, type: 'FLOAT' },
     fTotalVatSum: { public: true, type: 'FLOAT' },
     fCreatedDate: { public: true, type: 'DATE' },
     fHeaderInfo1: { public: true, type: 'TEXT' },
     fHeaderInfo2: { public: true, type: 'TEXT' },
     fHeaderInfo3: { public: true, type: 'TEXT' },
     fFooterInfo1: { public: true, type: 'TEXT' },
     fFooterInfo2: { public: true, type: 'TEXT' },
     fFooterInfo3: { public: true, type: 'TEXT' },
     fMinPersons: { public: true, type: 'INTEGER' },
     fStatusFlag: { public: true, type: 'INTEGER' },
     fLastBookingDate: { public: true, type: 'DATE' },
     fCountryCode: { public: true, type: 'TEXT' },
     fShowOnFirstPage: { public: true, type: 'INTEGER' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fInvFlag: { public: true, type: 'INTEGER' },
     fActType: { public: true, type: 'TEXT' },
     fResponsible: { public: true, type: 'TEXT' },
     fRemindersSent: { public: true, type: 'INTEGER' },
     fPRCode: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex547: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }