module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fName: { public: true, type: 'TEXT' },
     fHansaVersion: { public: true, type: 'TEXT' },
     fDataFolder: { public: true, type: 'TEXT' },
     fBindIP: { public: true, type: 'TEXT' },
     fPort: { public: true, type: 'INTEGER' },
     fWantedStatus: { public: true, type: 'INTEGER' },
     fCurrentStatus: { public: true, type: 'INTEGER' },
     fNextAttemptDate: { public: true, type: 'DATE' },
     fNextAttemptTime: { public: true, type: 'TIME' },
     fStatusText: { public: true, type: 'TEXT' },
     fHTTPPort: { public: true, type: 'INTEGER' },
     fHTTPSPort: { public: true, type: 'INTEGER' },
     fCUCode: { public: true, type: 'TEXT' },
     fClosed: { public: true, type: 'INTEGER' },
     fCreatedDate: { public: true, type: 'DATE' },
     fCreatedTime: { public: true, type: 'TIME' },
     fExtraParameters: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fMassiveCacheMB: { public: true, type: 'INTEGER' },
     fLogLevel: { public: true, type: 'INTEGER' },
     fServerName: { public: true, type: 'TEXT' },
     fCoreDump: { public: true, type: 'INTEGER' },
     fLastStartDate: { public: true, type: 'DATE' },
     fLastStartTime: { public: true, type: 'TIME' },
     fQuickRestarts: { public: true, type: 'INTEGER' },
     fUUIDLock: { public: true, type: 'INTEGER' },
     fDisableHobcheck: { public: true, type: 'INTEGER' },
     fNewHansaVersion: { public: true, type: 'TEXT' },
     fWantedSubStatus: { public: true, type: 'INTEGER' },
     fCurrentSubStatus: { public: true, type: 'INTEGER' },
     LocalCloudServerVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fItem: { public: true, type: 'INTEGER' },
           fDesc: { public: true, type: 'TEXT' },
           fItemName: { public: true, type: 'TEXT' },
           fData: { public: true, type: 'TEXT' },
           fWhen: { public: true, type: 'INTEGER' },
           fDisabled: { public: true, type: 'INTEGER' } } },
     fHalcustUpdateRule: { public: true, type: 'INTEGER' },
     fHalpatchUpdateRule: { public: true, type: 'INTEGER' },
     fBackupFolder: { public: true, type: 'TEXT' },
     fExecutableType: { public: true, type: 'INTEGER' },
     fBackupTime: { public: true, type: 'TEXT' },
     fPublicHostName: { public: true, type: 'TEXT' },
     fFastCheckFlag: { public: true, type: 'INTEGER' },
     fNewController: { public: true, type: 'TEXT' },
     fMaintPort: { public: true, type: 'INTEGER' },
     fWantedStatusParams: { public: true, type: 'TEXT' },
     fCloneFlag: { public: true, type: 'INTEGER' },
     fWebClientStartPort: { public: true, type: 'INTEGER' },
     fWebClientEndPort: { public: true, type: 'INTEGER' },
     fProgramType: { public: true, type: 'INTEGER' },
     fDisableCloudBackupFlag: { public: true, type: 'INTEGER' },
     fClassification: { public: true, type: 'TEXT' },
     fMovedAwayFlag: { public: true, type: 'INTEGER' },
     fOnDemandFlag: { public: true, type: 'INTEGER' },
     fLocalizations: { public: true, type: 'TEXT' },
     fBackupOnStopFlag: { public: true, type: 'INTEGER' },
     fCountryLocalizations: { public: true, type: 'TEXT' },
     fMigrationFlag: { public: true, type: 'INTEGER' },
     fClosedOnNodeFlag: { public: true, type: 'INTEGER' },
     fContract: { public: true, type: 'INTEGER' },
     fOrgNr: { public: true, type: 'TEXT' },
     fOrgNr2: { public: true, type: 'TEXT' },
     fVATNr: { public: true, type: 'TEXT' },
     fOldHansaVersion: { public: true, type: 'TEXT' },
     fWatchpointExceptions: { public: true, type: 'TEXT' },
     fExceptionComment: { public: true, type: 'TEXT' },
     fEncryptionKey: { public: true, type: 'TEXT' },
     fJournalPresentFlag: { public: true, type: 'INTEGER' },
     fHMCUCode: { public: true, type: 'TEXT' },
     fHMRegInCountry: { public: true, type: 'INTEGER' },
     fLastStopDate: { public: true, type: 'DATE' },
     fLastStopTime: { public: true, type: 'TIME' },
     fUUID: { public: true, type: 'TEXT' } },
  indexes: { MainKeyIndex559: { fields: [ 'fUUID' ], indicesType: 'UNIQUE' } } }