module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fSorting: { public: true, type: 'INTEGER' },
     fSign: { public: true, type: 'TEXT' },
     fType: { public: true, type: 'INTEGER' },
     fAllowManualRecalcf: { public: true, type: 'INTEGER' },
     fFrequency: { public: true, type: 'TIME' },
     fCompany: { public: true, type: 'INTEGER' },
     fStatus: { public: true, type: 'INTEGER' },
     fCurrent: { public: true, type: 'FLOAT' },
     fPrevious: { public: true, type: 'FLOAT' },
     fLastCalcDate: { public: true, type: 'DATE' },
     fLastCalcTime: { public: true, type: 'TIME' },
     fURL: { public: true, type: 'TEXT' },
     fOpenType: { public: true, type: 'INTEGER' },
     fPeriodLength: { public: true, type: 'INTEGER' },
     fPeriodType: { public: true, type: 'INTEGER' },
     fOwnTitle: { public: true, type: 'TEXT' },
     fReverseArrowf: { public: true, type: 'INTEGER' },
     fPerson: { public: true, type: 'TEXT' },
     fPeriodUnits: { public: true, type: 'INTEGER' },
     fAutoCalculated: { public: true, type: 'INTEGER' },
     fItemCode: { public: true, type: 'TEXT' },
     fItemGroup: { public: true, type: 'TEXT' },
     fItemClass: { public: true, type: 'TEXT' },
     fActType: { public: true, type: 'TEXT' },
     fActTypeGr: { public: true, type: 'TEXT' },
     fReverseColorf: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex655: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }