module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fVerNr: { public: true, type: 'INTEGER' },
     fMinVerNr: { public: true, type: 'INTEGER' },
     fVerNrWindows: { public: true, type: 'INTEGER' },
     fMinVerNrWindows: { public: true, type: 'INTEGER' },
     fVerNrOSXCocoa: { public: true, type: 'INTEGER' },
     fMinVerNrOSXCocoa: { public: true, type: 'INTEGER' },
     fVerNriPhone: { public: true, type: 'INTEGER' },
     fMinVerNriPhone: { public: true, type: 'INTEGER' },
     fVerNrAndroid: { public: true, type: 'INTEGER' },
     fMinVerNrAndroid: { public: true, type: 'INTEGER' },
     fVerNrMetro: { public: true, type: 'INTEGER' },
     fMinVerNrMetro: { public: true, type: 'INTEGER' },
     fNextVerNrWindows: { public: true, type: 'INTEGER' },
     fNextVerNrOSXCocoa: { public: true, type: 'INTEGER' },
     fNextVerNriPhone: { public: true, type: 'INTEGER' },
     fNextVerNrAndroid: { public: true, type: 'INTEGER' },
     fNextVerNrMetro: { public: true, type: 'INTEGER' },
     fVerNrWindowsNet: { public: true, type: 'INTEGER' },
     fMinVerNrWindowsNet: { public: true, type: 'INTEGER' },
     fNextVerNrWindowsNet: { public: true, type: 'INTEGER' },
     fVerNrLinux: { public: true, type: 'INTEGER' },
     fMinVerNrLinux: { public: true, type: 'INTEGER' },
     fNextVerNrLinux: { public: true, type: 'INTEGER' } } }