module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fSVOSerNr: { public: true, type: 'INTEGER' },
     fCustCode: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fPlanDate: { public: true, type: 'TEXT' },
     fPlanWork: { public: true, type: 'TEXT' },
     fOurContact: { public: true, type: 'TEXT' },
     fCustContact: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fCustOrdNr: { public: true, type: 'TEXT' },
     fClosed: { public: true, type: 'INTEGER' },
     fDone: { public: true, type: 'INTEGER' },
     fEMCode: { public: true, type: 'TEXT' },
     fEMName: { public: true, type: 'TEXT' },
     fPhone: { public: true, type: 'TEXT' },
     fFax: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fComment1: { public: true, type: 'TEXT' },
     fComment2: { public: true, type: 'TEXT' },
     fComment3: { public: true, type: 'TEXT' },
     fComment4: { public: true, type: 'TEXT' },
     fVATNr: { public: true, type: 'TEXT' },
     fCustVATCode: { public: true, type: 'TEXT' },
     fInvoiceToCode: { public: true, type: 'TEXT' },
     fPrntdf: { public: true, type: 'INTEGER' },
     fSalesGroup: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     WOVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fObjects: { public: true, type: 'TEXT' },
           fSpec: { public: true, type: 'TEXT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fPlanWork: { public: true, type: 'FLOAT' },
           fVARList: { public: true, type: 'TEXT' },
           fMaxCost: { public: true, type: 'FLOAT' },
           fItemType: { public: true, type: 'INTEGER' },
           fPlanShiprw: { public: true, type: 'TEXT' },
           fContractNr: { public: true, type: 'INTEGER' },
           fStandProblem: { public: true, type: 'TEXT' },
           fVATCode: { public: true, type: 'TEXT' } } },
     fRegDate: { public: true, type: 'DATE' },
     fRegTime: { public: true, type: 'TIME' } },
  indexes: { SerNrIndex183: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }