module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fServiceWIPAcc: { public: true, type: 'TEXT' },
     fServiceBalAcc: { public: true, type: 'TEXT' },
     fServiceCostAcc: { public: true, type: 'TEXT' },
     fMaterialWIPAcc: { public: true, type: 'TEXT' },
     fMaterialBalAcc: { public: true, type: 'TEXT' },
     fMaterialCostAcc: { public: true, type: 'TEXT' },
     fStockWIPAcc: { public: true, type: 'TEXT' },
     fPlainCostAcc: { public: true, type: 'TEXT' },
     fStockBalAcc: { public: true, type: 'TEXT' },
     fPlainWIPAcc: { public: true, type: 'TEXT' },
     fPlainBalAcc: { public: true, type: 'TEXT' },
     fRetentionAcc: { public: true, type: 'TEXT' },
     fAPRetentionAcc: { public: true, type: 'TEXT' },
     fRetentionVATCode: { public: true, type: 'TEXT' },
     fAPRetentionVATCode: { public: true, type: 'TEXT' } } }