module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fForumRootConf: { public: true, type: 'TEXT' },
     fForumReplyConf: { public: true, type: 'TEXT' },
     fForumReportConf: { public: true, type: 'TEXT' },
     fListCnt: { public: true, type: 'INTEGER' },
     fReportFlag: { public: true, type: 'INTEGER' },
     fListBodyFlag: { public: true, type: 'INTEGER' },
     fNewCustMail: { public: true, type: 'INTEGER' },
     fCustMailFrom: { public: true, type: 'TEXT' },
     fHeaderTxtSize: { public: true, type: 'INTEGER' },
     fExtraTxtSize: { public: true, type: 'INTEGER' },
     fUserMailBox: { public: true, type: 'TEXT' },
     fBannerElement: { public: true, type: 'TEXT' },
     fLanguage: { public: true, type: 'TEXT' },
     fAllowReply: { public: true, type: 'INTEGER' },
     fReplyCustMail: { public: true, type: 'INTEGER' },
     fForumInbox: { public: true, type: 'TEXT' },
     fForumInboxMove: { public: true, type: 'TEXT' } },
  indexes: { CodeIndex852: { fields: [ 'fCode', 'fLanguage' ], indicesType: 'UNIQUE' } } }