module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fVersion: { public: true, type: 'INTEGER' },
     fSubVersion: { public: true, type: 'INTEGER' },
     fProgramType: { public: true, type: 'INTEGER' },
     fProgramFolder: { public: true, type: 'TEXT' },
     fProductCode: { public: true, type: 'TEXT' },
     fRePubCount: { public: true, type: 'INTEGER' },
     fRunningBuild: { public: true, type: 'INTEGER' },
     fDateChanged: { public: true, type: 'DATE' },
     fTimeChanged: { public: true, type: 'TIME' },
     fForceReplaceVersionf: { public: true, type: 'INTEGER' },
     fCurrentState: { public: true, type: 'INTEGER' },
     fClosed: { public: true, type: 'INTEGER' },
     fUpdateType: { public: true, type: 'INTEGER' },
     fNextVersion: { public: true, type: 'INTEGER' },
     fNextSubVersion: { public: true, type: 'INTEGER' },
     fNextRunningBuild: { public: true, type: 'INTEGER' } },
  indexes: { MainKeyIndex555: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }