module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSignature: { public: true, type: 'TEXT' },
     fInvoices: { public: true, type: 'INTEGER' },
     fNotOKVI: { public: true, type: 'INTEGER' },
     fNrOfVI: { public: true, type: 'FLOAT' },
     fShowPU: { public: true, type: 'INTEGER' },
     fMonthBal: { public: true, type: 'INTEGER' },
     fVEItem: { public: true, type: 'INTEGER' },
     fVEItemMonthNr: { public: true, type: 'INTEGER' },
     fOrders: { public: true, type: 'INTEGER' },
     fPOClass: { public: true, type: 'TEXT' },
     fNrOfPO: { public: true, type: 'FLOAT' },
     fActivities: { public: true, type: 'INTEGER' },
     fNotOKAct: { public: true, type: 'INTEGER' },
     fNrOfAct: { public: true, type: 'FLOAT' },
     fSMSes: { public: true, type: 'INTEGER' },
     fNrOfSMS: { public: true, type: 'FLOAT' },
     fContactRelations: { public: true, type: 'INTEGER' } },
  indexes: { SignatureIndex304: { fields: [ 'fSignature' ], indicesType: 'UNIQUE' } } }