module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fDisplayLoginButtons: { public: true, type: 'INTEGER' },
     fDisplayLoginKeyPad: { public: true, type: 'INTEGER' },
     fAutoConToLastActComp: { public: true, type: 'INTEGER' },
     fLastUserLoggedIn: { public: true, type: 'TEXT' },
     fLastUsedCompCode: { public: true, type: 'TEXT' },
     fWindowStyle: { public: true, type: 'INTEGER' },
     fServerIP: { public: true, type: 'TEXT' },
     fServerPort: { public: true, type: 'INTEGER' },
     fDontAskStorePwdOS: { public: true, type: 'INTEGER' },
     fChsum: { public: true, type: 'INTEGER' },
     fDontAskConnect: { public: true, type: 'INTEGER' },
     fDontAskPhone: { public: true, type: 'INTEGER' },
     fForceUpdate: { public: true, type: 'INTEGER' },
     fBiometricLogin: { public: true, type: 'INTEGER' },
     fBiometricDevice: { public: true, type: 'INTEGER' },
     fDontDisplayWelcomeScreen: { public: true, type: 'INTEGER' },
     fDefaultProgramMode: { public: true, type: 'INTEGER' },
     fGUIServer: { public: true, type: 'INTEGER' },
     fLastEmailUserLoggedIn: { public: true, type: 'TEXT' },
     fDontAutoConToLastActComp: { public: true, type: 'INTEGER' } } }