module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fType: { public: true, type: 'INTEGER' },
     fWindowDays: { public: true, type: 'INTEGER' },
     fWindowMachines: { public: true, type: 'INTEGER' },
     fViewMonths: { public: true, type: 'INTEGER' },
     fDirection: { public: true, type: 'INTEGER' },
     fGradientFlag: { public: true, type: 'INTEGER' },
     fDayCnt: { public: true, type: 'INTEGER' },
     fShowSliderFlag: { public: true, type: 'INTEGER' },
     fWeekCnt: { public: true, type: 'INTEGER' },
     fAllowWkPln: { public: true, type: 'INTEGER' },
     fRouteColor: { public: true, type: 'TEXT' },
     fDefaultHours: { public: true, type: 'TEXT' },
     fMachineFlag: { public: true, type: 'INTEGER' },
     fLateFlag: { public: true, type: 'INTEGER' },
     fConstrFlag: { public: true, type: 'INTEGER' },
     fProdNrFlag: { public: true, type: 'INTEGER' },
     fProdOpNrFlag: { public: true, type: 'INTEGER' },
     fEffectWeekCnt: { public: true, type: 'INTEGER' },
     fSetupExcludedFlag: { public: true, type: 'INTEGER' },
     fDragColor: { public: true, type: 'TEXT' },
     fDateWorkColor: { public: true, type: 'TEXT' },
     fDateHolColor: { public: true, type: 'TEXT' },
     fShowOrigColors: { public: true, type: 'INTEGER' },
     fShiftOutColor: { public: true, type: 'TEXT' },
     fShiftOverColor: { public: true, type: 'TEXT' },
     fActiveColor: { public: true, type: 'TEXT' },
     fMachineCnt: { public: true, type: 'INTEGER' },
     fMachineIdleColor: { public: true, type: 'TEXT' },
     fShiftOldColor: { public: true, type: 'TEXT' },
     fRecalcType: { public: true, type: 'INTEGER' },
     fStatusFlag: { public: true, type: 'INTEGER' },
     fProdIdleActType: { public: true, type: 'TEXT' },
     fProdOvertimeActType: { public: true, type: 'TEXT' },
     fHttpDir: { public: true, type: 'TEXT' },
     fWCHost: { public: true, type: 'TEXT' },
     fWebFileVer: { public: true, type: 'TEXT' } } }