module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fAddToDay: { public: true, type: 'INTEGER' },
     fStartTime: { public: true, type: 'TIME' },
     fStateToDirty: { public: true, type: 'INTEGER' },
     fChargeStay: { public: true, type: 'INTEGER' },
     fAddRepItems: { public: true, type: 'INTEGER' },
     fNoshowToNoshow: { public: true, type: 'INTEGER' },
     fDelChoutMes: { public: true, type: 'INTEGER' },
     fDelOldFollow: { public: true, type: 'INTEGER' },
     fDelRecHist: { public: true, type: 'INTEGER' },
     fCreateCleanAct: { public: true, type: 'INTEGER' },
     fPrelBookWIP: { public: true, type: 'INTEGER' },
     fTransComment: { public: true, type: 'TEXT' },
     fAutoBookCashup: { public: true, type: 'INTEGER' } } }