module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     BankRecVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fIntYc: { public: true, type: 'INTEGER' },
           fNumber: { public: true, type: 'INTEGER' },
           fRownr: { public: true, type: 'INTEGER' },
           fTransDate: { public: true, type: 'DATE' },
           fComment: { public: true, type: 'TEXT' },
           fVal: { public: true, type: 'FLOAT' },
           fBalVal: { public: true, type: 'FLOAT' },
           fReconsf: { public: true, type: 'INTEGER' },
           fVal2: { public: true, type: 'FLOAT' },
           fCurVal: { public: true, type: 'FLOAT' },
           fObjects: { public: true, type: 'TEXT' },
           fReconCode: { public: true, type: 'TEXT' },
           fCurncyCode: { public: true, type: 'TEXT' },
           fReconDate: { public: true, type: 'DATE' },
           fCheckNr: { public: true, type: 'TEXT' } } },
     fAccNumber: { public: true, type: 'TEXT' },
     fPeriod2Str: { public: true, type: 'TEXT' },
     fD1: { public: true, type: 'DATE' },
     fD2: { public: true, type: 'DATE' },
     fIncompletef: { public: true, type: 'INTEGER' },
     fStartBal: { public: true, type: 'FLOAT' },
     fRecVal: { public: true, type: 'FLOAT' },
     fEndBal: { public: true, type: 'FLOAT' },
     fRecedf: { public: true, type: 'INTEGER' },
     fUnrecedf: { public: true, type: 'INTEGER' },
     fRecDate: { public: true, type: 'DATE' },
     fObjects: { public: true, type: 'TEXT' },
     fCompCode: { public: true, type: 'TEXT' },
     fTyp: { public: true, type: 'INTEGER' },
     fReconCode: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fShowRefStr: { public: true, type: 'INTEGER' },
     fBankBal: { public: true, type: 'FLOAT' },
     fReconSum: { public: true, type: 'FLOAT' },
     fDiff: { public: true, type: 'FLOAT' },
     fReconDate: { public: true, type: 'DATE' } },
  indexes: { AccNumberIndex181: { fields: [ 'fAccNumber' ], indicesType: 'UNIQUE' } } }