module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fSign: { public: true, type: 'TEXT' },
     fRefStr: { public: true, type: 'TEXT' },
     fDSum: { public: true, type: 'FLOAT' },
     fCSum: { public: true, type: 'FLOAT' },
     fDiffVal: { public: true, type: 'FLOAT' },
     SMVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fAccNumber: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fX1: { public: true, type: 'TEXT' },
           fVATCode: { public: true, type: 'TEXT' },
           fDebVal: { public: true, type: 'FLOAT' },
           fCredVal: { public: true, type: 'FLOAT' },
           fTransDate: { public: true, type: 'DATE' },
           fRowSimStat: { public: true, type: 'INTEGER' },
           fDebVal2: { public: true, type: 'FLOAT' },
           fCredVal2: { public: true, type: 'FLOAT' },
           fCurDebVal: { public: true, type: 'FLOAT' },
           fCurCredVal: { public: true, type: 'FLOAT' },
           fCurncyCode: { public: true, type: 'TEXT' },
           fFrRate: { public: true, type: 'FLOAT' },
           fToRateB1: { public: true, type: 'FLOAT' },
           fToRateB2: { public: true, type: 'FLOAT' },
           fBaseRate1: { public: true, type: 'FLOAT' },
           fBaseRate2: { public: true, type: 'FLOAT' },
           fExtraComment: { public: true, type: 'TEXT' } } },
     fXMainf: { public: true, type: 'INTEGER' },
     fBalf: { public: true, type: 'INTEGER' },
     fCreateStat: { public: true, type: 'INTEGER' },
     fFileName: { public: true, type: 'TEXT' },
     fTransNr: { public: true, type: 'INTEGER' },
     fRegDate: { public: true, type: 'DATE' },
     fRegTime: { public: true, type: 'TIME' } },
  indexes: { SerNrIndex37: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }