module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fDepCode: { public: true, type: 'TEXT' },
     fDepName: { public: true, type: 'TEXT' },
     fVECode: { public: true, type: 'TEXT' },
     fVEName: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     AT2PUVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStp: { public: true, type: 'INTEGER' },
           fOvst: { public: true, type: 'INTEGER' },
           fAT2Code: { public: true, type: 'TEXT' },
           fDescription: { public: true, type: 'TEXT' },
           fInventoryNr: { public: true, type: 'TEXT' },
           fPurchPrice: { public: true, type: 'FLOAT' },
           fExtraCost: { public: true, type: 'FLOAT' },
           fPurchVal: { public: true, type: 'FLOAT' },
           fInitDeprVal1: { public: true, type: 'FLOAT' },
           fInitDeprVal2: { public: true, type: 'FLOAT' },
           fInsuranceVal: { public: true, type: 'FLOAT' },
           fResVal: { public: true, type: 'FLOAT' },
           fMinDprVal: { public: true, type: 'FLOAT' },
           fProdDate: { public: true, type: 'DATE' },
           fStartingDate: { public: true, type: 'DATE' },
           fModel1: { public: true, type: 'TEXT' },
           fModel2: { public: true, type: 'TEXT' },
           fMetal: { public: true, type: 'TEXT' },
           fMetalWeight: { public: true, type: 'FLOAT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fWarrantyNr: { public: true, type: 'TEXT' },
           fLifespan: { public: true, type: 'INTEGER' },
           fInvestVal: { public: true, type: 'FLOAT' },
           fModelMin: { public: true, type: 'TEXT' },
           fModelMax: { public: true, type: 'TEXT' },
           fSubsidyVal: { public: true, type: 'FLOAT' },
           fContractNr: { public: true, type: 'TEXT' },
           fEndDate: { public: true, type: 'DATE' },
           fNewUsedf: { public: true, type: 'INTEGER' } } },
     fRespPerson: { public: true, type: 'TEXT' },
     fVISerNr: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex246: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }