module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fPeriod2Str: { public: true, type: 'TEXT' },
     fIncompletef: { public: true, type: 'INTEGER' },
     fStartBal: { public: true, type: 'FLOAT' },
     fEndBal: { public: true, type: 'FLOAT' },
     fBankBalDate: { public: true, type: 'DATE' },
     fCompCode: { public: true, type: 'TEXT' },
     fBankAcc: { public: true, type: 'TEXT' },
     PlannedPaymentsVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fReference: { public: true, type: 'TEXT' },
           fPayDate: { public: true, type: 'DATE' },
           fPlanPayDate: { public: true, type: 'DATE' },
           fAgreedPayDate: { public: true, type: 'DATE' },
           fLateDays: { public: true, type: 'FLOAT' },
           fPriority: { public: true, type: 'TEXT' },
           fApproved: { public: true, type: 'INTEGER' },
           fPaid: { public: true, type: 'INTEGER' },
           fComment: { public: true, type: 'TEXT' },
           fCurncyCode: { public: true, type: 'TEXT' },
           fSum: { public: true, type: 'FLOAT' },
           fBaseSum: { public: true, type: 'FLOAT' },
           fBalance: { public: true, type: 'FLOAT' },
           fPlanPaymentNr: { public: true, type: 'INTEGER' },
           fPlanPaymentFileName: { public: true, type: 'TEXT' } } } } }