module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fCUCode: { public: true, type: 'TEXT' },
     fDestinationNr: { public: true, type: 'INTEGER' },
     fItemCode: { public: true, type: 'TEXT' },
     fQty: { public: true, type: 'FLOAT' },
     fPrice: { public: true, type: 'FLOAT' },
     fTransDate: { public: true, type: 'DATE' },
     fTransTime: { public: true, type: 'TIME' },
     fDiscount: { public: true, type: 'FLOAT' },
     fOwner: { public: true, type: 'INTEGER' },
     fOwnerSerNr: { public: true, type: 'INTEGER' },
     fDestination: { public: true, type: 'INTEGER' },
     fBaskNo: { public: true, type: 'INTEGER' },
     fPFormCode: { public: true, type: 'TEXT' },
     fInclVAT: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     fExtraCom: { public: true, type: 'TEXT' },
     fExtraVal: { public: true, type: 'FLOAT' },
     fPeriodStartDate: { public: true, type: 'DATE' },
     fObjects: { public: true, type: 'TEXT' },
     fPrelBooked: { public: true, type: 'INTEGER' },
     fDownPayIVSerNr: { public: true, type: 'INTEGER' },
     fValueIsTip: { public: true, type: 'INTEGER' },
     fSortingAtTop: { public: true, type: 'INTEGER' },
     fNegateItem: { public: true, type: 'TEXT' },
     fPerson: { public: true, type: 'TEXT' },
     fCCPayPReNo: { public: true, type: 'INTEGER' },
     fCUServiceHistNr: { public: true, type: 'INTEGER' },
     fVECode: { public: true, type: 'TEXT' },
     fCUServiceValidUntil: { public: true, type: 'DATE' },
     fFromFileName: { public: true, type: 'TEXT' },
     fFromSerNr: { public: true, type: 'INTEGER' },
     fBasePrice: { public: true, type: 'FLOAT' },
     fResUsage: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' },
     fPriceInCur: { public: true, type: 'FLOAT' },
     fExtraValInCur: { public: true, type: 'FLOAT' },
     fBasePriceInCur: { public: true, type: 'FLOAT' } },
  indexes: { SerNrIndex237: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }