module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCompanyFullName: { public: true, type: 'TEXT' },
     fFirstName: { public: true, type: 'TEXT' },
     fLastName: { public: true, type: 'TEXT' },
     fBirthDate: { public: true, type: 'DATE' },
     fStreet: { public: true, type: 'TEXT' },
     fHouseNr: { public: true, type: 'TEXT' },
     fFlatNr: { public: true, type: 'TEXT' },
     fPostCode: { public: true, type: 'TEXT' },
     fCity: { public: true, type: 'TEXT' },
     fPostCity: { public: true, type: 'TEXT' },
     fRegion: { public: true, type: 'TEXT' },
     fCounty: { public: true, type: 'TEXT' },
     fCommunity: { public: true, type: 'TEXT' },
     fVATNr: { public: true, type: 'TEXT' },
     fVATPrefix: { public: true, type: 'TEXT' },
     fStatisticNr: { public: true, type: 'TEXT' },
     fTaxAuthID: { public: true, type: 'TEXT' },
     fType: { public: true, type: 'INTEGER' } } }