module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fAgreementNr: { public: true, type: 'INTEGER' },
     fCode: { public: true, type: 'TEXT' },
     fSerialNr: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fGroup: { public: true, type: 'TEXT' },
     fIncludeRecepy: { public: true, type: 'TEXT' },
     fPrice: { public: true, type: 'FLOAT' },
     fVRebate: { public: true, type: 'FLOAT' },
     fSum: { public: true, type: 'FLOAT' },
     fPricePer: { public: true, type: 'INTEGER' },
     fInvItem: { public: true, type: 'TEXT' },
     fInvItemName: { public: true, type: 'TEXT' },
     fLengthClass: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fStartTime: { public: true, type: 'TIME' },
     fEndTime: { public: true, type: 'TIME' },
     fAgreeStatus: { public: true, type: 'TEXT' },
     RentResVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fSpec: { public: true, type: 'TEXT' },
           fType: { public: true, type: 'INTEGER' },
           fDel: { public: true, type: 'FLOAT' },
           fRet: { public: true, type: 'FLOAT' },
           fCol: { public: true, type: 'FLOAT' },
           fInv: { public: true, type: 'FLOAT' } } },
     fLocation: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fRentQuant: { public: true, type: 'FLOAT' },
     fInvQuant: { public: true, type: 'FLOAT' },
     fRentResDel: { public: true, type: 'FLOAT' },
     fRentResRet: { public: true, type: 'FLOAT' },
     fRentResCol: { public: true, type: 'FLOAT' },
     fRentResInsp: { public: true, type: 'FLOAT' },
     fLastChargeDate: { public: true, type: 'DATE' },
     fRecepyItem: { public: true, type: 'INTEGER' },
     fDone: { public: true, type: 'INTEGER' },
     fAgreeType: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fClientContact: { public: true, type: 'TEXT' },
     fOriginalSerNr: { public: true, type: 'INTEGER' },
     fLastInvoiceDate: { public: true, type: 'DATE' },
     fStartInvoicing: { public: true, type: 'DATE' },
     fEndInvoicing: { public: true, type: 'DATE' },
     fSite: { public: true, type: 'TEXT' },
     fCustOrdNr: { public: true, type: 'TEXT' },
     fNoMinCharge: { public: true, type: 'INTEGER' },
     fDealerCode: { public: true, type: 'TEXT' },
     fDealerName: { public: true, type: 'TEXT' },
     fCommitedUntil: { public: true, type: 'DATE' },
     fCommitedSum: { public: true, type: 'FLOAT' },
     fAdvPrActive: { public: true, type: 'INTEGER' },
     fSalesMan: { public: true, type: 'TEXT' },
     fSalesGroup: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex356: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }