module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fRndTotal: { public: true, type: 'INTEGER' },
     fRndVat: { public: true, type: 'INTEGER' },
     fRndFIFO: { public: true, type: 'INTEGER' },
     fDiscount: { public: true, type: 'INTEGER' },
     fVATCalcWay: { public: true, type: 'INTEGER' },
     fRndDefaultDecs: { public: true, type: 'INTEGER' },
     fRndDefaultStep: { public: true, type: 'INTEGER' },
     fRndDefaultMode: { public: true, type: 'INTEGER' },
     fRndDefaultDirec: { public: true, type: 'INTEGER' },
     fRndDefaultCurDecs: { public: true, type: 'INTEGER' },
     fRndDefaultCurStep: { public: true, type: 'INTEGER' },
     fRndDefaultCurMode: { public: true, type: 'INTEGER' },
     fRndDefaultCurDirec: { public: true, type: 'INTEGER' },
     fRndTotalDecs: { public: true, type: 'INTEGER' },
     fRndTotalStep: { public: true, type: 'INTEGER' },
     fRndTotalMode: { public: true, type: 'INTEGER' },
     fRndTotalDirec: { public: true, type: 'INTEGER' },
     fRndVATDecs: { public: true, type: 'INTEGER' },
     fRndVATStep: { public: true, type: 'INTEGER' },
     fRndVATMode: { public: true, type: 'INTEGER' },
     fRndVATDirec: { public: true, type: 'INTEGER' },
     fRndCostDecs: { public: true, type: 'INTEGER' },
     fRndCostStep: { public: true, type: 'INTEGER' },
     fRndCostMode: { public: true, type: 'INTEGER' },
     fRndCostDirec: { public: true, type: 'INTEGER' },
     fRndRowsumDecs: { public: true, type: 'INTEGER' },
     fRndRowsumStep: { public: true, type: 'INTEGER' },
     fRndRowsumMode: { public: true, type: 'INTEGER' },
     fRndRowsumDirec: { public: true, type: 'INTEGER' } } }