module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fSign: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fTransTime: { public: true, type: 'TIME' },
     fLocalMachineCode: { public: true, type: 'TEXT' },
     fDrawerCode: { public: true, type: 'TEXT' },
     fCCAccountID: { public: true, type: 'TEXT' },
     fCCMerchantID: { public: true, type: 'TEXT' },
     fCreditCard: { public: true, type: 'TEXT' },
     fPaymentReference: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fExpiryMonth: { public: true, type: 'INTEGER' },
     fExpiryYear: { public: true, type: 'INTEGER' },
     fCVC: { public: true, type: 'TEXT' },
     fStartMonth: { public: true, type: 'INTEGER' },
     fStartYear: { public: true, type: 'INTEGER' },
     fIssueNr: { public: true, type: 'TEXT' },
     fBranchID: { public: true, type: 'TEXT' },
     fAmount: { public: true, type: 'FLOAT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fCardType: { public: true, type: 'TEXT' },
     fFileName: { public: true, type: 'TEXT' },
     fTransNr: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex757: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }