module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fTransDate: { public: true, type: 'DATE' },
     fFileName: { public: true, type: 'TEXT' },
     fTransNr: { public: true, type: 'INTEGER' },
     fLocOKNr: { public: true, type: 'FLOAT' },
     fRecordWeight: { public: true, type: 'INTEGER' },
     fQty: { public: true, type: 'FLOAT' },
     fTotCostPrice: { public: true, type: 'FLOAT' },
     fWATotCost: { public: true, type: 'FLOAT' },
     fCPTotCost: { public: true, type: 'FLOAT' },
     fBPTotCost: { public: true, type: 'FLOAT' },
     fWATotCostPerLoc: { public: true, type: 'FLOAT' },
     fCPTotCostPerLoc: { public: true, type: 'FLOAT' },
     fBPTotCostPerLoc: { public: true, type: 'FLOAT' },
     fLocation: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fOKStatus: { public: true, type: 'INTEGER' },
     TempStockVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fRow: { public: true, type: 'INTEGER' },
           fPrimaryCostModel: { public: true, type: 'INTEGER' },
           fQueuedCostModel: { public: true, type: 'INTEGER' },
           fFIFOPerLocation: { public: true, type: 'INTEGER' },
           fItemType: { public: true, type: 'INTEGER' },
           fFIFOPerSerialNr: { public: true, type: 'INTEGER' },
           fNoNLCostOnShip: { public: true, type: 'INTEGER' },
           fWAPerLocation: { public: true, type: 'INTEGER' },
           fWABase2: { public: true, type: 'INTEGER' },
           fUpdWeightAvFromRetPU: { public: true, type: 'INTEGER' },
           fUpdWeightAvFromRet: { public: true, type: 'INTEGER' },
           fStockAffectf: { public: true, type: 'INTEGER' } } } },
  indexes: 
   { TransDateIndex52: 
      { fields: [ 'fTransDate', 'fLocOKNr', 'fFileName', 'fTransNr' ],
        indicesType: 'UNIQUE' } } }