module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fCustCode: { public: true, type: 'TEXT' },
     fCustName: { public: true, type: 'TEXT' },
     fService: { public: true, type: 'TEXT' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fType: { public: true, type: 'INTEGER' },
     fExtraPerClick: { public: true, type: 'INTEGER' },
     fQuant: { public: true, type: 'FLOAT' },
     fUsedQuant: { public: true, type: 'FLOAT' },
     fClosed: { public: true, type: 'INTEGER' },
     fCUServiceNr: { public: true, type: 'INTEGER' },
     fCountdownClicks: { public: true, type: 'INTEGER' },
     fMath: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex554: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }