module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fActType: { public: true, type: 'TEXT' },
     fCustCode: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fCustCat: { public: true, type: 'TEXT' },
     fClassification: { public: true, type: 'TEXT' },
     fContact: { public: true, type: 'TEXT' },
     fHeader: { public: true, type: 'TEXT' },
     fDocName: { public: true, type: 'TEXT' },
     fGreet: { public: true, type: 'TEXT' },
     fShortSign: { public: true, type: 'TEXT' },
     fSignature: { public: true, type: 'TEXT' },
     fTransDate: { public: true, type: 'DATE' },
     fTransTime: { public: true, type: 'TIME' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fAllCont: { public: true, type: 'INTEGER' },
     fPrintdf: { public: true, type: 'INTEGER' },
     fLTxtCode: { public: true, type: 'TEXT' },
     fJobDesc: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fMinSum: { public: true, type: 'FLOAT' },
     fContClass: { public: true, type: 'TEXT' },
     fAddr0: { public: true, type: 'TEXT' },
     fAddr1: { public: true, type: 'TEXT' },
     fAddr2: { public: true, type: 'TEXT' },
     fEmailAddr: { public: true, type: 'TEXT' },
     fFax: { public: true, type: 'TEXT' },
     fMath: { public: true, type: 'TEXT' },
     fAddr3: { public: true, type: 'TEXT' },
     fAddr4: { public: true, type: 'TEXT' },
     fTyp: { public: true, type: 'INTEGER' },
     fReplyToAddr: { public: true, type: 'TEXT' },
     fPersColCode: { public: true, type: 'TEXT' },
     fGuestCode: { public: true, type: 'TEXT' },
     fMarketing: { public: true, type: 'INTEGER' },
     fHtmlTemplate: { public: true, type: 'TEXT' },
     fHtmlFlag: { public: true, type: 'INTEGER' },
     fTransNr: { public: true, type: 'INTEGER' },
     fFileName: { public: true, type: 'TEXT' },
     fCampaignCode: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex152: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }