module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fTransTime: { public: true, type: 'TIME' },
     fLockedFlag: { public: true, type: 'INTEGER' },
     fSendFlag: { public: true, type: 'INTEGER' },
     fPerson: { public: true, type: 'TEXT' },
     fPhoneNo: { public: true, type: 'TEXT' },
     fFromPhoneNo: { public: true, type: 'TEXT' },
     fCustCode: { public: true, type: 'TEXT' },
     fMath: { public: true, type: 'TEXT' },
     fLTxtCode: { public: true, type: 'TEXT' },
     fCheckSum: { public: true, type: 'INTEGER' },
     fMessageType: { public: true, type: 'INTEGER' },
     fChatId: { public: true, type: 'TEXT' },
     fSkypeChatMsgId: { public: true, type: 'INTEGER' },
     fSkypeChatParties: { public: true, type: 'TEXT' },
     fSubMessageType: { public: true, type: 'INTEGER' },
     fCustCode2: { public: true, type: 'TEXT' },
     fPersons: { public: true, type: 'TEXT' },
     fEncryptedf: { public: true, type: 'INTEGER' },
     fPrivacyLevel: { public: true, type: 'INTEGER' },
     fCopiedf: { public: true, type: 'INTEGER' },
     fCallStatus: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex172: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }