module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fIP: { public: true, type: 'TEXT' },
     fWebPort: { public: true, type: 'INTEGER' },
     fStatus: { public: true, type: 'TEXT' },
     fIStatus: { public: true, type: 'INTEGER' },
     fDBSize: { public: true, type: 'INTEGER' },
     fHDFree: { public: true, type: 'INTEGER' },
     fOnline: { public: true, type: 'INTEGER' },
     fRunning: { public: true, type: 'INTEGER' },
     fDisable: { public: true, type: 'INTEGER' },
     fTransDate: { public: true, type: 'DATE' },
     fTransTime: { public: true, type: 'TIME' } },
  indexes: { CodeIndex552: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }