module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fProject: { public: true, type: 'TEXT' },
     fItem: { public: true, type: 'TEXT' },
     fDesc: { public: true, type: 'TEXT' },
     fEstimate: { public: true, type: 'INTEGER' },
     fValue: { public: true, type: 'FLOAT' },
     fDiscount: { public: true, type: 'FLOAT' },
     fPRName: { public: true, type: 'TEXT' },
     fInvSeparately: { public: true, type: 'INTEGER' },
     fSum: { public: true, type: 'FLOAT' },
     fNoInvBefore: { public: true, type: 'DATE' },
     fSumInvoiced: { public: true, type: 'FLOAT' },
     TBVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fPerson: { public: true, type: 'TEXT' },
           fBudQty: { public: true, type: 'FLOAT' },
           fSpentQty: { public: true, type: 'FLOAT' },
           fInvoicedQty: { public: true, type: 'FLOAT' },
           fMarkupQty: { public: true, type: 'FLOAT' },
           fToInvoiceQty: { public: true, type: 'FLOAT' },
           fPrice: { public: true, type: 'FLOAT' },
           fCostInvd: { public: true, type: 'FLOAT' },
           fCostToInv: { public: true, type: 'FLOAT' } } } },
  indexes: { ProjectIndex84: { fields: [ 'fProject', 'fItem' ], indicesType: 'UNIQUE' } } }