module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fPayTypeCreditCard: { public: true, type: 'INTEGER' },
     fPayTypeOrder: { public: true, type: 'INTEGER' },
     fPayTypeDirectDebit: { public: true, type: 'INTEGER' },
     fPayTypePayPal: { public: true, type: 'INTEGER' },
     fDefaultCust: { public: true, type: 'TEXT' },
     fDefaultFreight: { public: true, type: 'TEXT' },
     fPayDealCreditCard: { public: true, type: 'TEXT' },
     fPayDealOrder: { public: true, type: 'TEXT' },
     fPayDealDirectDebit: { public: true, type: 'TEXT' },
     fPayDealPayPal: { public: true, type: 'TEXT' },
     fDefaultDispGroup: { public: true, type: 'TEXT' },
     fDontOKInvoices: { public: true, type: 'INTEGER' },
     fOrderClass: { public: true, type: 'TEXT' },
     fPayTypeInvoice: { public: true, type: 'INTEGER' },
     fPayDealInvoice: { public: true, type: 'TEXT' },
     fCatalogSort: { public: true, type: 'INTEGER' },
     fHidePricesNotLoggedIn: { public: true, type: 'INTEGER' },
     fInfoElCreditCard: { public: true, type: 'TEXT' },
     fInfoElOrder: { public: true, type: 'TEXT' },
     fInfoElDirectDebit: { public: true, type: 'TEXT' },
     fInfoElPayPal: { public: true, type: 'TEXT' },
     fInfoElInvoice: { public: true, type: 'TEXT' },
     fPaginationType: { public: true, type: 'INTEGER' },
     fItemsPerPage: { public: true, type: 'INTEGER' },
     fMaxPages: { public: true, type: 'INTEGER' },
     fCCPaymentOpt: { public: true, type: 'INTEGER' },
     fPayModeCreditCard: { public: true, type: 'TEXT' },
     fPayModePayPal: { public: true, type: 'TEXT' },
     fSalesMan: { public: true, type: 'TEXT' },
     fLocation: { public: true, type: 'TEXT' },
     fDontOKOrders: { public: true, type: 'INTEGER' },
     fStockCheck: { public: true, type: 'INTEGER' },
     fIncludeOrdQty: { public: true, type: 'INTEGER' },
     fUseExistingOrders: { public: true, type: 'INTEGER' },
     fWebOTCode: { public: true, type: 'TEXT' },
     fShowDelModes: { public: true, type: 'INTEGER' } } }