module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fLangCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fBill1: { public: true, type: 'TEXT' },
     fBill4: { public: true, type: 'TEXT' },
     fBill9: { public: true, type: 'TEXT' },
     fMill1: { public: true, type: 'TEXT' },
     fMill4: { public: true, type: 'TEXT' },
     fMill9: { public: true, type: 'TEXT' },
     fThou1: { public: true, type: 'TEXT' },
     fThou4: { public: true, type: 'TEXT' },
     fThou9: { public: true, type: 'TEXT' },
     fHoun1: { public: true, type: 'TEXT' },
     fHoun2: { public: true, type: 'TEXT' },
     fHoun3: { public: true, type: 'TEXT' },
     fHoun4: { public: true, type: 'TEXT' },
     fHoun5: { public: true, type: 'TEXT' },
     fHoun6: { public: true, type: 'TEXT' },
     fHoun7: { public: true, type: 'TEXT' },
     fHoun8: { public: true, type: 'TEXT' },
     fHoun9: { public: true, type: 'TEXT' },
     fZero: { public: true, type: 'TEXT' },
     fMainPart: { public: true, type: 'TEXT' },
     fDeciPart: { public: true, type: 'TEXT' },
     fEndText: { public: true, type: 'TEXT' },
     fCurCodeVer: { public: true, type: 'INTEGER' },
     fMinorInText: { public: true, type: 'INTEGER' },
     fBill10: { public: true, type: 'TEXT' },
     fMill10: { public: true, type: 'TEXT' },
     fThou10: { public: true, type: 'TEXT' },
     fCutDecimals: { public: true, type: 'INTEGER' },
     fHoun1Single: { public: true, type: 'TEXT' },
     LangNrVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fValText: { public: true, type: 'TEXT' },
           fValTextF: { public: true, type: 'TEXT' } } } },
  indexes: { LangCodeIndex155: { fields: [ 'fLangCode' ], indicesType: 'UNIQUE' } } }