module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fDescription: { public: true, type: 'TEXT' },
     fService: { public: true, type: 'TEXT' },
     fServiceName: { public: true, type: 'TEXT' },
     fCountry: { public: true, type: 'INTEGER' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fClosed: { public: true, type: 'INTEGER' },
     fType: { public: true, type: 'INTEGER' },
     fPerLength: { public: true, type: 'INTEGER' },
     fExtraPerClick: { public: true, type: 'INTEGER' },
     fClassification: { public: true, type: 'TEXT' },
     fSortOrder: { public: true, type: 'INTEGER' },
     fSetupItem: { public: true, type: 'TEXT' },
     fCanBuyOnline: { public: true, type: 'INTEGER' },
     ISPackageVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fTyp: { public: true, type: 'INTEGER' },
           fArtCode: { public: true, type: 'TEXT' },
           fQuant: { public: true, type: 'FLOAT' },
           fPrice: { public: true, type: 'FLOAT' },
           fText: { public: true, type: 'TEXT' } } },
     fSetupPrice: { public: true, type: 'FLOAT' } },
  indexes: { CodeIndex584: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }