module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     DocVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fUnitType: { public: true, type: 'INTEGER' },
           fXpos: { public: true, type: 'FLOAT' },
           fYpos: { public: true, type: 'FLOAT' },
           fUnitWidth: { public: true, type: 'FLOAT' },
           fUnitHeight: { public: true, type: 'FLOAT' },
           fUnitStyle: { public: true, type: 'TEXT' },
           fUnitText: { public: true, type: 'TEXT' },
           fJust: { public: true, type: 'INTEGER' },
           fLineHeight: { public: true, type: 'INTEGER' },
           fFieldSetNr: { public: true, type: 'INTEGER' },
           fClip: { public: true, type: 'INTEGER' },
           fEscSeq: { public: true, type: 'TEXT' },
           fExcludeFirst: { public: true, type: 'INTEGER' },
           fExcludeMiddle: { public: true, type: 'INTEGER' },
           fExcludeLast: { public: true, type: 'INTEGER' },
           fExcludeOnly: { public: true, type: 'INTEGER' },
           fWordWrap: { public: true, type: 'INTEGER' },
           fFormatNr: { public: true, type: 'INTEGER' },
           fPageSumType: { public: true, type: 'INTEGER' } } },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fNrOfMatrixLinesOnly: { public: true, type: 'INTEGER' },
     fPcFormLines: { public: true, type: 'INTEGER' },
     fPcFormVisible: { public: true, type: 'INTEGER' },
     fPcFormMargin: { public: true, type: 'INTEGER' },
     fPcFormCRend: { public: true, type: 'INTEGER' },
     fNrofex: { public: true, type: 'INTEGER' },
     fDocName: { public: true, type: 'TEXT' },
     fJobDf: { public: true, type: 'INTEGER' },
     fExtext0: { public: true, type: 'TEXT' },
     fPaperTray0: { public: true, type: 'TEXT' },
     fExtext1: { public: true, type: 'TEXT' },
     fPaperTray1: { public: true, type: 'TEXT' },
     fExtext2: { public: true, type: 'TEXT' },
     fPaperTray2: { public: true, type: 'TEXT' },
     fExtext3: { public: true, type: 'TEXT' },
     fPaperTray3: { public: true, type: 'TEXT' },
     fExtext4: { public: true, type: 'TEXT' },
     fPaperTray4: { public: true, type: 'TEXT' },
     fDocType: { public: true, type: 'INTEGER' },
     fNrOfMatrixLinesFirst: { public: true, type: 'INTEGER' },
     fNrOfMatrixLinesMiddle: { public: true, type: 'INTEGER' },
     fNrOfMatrixLinesLast: { public: true, type: 'INTEGER' },
     fHalRoutine: { public: true, type: 'TEXT' },
     fDontPrintf: { public: true, type: 'INTEGER' },
     fHeaderStyle: { public: true, type: 'TEXT' },
     fHeaderHeight: { public: true, type: 'INTEGER' },
     fDescriptionStyle: { public: true, type: 'TEXT' },
     fDescriptionHeight: { public: true, type: 'INTEGER' },
     fItemlineStyle: { public: true, type: 'TEXT' },
     fItemlineHeight: { public: true, type: 'INTEGER' },
     fSubTotalStyle: { public: true, type: 'TEXT' },
     fSubTotalHeight: { public: true, type: 'INTEGER' },
     fCreditInvStyle: { public: true, type: 'TEXT' },
     fCreditInvHeight: { public: true, type: 'INTEGER' },
     fPrepaymentStyle: { public: true, type: 'TEXT' },
     fPrepaymentHeight: { public: true, type: 'INTEGER' },
     fCodePage: { public: true, type: 'INTEGER' },
     fPdfOrient: { public: true, type: 'INTEGER' },
     fWtihholdingStyle: { public: true, type: 'TEXT' },
     fWtihholdingHeight: { public: true, type: 'INTEGER' },
     fMultiBuyRebStyle: { public: true, type: 'TEXT' },
     fMultiBuyRebHeight: { public: true, type: 'INTEGER' },
     fShowGrid: { public: true, type: 'INTEGER' },
     fEditScale: { public: true, type: 'INTEGER' } },
  indexes: { MainKeyIndex135: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }