module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fHead0: { public: true, type: 'TEXT' },
     fHead1: { public: true, type: 'TEXT' },
     fHead2: { public: true, type: 'TEXT' },
     fHead3: { public: true, type: 'TEXT' },
     fHead4: { public: true, type: 'TEXT' },
     fFoot0: { public: true, type: 'TEXT' },
     fFoot1: { public: true, type: 'TEXT' },
     fFoot2: { public: true, type: 'TEXT' },
     fFoot3: { public: true, type: 'TEXT' },
     fFoot4: { public: true, type: 'TEXT' },
     fPrinterType: { public: true, type: 'INTEGER' },
     fMinCashLen: { public: true, type: 'INTEGER' },
     fCommPort: { public: true, type: 'TEXT' },
     fDisplayText: { public: true, type: 'TEXT' },
     fFiscalPrinter: { public: true, type: 'INTEGER' },
     MachineCashVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fRegDef: { public: true, type: 'TEXT' },
           fCUVATRules: { public: true, type: 'INTEGER' } } },
     fWithExtraText: { public: true, type: 'INTEGER' },
     fControlHasarExtraText: { public: true, type: 'INTEGER' },
     fAddHeader: { public: true, type: 'INTEGER' },
     fAddFooter: { public: true, type: 'INTEGER' },
     fVATNrCheck: { public: true, type: 'INTEGER' },
     fCustNameCheck: { public: true, type: 'INTEGER' },
     fLogLevel: { public: true, type: 'INTEGER' },
     fAnsTimeOut: { public: true, type: 'INTEGER' },
     fDefFiscalFlag: { public: true, type: 'INTEGER' },
     fPrintSerialInfo: { public: true, type: 'INTEGER' },
     fPrintBarCode: { public: true, type: 'INTEGER' },
     fPrintAltCode: { public: true, type: 'INTEGER' },
     fPrintSalesMan: { public: true, type: 'INTEGER' },
     fPrintCashier: { public: true, type: 'INTEGER' },
     fGlobalDiscount: { public: true, type: 'INTEGER' },
     fPrintDiscount: { public: true, type: 'INTEGER' },
     fCheckClock: { public: true, type: 'INTEGER' },
     fCheckEnabler: { public: true, type: 'INTEGER' } },
  indexes: { CodeIndex318: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }