module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fCustCode: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fDesc0: { public: true, type: 'TEXT' },
     fDesc1: { public: true, type: 'TEXT' },
     fDesc2: { public: true, type: 'TEXT' },
     fCustName: { public: true, type: 'TEXT' },
     fTerminated: { public: true, type: 'INTEGER' },
     fStopInvoicing: { public: true, type: 'INTEGER' },
     fLeader: { public: true, type: 'TEXT' },
     fLeaderName: { public: true, type: 'TEXT' },
     fStartDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fInvoiceTime: { public: true, type: 'INTEGER' },
     fInvoicePurch: { public: true, type: 'INTEGER' },
     fInvoiceStock: { public: true, type: 'INTEGER' },
     fNoInvBefore: { public: true, type: 'DATE' },
     fBuildOn: { public: true, type: 'INTEGER' },
     fContact: { public: true, type: 'TEXT' },
     fPRCodeOnInv: { public: true, type: 'INTEGER' },
     fPRNameOnInv: { public: true, type: 'INTEGER' },
     fPRContOnInv: { public: true, type: 'INTEGER' },
     fPRTextOnInv: { public: true, type: 'INTEGER' },
     PRVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fPlanDate: { public: true, type: 'DATE' },
           fInvNr: { public: true, type: 'INTEGER' },
           fValStr: { public: true, type: 'FLOAT' },
           fPerson: { public: true, type: 'TEXT' },
           fComment: { public: true, type: 'TEXT' },
           fInvFlag: { public: true, type: 'INTEGER' },
           fRetentionPrc: { public: true, type: 'FLOAT' },
           fRowType: { public: true, type: 'INTEGER' },
           fPRStage: { public: true, type: 'TEXT' } } },
     fTimexSum: { public: true, type: 'FLOAT' },
     fPurSum: { public: true, type: 'FLOAT' },
     fTotSum: { public: true, type: 'FLOAT' },
     fTimBudModel: { public: true, type: 'INTEGER' },
     fPurBudModel: { public: true, type: 'INTEGER' },
     fType: { public: true, type: 'INTEGER' },
     fPRClass: { public: true, type: 'TEXT' },
     fText0: { public: true, type: 'TEXT' },
     fText1: { public: true, type: 'TEXT' },
     fText2: { public: true, type: 'TEXT' },
     fText3: { public: true, type: 'TEXT' },
     fText4: { public: true, type: 'TEXT' },
     fText5: { public: true, type: 'TEXT' },
     fText6: { public: true, type: 'TEXT' },
     fText7: { public: true, type: 'TEXT' },
     fText8: { public: true, type: 'TEXT' },
     fText9: { public: true, type: 'TEXT' },
     fDownPaySent: { public: true, type: 'FLOAT' },
     fDownPayRedcd: { public: true, type: 'FLOAT' },
     fObjects: { public: true, type: 'TEXT' },
     fTimeAvgPriOnInv: { public: true, type: 'INTEGER' },
     fTimeAvgQtyOnInv: { public: true, type: 'INTEGER' },
     fPurcAvgPriOnInv: { public: true, type: 'INTEGER' },
     fPurcAvgQtyOnInv: { public: true, type: 'INTEGER' },
     fInvoiceMaterial: { public: true, type: 'INTEGER' },
     fStatMark: { public: true, type: 'INTEGER' },
     fMotherCode: { public: true, type: 'TEXT' },
     fLangCode: { public: true, type: 'TEXT' },
     fInvSepTB: { public: true, type: 'INTEGER' },
     fInvSepPB: { public: true, type: 'INTEGER' },
     fSalesGroup: { public: true, type: 'TEXT' },
     fPrSalesMan: { public: true, type: 'TEXT' },
     fEmail: { public: true, type: 'TEXT' },
     fRetSum: { public: true, type: 'FLOAT' },
     fRetInvd: { public: true, type: 'FLOAT' },
     fMembers: { public: true, type: 'TEXT' },
     fFinishedDate: { public: true, type: 'DATE' },
     fItemPerDay: { public: true, type: 'INTEGER' },
     fPRLeaderOnInv: { public: true, type: 'INTEGER' },
     fPeriodOnInv: { public: true, type: 'INTEGER' },
     fLeader2: { public: true, type: 'TEXT' },
     fLeader2Name: { public: true, type: 'TEXT' },
     fLeader3: { public: true, type: 'TEXT' },
     fLeader3Name: { public: true, type: 'TEXT' },
     fLeader4: { public: true, type: 'TEXT' },
     fLeader4Name: { public: true, type: 'TEXT' },
     fPRStage: { public: true, type: 'TEXT' },
     fPRClassification: { public: true, type: 'TEXT' },
     fLeader5: { public: true, type: 'TEXT' },
     fLeader5Name: { public: true, type: 'TEXT' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fUseWIP: { public: true, type: 'INTEGER' },
     fTBIVItemsUsage: { public: true, type: 'INTEGER' },
     fMaxRetSum: { public: true, type: 'FLOAT' },
     fPayDeal: { public: true, type: 'TEXT' },
     fCustOrdNr: { public: true, type: 'TEXT' },
     fDeliverySiteCode: { public: true, type: 'TEXT' },
     fWorkSiteNumber: { public: true, type: 'TEXT' } },
  indexes: { CodeIndex4: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }