module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fStaffType: { public: true, type: 'INTEGER' },
     fLim1: { public: true, type: 'FLOAT' },
     fLim2: { public: true, type: 'FLOAT' },
     fLim3: { public: true, type: 'FLOAT' },
     fLim4: { public: true, type: 'FLOAT' },
     fLim5: { public: true, type: 'FLOAT' },
     fLim6: { public: true, type: 'FLOAT' },
     fLim7: { public: true, type: 'FLOAT' },
     fLim8: { public: true, type: 'FLOAT' },
     fLim9: { public: true, type: 'FLOAT' } },
  indexes: { CodeIndex78: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }