module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fAPIToken: { public: true, type: 'TEXT' },
     fLastLogAction: { public: true, type: 'INTEGER' },
     fAPIKey: { public: true, type: 'TEXT' },
     fLastAppStoreReview: { public: true, type: 'DATE' },
     fLastAppStoreStat: { public: true, type: 'DATE' },
     fExecTime: { public: true, type: 'TIME' },
     fExportActivities: { public: true, type: 'INTEGER' },
     fLastActivity: { public: true, type: 'INTEGER' },
     fActiveFlag: { public: true, type: 'INTEGER' },
     fExportLogActions: { public: true, type: 'INTEGER' },
     fExportReviews: { public: true, type: 'INTEGER' },
     fExportStats: { public: true, type: 'INTEGER' },
     fExportPresContacts: { public: true, type: 'INTEGER' },
     fExportMPContacts: { public: true, type: 'INTEGER' },
     fExportMPSubscriptions: { public: true, type: 'INTEGER' },
     fLastMPSubscription: { public: true, type: 'INTEGER' },
     fLastMPContact: { public: true, type: 'DATE' },
     fLastPresContact: { public: true, type: 'INTEGER' },
     fContOnFail: { public: true, type: 'INTEGER' },
     fExportEmailViews: { public: true, type: 'INTEGER' },
     fExportValidatedMails: { public: true, type: 'INTEGER' },
     fLastEmailView: { public: true, type: 'INTEGER' },
     fLastValidatedMail: { public: true, type: 'DATE' },
     fExcludeMail: { public: true, type: 'TEXT' },
     fLastSentEmail: { public: true, type: 'INTEGER' },
     fExportSentEmails: { public: true, type: 'INTEGER' },
     fLastProdHist: { public: true, type: 'INTEGER' },
     fExportProdHist: { public: true, type: 'INTEGER' },
     fLastStandardIDLoginExDate: { public: true, type: 'DATE' },
     fExportStandardIDLogins: { public: true, type: 'INTEGER' },
     fExcludeTestMPSubscriptions: { public: true, type: 'INTEGER' } } }