module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     SDVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fArtCode: { public: true, type: 'TEXT' },
           fSpec: { public: true, type: 'TEXT' },
           fSerialNr: { public: true, type: 'TEXT' },
           fQty: { public: true, type: 'FLOAT' },
           fFIFO: { public: true, type: 'FLOAT' },
           fLocation: { public: true, type: 'TEXT' },
           fRecepy: { public: true, type: 'TEXT' },
           fVARList: { public: true, type: 'TEXT' },
           fObjects: { public: true, type: 'TEXT' },
           fCostAcc: { public: true, type: 'TEXT' },
           fFIFORowVal: { public: true, type: 'FLOAT' },
           fCoefficient: { public: true, type: 'FLOAT' },
           fBasePrice: { public: true, type: 'FLOAT' },
           fIntORRow: { public: true, type: 'INTEGER' },
           fUnitXval: { public: true, type: 'FLOAT' },
           fUnitYval: { public: true, type: 'FLOAT' },
           fUnitZval: { public: true, type: 'FLOAT' },
           fPRCodeRow: { public: true, type: 'TEXT' },
           fPosCode: { public: true, type: 'TEXT' },
           fACShort: { public: true, type: 'TEXT' } } },
     fTransDate: { public: true, type: 'DATE' },
     fCostAcc: { public: true, type: 'TEXT' },
     fOKFlag: { public: true, type: 'INTEGER' },
     fLocation: { public: true, type: 'TEXT' },
     fPRCode: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fObjects: { public: true, type: 'TEXT' },
     fExportedFlag: { public: true, type: 'INTEGER' },
     fTotQty: { public: true, type: 'FLOAT' },
     fLocOKNr: { public: true, type: 'FLOAT' },
     fIntORNo: { public: true, type: 'INTEGER' },
     fSDClass: { public: true, type: 'TEXT' },
     fACShort: { public: true, type: 'TEXT' },
     fRefStr: { public: true, type: 'TEXT' },
     fInvalid: { public: true, type: 'INTEGER' },
     fInvalidDate: { public: true, type: 'DATE' },
     fReason: { public: true, type: 'TEXT' },
     fAcceptanceStatus: { public: true, type: 'INTEGER' },
     fAcceptanceBy: { public: true, type: 'TEXT' },
     fAcceptanceFYI: { public: true, type: 'TEXT' },
     fSign: { public: true, type: 'TEXT' },
     fSalesGroup: { public: true, type: 'TEXT' } },
  indexes: { SerNrIndex167: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }