module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fController: { public: true, type: 'TEXT' },
     fRemoteCloudServer: { public: true, type: 'TEXT' },
     fAllControllers: { public: true, type: 'INTEGER' },
     fAllRemoteCloudServers: { public: true, type: 'INTEGER' },
     fRepeatInterval: { public: true, type: 'TIME' },
     fClosed: { public: true, type: 'INTEGER' },
     fWatchpoint: { public: true, type: 'INTEGER' },
     fWatchpointParam: { public: true, type: 'TEXT' },
     fStdTxt: { public: true, type: 'TEXT' },
     CloudWatchpointVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fContactCode: { public: true, type: 'TEXT' },
           fContactName: { public: true, type: 'TEXT' },
           fMobile: { public: true, type: 'TEXT' },
           fNotifLevel: { public: true, type: 'INTEGER' } } },
     fServerName: { public: true, type: 'TEXT' },
     fComment: { public: true, type: 'TEXT' },
     fLastCheckDate: { public: true, type: 'DATE' },
     fLastCheckTime: { public: true, type: 'TIME' },
     fExcludeAutoNodes: { public: true, type: 'INTEGER' },
     fExcludeOnDemand: { public: true, type: 'INTEGER' },
     fExcludeController: { public: true, type: 'TEXT' },
     fSMSInterval: { public: true, type: 'TIME' },
     fEscalateTimeAll: { public: true, type: 'INTEGER' },
     fEscalateTime1: { public: true, type: 'INTEGER' },
     fEscalateTimeAll1: { public: true, type: 'INTEGER' },
     fEscalateTime2: { public: true, type: 'INTEGER' } },
  indexes: { SerNrIndex767: { fields: [ 'fSerNr' ], indicesType: 'UNIQUE' } } }