module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fSerNr: { public: true, type: 'INTEGER' },
     fRecType: { public: true, type: 'INTEGER' },
     fRowNr: { public: true, type: 'INTEGER' },
     fComment: { public: true, type: 'TEXT' },
     JobPriceVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fStayDay: { public: true, type: 'DATE' },
           fPriceList: { public: true, type: 'TEXT' },
           fVRebate: { public: true, type: 'FLOAT' },
           fPrice: { public: true, type: 'FLOAT' },
           fSum: { public: true, type: 'FLOAT' },
           fArtCode: { public: true, type: 'TEXT' },
           fVATCode: { public: true, type: 'TEXT' },
           fQty: { public: true, type: 'FLOAT' },
           fAgreedPrice: { public: true, type: 'FLOAT' },
           fPerson: { public: true, type: 'TEXT' },
           fCClass: { public: true, type: 'TEXT' },
           fRackRatePrice: { public: true, type: 'FLOAT' },
           fAgreedRebate: { public: true, type: 'FLOAT' },
           fPriceRules: { public: true, type: 'TEXT' },
           fPriceCalc: { public: true, type: 'TEXT' } } },
     fTransDate: { public: true, type: 'DATE' },
     fEndDate: { public: true, type: 'DATE' },
     fStartTime: { public: true, type: 'TIME' },
     fEndTime: { public: true, type: 'TIME' },
     fXQtyConv: { public: true, type: 'TEXT' },
     fType: { public: true, type: 'TEXT' },
     fResUsage: { public: true, type: 'TEXT' },
     fPriceList: { public: true, type: 'TEXT' },
     fNoOfGuests: { public: true, type: 'INTEGER' },
     fCurncyCode: { public: true, type: 'TEXT' },
     fFrRate: { public: true, type: 'FLOAT' },
     fToRateB1: { public: true, type: 'FLOAT' },
     fToRateB2: { public: true, type: 'FLOAT' },
     fBaseRate1: { public: true, type: 'FLOAT' },
     fBaseRate2: { public: true, type: 'FLOAT' } },
  indexes: 
   { SerNrIndex292: 
      { fields: [ 'fRecType', 'fSerNr', 'fRowNr' ],
        indicesType: 'UNIQUE' } } }