module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fCode: { public: true, type: 'TEXT' },
     fName: { public: true, type: 'TEXT' },
     fAccessGroup: { public: true, type: 'TEXT' },
     fEmailAddr: { public: true, type: 'TEXT' },
     fNewPassWord: { public: true, type: 'INTEGER' },
     fLangCode: { public: true, type: 'TEXT' },
     fFTPLogin: { public: true, type: 'INTEGER' },
     fClosed: { public: true, type: 'INTEGER' },
     fOnlyVoiceLogin: { public: true, type: 'INTEGER' },
     fDateCreated: { public: true, type: 'DATE' },
     fOneFunction: { public: true, type: 'TEXT' },
     fTypeOfUser: { public: true, type: 'INTEGER' },
     fCanUseOS: { public: true, type: 'INTEGER' },
     fMagic: { public: true, type: 'INTEGER' },
     fNewf: { public: true, type: 'INTEGER' },
     GlobalUserVcMatrix: 
      { public: true,
        type: 'MATRIX',
        label: 'Math',
        fields: 
         { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
           fCompCode: { public: true, type: 'TEXT' },
           fCompName: { public: true, type: 'TEXT' },
           fAccessGroup: { public: true, type: 'TEXT' },
           fStartLevel: { public: true, type: 'INTEGER' } } },
     fMainCRMCompany: { public: true, type: 'TEXT' },
     fCustCode: { public: true, type: 'TEXT' },
     fRegistrationNumber: { public: true, type: 'INTEGER' },
     fStartLevel: { public: true, type: 'INTEGER' },
     fMagic2: { public: true, type: 'INTEGER' },
     fDiscPassword: { public: true, type: 'INTEGER' },
     fPasswordNeverExpires: { public: true, type: 'INTEGER' },
     fExpiryDate: { public: true, type: 'DATE' },
     fExtraCRMCompanies: { public: true, type: 'TEXT' },
     fUnlicensed: { public: true, type: 'INTEGER' },
     fAstPBXConnection: { public: true, type: 'TEXT' },
     fAstUserName: { public: true, type: 'TEXT' },
     fAstPassword: { public: true, type: 'TEXT' },
     fAstCallerIdNumber: { public: true, type: 'TEXT' },
     fXAstCallerIdName: { public: true, type: 'TEXT' },
     fExcludeQueueFallbackf: { public: true, type: 'INTEGER' },
     fLinPhonef: { public: true, type: 'INTEGER' },
     fLoginEmailAddr: { public: true, type: 'TEXT' },
     fAdminFlag: { public: true, type: 'INTEGER' } },
  indexes: { CodeIndex441: { fields: [ 'fCode' ], indicesType: 'UNIQUE' } } }