module.exports = { fields: 
   { id: { type: 'INTEGER', autoIncrement: true, primaryKey: true },
     fTitle: { public: true, type: 'TEXT' },
     fUseTheNewShop: { public: true, type: 'INTEGER' },
     fFrames: { public: true, type: 'INTEGER' },
     fFr1Src: { public: true, type: 'TEXT' },
     fFr1BgColor: { public: true, type: 'TEXT' },
     fFr1BgPict: { public: true, type: 'TEXT' },
     fFr1MenuName: { public: true, type: 'TEXT' },
     fFr1MenuName2: { public: true, type: 'TEXT' },
     fFr2Src: { public: true, type: 'TEXT' },
     fFr2BgColor: { public: true, type: 'TEXT' },
     fFr2BgPict: { public: true, type: 'TEXT' },
     fFr2MenuName: { public: true, type: 'TEXT' },
     fFr2MenuName2: { public: true, type: 'TEXT' },
     fFr3Src: { public: true, type: 'TEXT' },
     fFr3BgColor: { public: true, type: 'TEXT' },
     fFr3BgPict: { public: true, type: 'TEXT' },
     fFr3MenuName: { public: true, type: 'TEXT' },
     fFr3MenuName2: { public: true, type: 'TEXT' },
     fFr4Src: { public: true, type: 'TEXT' },
     fFr4BgColor: { public: true, type: 'TEXT' },
     fFr4BgPict: { public: true, type: 'TEXT' },
     fFr4MenuName: { public: true, type: 'TEXT' },
     fFr4MenuName2: { public: true, type: 'TEXT' },
     fFr5Src: { public: true, type: 'TEXT' },
     fFr5BgColor: { public: true, type: 'TEXT' },
     fFr5BgPict: { public: true, type: 'TEXT' },
     fFr5MenuName: { public: true, type: 'TEXT' },
     fFr5MenuName2: { public: true, type: 'TEXT' } } }